import { BO4EBOAnfrage as Old0 } from "./src/BO4E.BO.Anfrage";
import { Anfrage as New0 } from "./src/Anfrage";
export declare const old0: Old0;
export declare const new0: New0;
import { BO4EBOAngebot as Old1 } from "./src/BO4E.BO.Angebot";
import { Angebot as New1 } from "./src/Angebot";
export declare const old1: Old1;
export declare const new1: New1;
import { BO4EBOAnsprechpartner as Old2 } from "./src/BO4E.BO.Ansprechpartner";
import { Ansprechpartner as New2 } from "./src/Ansprechpartner";
export declare const old2: Old2;
export declare const new2: New2;
import { BO4EBOAuftrag as Old3 } from "./src/BO4E.BO.Auftrag";
import { Auftrag as New3 } from "./src/Auftrag";
export declare const old3: Old3;
export declare const new3: New3;
import { BO4EBOAuftragsStorno as Old4 } from "./src/BO4E.BO.AuftragsStorno";
import { AuftragsStorno as New4 } from "./src/AuftragsStorno";
export declare const old4: Old4;
export declare const new4: New4;
import { BO4EBOAvis as Old5 } from "./src/BO4E.BO.Avis";
import { Avis as New5 } from "./src/Avis";
export declare const old5: Old5;
export declare const new5: New5;
import { BO4EBOBerechnungsformel as Old6 } from "./src/BO4E.BO.Berechnungsformel";
import { Berechnungsformel as New6 } from "./src/Berechnungsformel";
export declare const old6: Old6;
export declare const new6: New6;
import { BO4EBOBilanzierung as Old7 } from "./src/BO4E.BO.Bilanzierung";
import { Bilanzierung as New7 } from "./src/Bilanzierung";
export declare const old7: Old7;
export declare const new7: New7;
import { BO4EBOEnergiemenge as Old8 } from "./src/BO4E.BO.Energiemenge";
import { Energiemenge as New8 } from "./src/Energiemenge";
export declare const old8: Old8;
export declare const new8: New8;
import { BO4EBOEntsperrauftrag as Old9 } from "./src/BO4E.BO.Entsperrauftrag";
import { Entsperrauftrag as New9 } from "./src/Entsperrauftrag";
export declare const old9: Old9;
export declare const new9: New9;
import { BO4EBOGeschaeftspartner as Old10 } from "./src/BO4E.BO.Geschaeftspartner";
import { Geschaeftspartner as New10 } from "./src/Geschaeftspartner";
export declare const old10: Old10;
export declare const new10: New10;
import { BO4EBOHandelsunstimmigkeit as Old11 } from "./src/BO4E.BO.Handelsunstimmigkeit";
import { Handelsunstimmigkeit as New11 } from "./src/Handelsunstimmigkeit";
export declare const old11: Old11;
export declare const new11: New11;
import { BO4EBOKosten as Old12 } from "./src/BO4E.BO.Kosten";
import { Kosten as New12 } from "./src/Kosten";
export declare const old12: Old12;
export declare const new12: New12;
import { BO4EBOMabisZaehlpunkt as Old13 } from "./src/BO4E.BO.MabisZaehlpunkt";
import { MabisZaehlpunkt as New13 } from "./src/MabisZaehlpunkt";
export declare const old13: Old13;
export declare const new13: New13;
import { BO4EBOMarktlokation as Old14 } from "./src/BO4E.BO.Marktlokation";
import { Marktlokation as New14 } from "./src/Marktlokation";
export declare const old14: Old14;
export declare const new14: New14;
import { BO4EBOMarktteilnehmer as Old15 } from "./src/BO4E.BO.Marktteilnehmer";
import { Marktteilnehmer as New15 } from "./src/Marktteilnehmer";
export declare const old15: Old15;
export declare const new15: New15;
import { BO4EBOMesslokation as Old16 } from "./src/BO4E.BO.Messlokation";
import { Messlokation as New16 } from "./src/Messlokation";
export declare const old16: Old16;
export declare const new16: New16;
import { BO4EBONetzlokation as Old17 } from "./src/BO4E.BO.Netzlokation";
import { Netzlokation as New17 } from "./src/Netzlokation";
export declare const old17: Old17;
export declare const new17: New17;
import { BO4EBOPreisblatt as Old18 } from "./src/BO4E.BO.Preisblatt";
import { Preisblatt as New18 } from "./src/Preisblatt";
export declare const old18: Old18;
export declare const new18: New18;
import { BO4EBOPreisblattDienstleistung as Old19 } from "./src/BO4E.BO.PreisblattDienstleistung";
import { PreisblattDienstleistung as New19 } from "./src/PreisblattDienstleistung";
export declare const old19: Old19;
export declare const new19: New19;
import { BO4EBOPreisblattKonzessionsabgabe as Old20 } from "./src/BO4E.BO.PreisblattKonzessionsabgabe";
import { PreisblattKonzessionsabgabe as New20 } from "./src/PreisblattKonzessionsabgabe";
export declare const old20: Old20;
export declare const new20: New20;
import { BO4EBOPreisblattMessung as Old21 } from "./src/BO4E.BO.PreisblattMessung";
import { PreisblattMessung as New21 } from "./src/PreisblattMessung";
export declare const old21: Old21;
export declare const new21: New21;
import { BO4EBOPreisblattNetznutzung as Old22 } from "./src/BO4E.BO.PreisblattNetznutzung";
import { PreisblattNetznutzung as New22 } from "./src/PreisblattNetznutzung";
export declare const old22: Old22;
export declare const new22: New22;
import { BO4EBOPreisblattUmlagen as Old23 } from "./src/BO4E.BO.PreisblattUmlagen";
import { PreisblattUmlagen as New23 } from "./src/PreisblattUmlagen";
export declare const old23: Old23;
export declare const new23: New23;
import { BO4EBORechnung as Old24 } from "./src/BO4E.BO.Rechnung";
import { Rechnung as New24 } from "./src/Rechnung";
export declare const old24: Old24;
export declare const new24: New24;
import { BO4EBORegion as Old25 } from "./src/BO4E.BO.Region";
import { Region as New25 } from "./src/Region";
export declare const old25: Old25;
export declare const new25: New25;
import { BO4EBOReklamation as Old26 } from "./src/BO4E.BO.Reklamation";
import { Reklamation as New26 } from "./src/Reklamation";
export declare const old26: Old26;
export declare const new26: New26;
import { BO4EBOSperrauftrag as Old27 } from "./src/BO4E.BO.Sperrauftrag";
import { Sperrauftrag as New27 } from "./src/Sperrauftrag";
export declare const old27: Old27;
export declare const new27: New27;
import { BO4EBOSperrauftragsStorno as Old28 } from "./src/BO4E.BO.SperrauftragsStorno";
import { SperrauftragsStorno as New28 } from "./src/SperrauftragsStorno";
export declare const old28: Old28;
export declare const new28: New28;
import { BO4EBOStatusbericht as Old29 } from "./src/BO4E.BO.Statusbericht";
import { Statusbericht as New29 } from "./src/Statusbericht";
export declare const old29: Old29;
export declare const new29: New29;
import { BO4EBOSteuerbareRessource as Old30 } from "./src/BO4E.BO.SteuerbareRessource";
import { SteuerbareRessource as New30 } from "./src/SteuerbareRessource";
export declare const old30: Old30;
export declare const new30: New30;
import { BO4EBOSummenzeitreihe as Old31 } from "./src/BO4E.BO.Summenzeitreihe";
import { Summenzeitreihe as New31 } from "./src/Summenzeitreihe";
export declare const old31: Old31;
export declare const new31: New31;
import { BO4EBOTechnischeRessource as Old32 } from "./src/BO4E.BO.TechnischeRessource";
import { TechnischeRessource as New32 } from "./src/TechnischeRessource";
export declare const old32: Old32;
export declare const new32: New32;
import { BO4EBOTranche as Old33 } from "./src/BO4E.BO.Tranche";
import { Tranche as New33 } from "./src/Tranche";
export declare const old33: Old33;
export declare const new33: New33;
import { BO4EBOVertrag as Old34 } from "./src/BO4E.BO.Vertrag";
import { Vertrag as New34 } from "./src/Vertrag";
export declare const old34: Old34;
export declare const new34: New34;
import { BO4EBOWechsel as Old35 } from "./src/BO4E.BO.Wechsel";
import { Wechsel as New35 } from "./src/Wechsel";
export declare const old35: Old35;
export declare const new35: New35;
import { BO4EBOZaehler as Old36 } from "./src/BO4E.BO.Zaehler";
import { Zaehler as New36 } from "./src/Zaehler";
export declare const old36: Old36;
export declare const new36: New36;
import { BO4EBOZaehlzeitdefinition as Old37 } from "./src/BO4E.BO.Zaehlzeitdefinition";
import { Zaehlzeitdefinition as New37 } from "./src/Zaehlzeitdefinition";
export declare const old37: Old37;
export declare const new37: New37;
