/* eslint-disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

export type Avisposition = {
  timestamp?: string | null;
  rechnungsNummer: string | null;
  guid?: string | null;
  rechnungsDatum: string;
  istStorno: boolean;
  istSelbstausgestellt: boolean | null;
  gesamtBrutto: Betrag;
  zuZahlen: Betrag;
  referenz: string | null;
  abweichungen: Abweichung[] | null;
  positionen: Rueckmeldungsposition[] | null;
  [k: string]: unknown;
} & Avisposition1;
export type Betrag = {
  wert: number;
  waehrung:
    | "AFN"
    | "ALL"
    | "AMD"
    | "ANG"
    | "AOA"
    | "ARS"
    | "AUD"
    | "AWG"
    | "AZN"
    | "BAM"
    | "BBD"
    | "BDT"
    | "BGN"
    | "BHD"
    | "BIF"
    | "BMD"
    | "BND"
    | "BOB"
    | "BOV"
    | "BRL"
    | "BSD"
    | "BTN"
    | "BWP"
    | "BYN"
    | "BYR"
    | "BZD"
    | "CAD"
    | "CDF"
    | "CHE"
    | "CHF"
    | "CHW"
    | "CLF"
    | "CLP"
    | "CNY"
    | "COP"
    | "COU"
    | "CRC"
    | "CUC"
    | "CUP"
    | "CVE"
    | "CZK"
    | "DJF"
    | "DKK"
    | "DOP"
    | "DZD"
    | "EGP"
    | "ERN"
    | "ETB"
    | "EUR"
    | "FJD"
    | "FKP"
    | "GBP"
    | "GEL"
    | "GHS"
    | "GIP"
    | "GMD"
    | "GNF"
    | "GTQ"
    | "GYD"
    | "HKD"
    | "HNL"
    | "HRK"
    | "HTG"
    | "HUF"
    | "IDR"
    | "ILS"
    | "INR"
    | "IQD"
    | "IRR"
    | "ISK"
    | "JMD"
    | "JOD"
    | "JPY"
    | "KES"
    | "KGS"
    | "KHR"
    | "KMF"
    | "KPW"
    | "KRW"
    | "KWD"
    | "KYD"
    | "KZT"
    | "LAK"
    | "LBP"
    | "LKR"
    | "LRD"
    | "LSL"
    | "LTL"
    | "LYD"
    | "MAD"
    | "MDL"
    | "MGA"
    | "MKD"
    | "MMK"
    | "MNT"
    | "MOP"
    | "MRO"
    | "MUR"
    | "MVR"
    | "MWK"
    | "MXN"
    | "MXV"
    | "MYR"
    | "MZN"
    | "NAD"
    | "NGN"
    | "NIO"
    | "NOK"
    | "NPR"
    | "NZD"
    | "OMR"
    | "PAB"
    | "PEN"
    | "PGK"
    | "PHP"
    | "PKR"
    | "PLN"
    | "PYG"
    | "QAR"
    | "RON"
    | "RSD"
    | "RUB"
    | "RUR"
    | "RWF"
    | "SAR"
    | "SBD"
    | "SCR"
    | "SDG"
    | "SEK"
    | "SGD"
    | "SHP"
    | "SLL"
    | "SOS"
    | "SRD"
    | "SSP"
    | "STD"
    | "SVC"
    | "SYP"
    | "SZL"
    | "THB"
    | "TJS"
    | "TMT"
    | "TND"
    | "TOP"
    | "TRY"
    | "TTD"
    | "TWD"
    | "TZS"
    | "UAH"
    | "UGX"
    | "USD"
    | "USN"
    | "USS"
    | "UYI"
    | "UYU"
    | "UZS"
    | "VEF"
    | "VND"
    | "VUV"
    | "WST"
    | "XAF"
    | "XAG"
    | "XAU"
    | "XBA"
    | "XBB"
    | "XBC"
    | "XBD"
    | "XCD"
    | "XDR"
    | "XOF"
    | "XPD"
    | "XPF"
    | "XPT"
    | "XSU"
    | "XTS"
    | "XUA"
    | "XXX"
    | "YER"
    | "ZAR"
    | "ZMW"
    | "ZWL";
  timestamp?: string | null;
  guid?: string | null;
  [k: string]: unknown;
} & Betrag1;
export type Betrag1 = {
  wert: number;
  waehrung:
    | "AFN"
    | "ALL"
    | "AMD"
    | "ANG"
    | "AOA"
    | "ARS"
    | "AUD"
    | "AWG"
    | "AZN"
    | "BAM"
    | "BBD"
    | "BDT"
    | "BGN"
    | "BHD"
    | "BIF"
    | "BMD"
    | "BND"
    | "BOB"
    | "BOV"
    | "BRL"
    | "BSD"
    | "BTN"
    | "BWP"
    | "BYN"
    | "BYR"
    | "BZD"
    | "CAD"
    | "CDF"
    | "CHE"
    | "CHF"
    | "CHW"
    | "CLF"
    | "CLP"
    | "CNY"
    | "COP"
    | "COU"
    | "CRC"
    | "CUC"
    | "CUP"
    | "CVE"
    | "CZK"
    | "DJF"
    | "DKK"
    | "DOP"
    | "DZD"
    | "EGP"
    | "ERN"
    | "ETB"
    | "EUR"
    | "FJD"
    | "FKP"
    | "GBP"
    | "GEL"
    | "GHS"
    | "GIP"
    | "GMD"
    | "GNF"
    | "GTQ"
    | "GYD"
    | "HKD"
    | "HNL"
    | "HRK"
    | "HTG"
    | "HUF"
    | "IDR"
    | "ILS"
    | "INR"
    | "IQD"
    | "IRR"
    | "ISK"
    | "JMD"
    | "JOD"
    | "JPY"
    | "KES"
    | "KGS"
    | "KHR"
    | "KMF"
    | "KPW"
    | "KRW"
    | "KWD"
    | "KYD"
    | "KZT"
    | "LAK"
    | "LBP"
    | "LKR"
    | "LRD"
    | "LSL"
    | "LTL"
    | "LYD"
    | "MAD"
    | "MDL"
    | "MGA"
    | "MKD"
    | "MMK"
    | "MNT"
    | "MOP"
    | "MRO"
    | "MUR"
    | "MVR"
    | "MWK"
    | "MXN"
    | "MXV"
    | "MYR"
    | "MZN"
    | "NAD"
    | "NGN"
    | "NIO"
    | "NOK"
    | "NPR"
    | "NZD"
    | "OMR"
    | "PAB"
    | "PEN"
    | "PGK"
    | "PHP"
    | "PKR"
    | "PLN"
    | "PYG"
    | "QAR"
    | "RON"
    | "RSD"
    | "RUB"
    | "RUR"
    | "RWF"
    | "SAR"
    | "SBD"
    | "SCR"
    | "SDG"
    | "SEK"
    | "SGD"
    | "SHP"
    | "SLL"
    | "SOS"
    | "SRD"
    | "SSP"
    | "STD"
    | "SVC"
    | "SYP"
    | "SZL"
    | "THB"
    | "TJS"
    | "TMT"
    | "TND"
    | "TOP"
    | "TRY"
    | "TTD"
    | "TWD"
    | "TZS"
    | "UAH"
    | "UGX"
    | "USD"
    | "USN"
    | "USS"
    | "UYI"
    | "UYU"
    | "UZS"
    | "VEF"
    | "VND"
    | "VUV"
    | "WST"
    | "XAF"
    | "XAG"
    | "XAU"
    | "XBA"
    | "XBB"
    | "XBC"
    | "XBD"
    | "XCD"
    | "XDR"
    | "XOF"
    | "XPD"
    | "XPF"
    | "XPT"
    | "XSU"
    | "XTS"
    | "XUA"
    | "XXX"
    | "YER"
    | "ZAR"
    | "ZMW"
    | "ZWL";
  timestamp?: string | null;
  guid?: string | null;
  [k: string]: unknown;
} | null;
export type Abweichung = {
  timestamp?: string | null;
  guid?: string | null;
  abweichungsgrund:
    | null
    | "PREIS_RECHENREGEL_FALSCH"
    | "FALSCHER_ABRECHNUNGSZEITRAUM"
    | "UNBEKANNTE_MARKTLOKATION_MESSLOKATION"
    | "SONSTIGER_ABWEICHUNGSGRUND"
    | "DOPPELTE_RECHNUNG"
    | "ABRECHNUNGSBEGINN_UNGLEICH_VERTRAGSBEGINN"
    | "ABRECHNUNGSENDE_UNGLEICH_VERTRAGSENDE"
    | "BETRAG_DER_ABSCHLAGSRECHNUNG_FALSCH"
    | "VORAUSBEZAHLTER_BETRAG_FALSCH"
    | "ARTIKEL_NICHT_VEREINBART"
    | "NETZNUTZUNGSMESSWERTE_ENERGIEMENGEN_FEHLEN"
    | "RECHNUNGSNUMMER_BEREITS_ERHALTEN"
    | "NETZNUTZUNGSMESSWERTE_ENERGIEMENGEN_FALSCH"
    | "ZEITLICHE_MENGENANGABE_FEHLERHAFT"
    | "FALSCHER_BILANZIERUNGSBEGINN"
    | "FALSCHES_NETZNUTZUNGSENDE"
    | "BILANZIERTE_MENGE_FEHLT"
    | "BILANZIERTE_MENGE_FALSCH"
    | "NETZNUTZUNGSABRECHNUNG_FEHLT"
    | "REVERSE_CHARGE_ANWENDUNG_FEHLT_ODER_FEHLERHAFT"
    | "ALLOKATIONSLISTE_FEHLT"
    | "MEHR_MINDERMENGE_FALSCH"
    | "UNGUELTIGES_RECHNUNGSDATUM"
    | "ZEITINTERVALL_DER_BILANZIERTEN_MENGE_INKONSISTENT"
    | "RECHNUNGSEMPFAENGER_WIDERSPRICHT_DER_STEUERRECHTLICHEN_EINSCHAETZUNG_DES_RECHNUNGSSTELLERS"
    | "ANGEGEBENE_QUOTES_AN_MARKTLOKATION_NICHT_VORHANDEN"
    | "RECHNUNGSABWICKLUNG_NICHT_VEREINBART"
    | "COMDIS_WIRD_ABGELEHNT"
    | "BEGINN_DES_ABRECHNUNGSZEITRAUMS_VOR_2024"
    | "ERWARTETE_POSITION_NICHT_VORHANDEN"
    | "KEIN_IMS_IM_GESAMTEN_ABRECHNUNGSZEITRAUM"
    | "MSB_IM_ABRECHNUNGSZEITRAUM_NICHT_IMMER_ZUGEORDNET"
    | "MSB_IM_GESAMTEN_ABRECHNUNGSZEITRAUM_NICHT_ZUGEORDNET"
    | "ARTIKELID_DER_POSITION_NICHT_IM_GESAMTEN_POSITIONSZEITRAUM_GUELTIG"
    | "ARTIKELID_FUER_RECHNUNGSTYP_IM_POSITIONSZEITRAUM_NICHT_ZULAESSIG";
  abweichungsgrundBemerkung: string | null;
  zugehoerigeRechnung: string | null;
  abschlagsrechnungen: (string | null)[] | null;
  abweichungsgrundCode: string | null;
  abweichungsgrundCodeliste: string | null;
  [k: string]: unknown;
} & Abweichung1;
export type Abweichung1 = {
  timestamp?: string | null;
  guid?: string | null;
  abweichungsgrund:
    | null
    | "PREIS_RECHENREGEL_FALSCH"
    | "FALSCHER_ABRECHNUNGSZEITRAUM"
    | "UNBEKANNTE_MARKTLOKATION_MESSLOKATION"
    | "SONSTIGER_ABWEICHUNGSGRUND"
    | "DOPPELTE_RECHNUNG"
    | "ABRECHNUNGSBEGINN_UNGLEICH_VERTRAGSBEGINN"
    | "ABRECHNUNGSENDE_UNGLEICH_VERTRAGSENDE"
    | "BETRAG_DER_ABSCHLAGSRECHNUNG_FALSCH"
    | "VORAUSBEZAHLTER_BETRAG_FALSCH"
    | "ARTIKEL_NICHT_VEREINBART"
    | "NETZNUTZUNGSMESSWERTE_ENERGIEMENGEN_FEHLEN"
    | "RECHNUNGSNUMMER_BEREITS_ERHALTEN"
    | "NETZNUTZUNGSMESSWERTE_ENERGIEMENGEN_FALSCH"
    | "ZEITLICHE_MENGENANGABE_FEHLERHAFT"
    | "FALSCHER_BILANZIERUNGSBEGINN"
    | "FALSCHES_NETZNUTZUNGSENDE"
    | "BILANZIERTE_MENGE_FEHLT"
    | "BILANZIERTE_MENGE_FALSCH"
    | "NETZNUTZUNGSABRECHNUNG_FEHLT"
    | "REVERSE_CHARGE_ANWENDUNG_FEHLT_ODER_FEHLERHAFT"
    | "ALLOKATIONSLISTE_FEHLT"
    | "MEHR_MINDERMENGE_FALSCH"
    | "UNGUELTIGES_RECHNUNGSDATUM"
    | "ZEITINTERVALL_DER_BILANZIERTEN_MENGE_INKONSISTENT"
    | "RECHNUNGSEMPFAENGER_WIDERSPRICHT_DER_STEUERRECHTLICHEN_EINSCHAETZUNG_DES_RECHNUNGSSTELLERS"
    | "ANGEGEBENE_QUOTES_AN_MARKTLOKATION_NICHT_VORHANDEN"
    | "RECHNUNGSABWICKLUNG_NICHT_VEREINBART"
    | "COMDIS_WIRD_ABGELEHNT"
    | "BEGINN_DES_ABRECHNUNGSZEITRAUMS_VOR_2024"
    | "ERWARTETE_POSITION_NICHT_VORHANDEN"
    | "KEIN_IMS_IM_GESAMTEN_ABRECHNUNGSZEITRAUM"
    | "MSB_IM_ABRECHNUNGSZEITRAUM_NICHT_IMMER_ZUGEORDNET"
    | "MSB_IM_GESAMTEN_ABRECHNUNGSZEITRAUM_NICHT_ZUGEORDNET"
    | "ARTIKELID_DER_POSITION_NICHT_IM_GESAMTEN_POSITIONSZEITRAUM_GUELTIG"
    | "ARTIKELID_FUER_RECHNUNGSTYP_IM_POSITIONSZEITRAUM_NICHT_ZULAESSIG";
  abweichungsgrundBemerkung: string | null;
  zugehoerigeRechnung: string | null;
  abschlagsrechnungen: (string | null)[] | null;
  abweichungsgrundCode: string | null;
  abweichungsgrundCodeliste: string | null;
  [k: string]: unknown;
} | null;
export type Rueckmeldungsposition = {
  timestamp?: string | null;
  guid?: string | null;
  positionsnummer: string | null;
  abweichungspositionen: Abweichungsposition[] | null;
  [k: string]: unknown;
} & Rueckmeldungsposition1;
export type Abweichungsposition = {
  timestamp?: string | null;
  guid?: string | null;
  abweichungsgrundCodeliste: string | null;
  abweichungsgrundBemerkung: string | null;
  zugehoerigeRechnung: string | null;
  zugehoerigeBestellung: string | null;
  abweichungsgrundCode: string | null;
  [k: string]: unknown;
} & Abweichungsposition1;
export type Abweichungsposition1 = {
  timestamp?: string | null;
  guid?: string | null;
  abweichungsgrundCodeliste: string | null;
  abweichungsgrundBemerkung: string | null;
  zugehoerigeRechnung: string | null;
  zugehoerigeBestellung: string | null;
  abweichungsgrundCode: string | null;
  [k: string]: unknown;
} | null;
export type Rueckmeldungsposition1 = {
  timestamp?: string | null;
  guid?: string | null;
  positionsnummer: string | null;
  abweichungspositionen: Abweichungsposition[] | null;
  [k: string]: unknown;
} | null;
export type Avisposition1 = {
  timestamp?: string | null;
  rechnungsNummer: string | null;
  guid?: string | null;
  rechnungsDatum: string;
  istStorno: boolean;
  istSelbstausgestellt: boolean | null;
  gesamtBrutto: Betrag;
  zuZahlen: Betrag;
  referenz: string | null;
  abweichungen: Abweichung[] | null;
  positionen: Rueckmeldungsposition[] | null;
  [k: string]: unknown;
} | null;
export type ExterneReferenz = {
  exRefName: string | null;
  exRefWert: string | null;
  timestamp?: string | null;
  guid?: string | null;
  [k: string]: unknown;
} & ExterneReferenz1;
export type ExterneReferenz1 = {
  exRefName: string | null;
  exRefWert: string | null;
  timestamp?: string | null;
  guid?: string | null;
  [k: string]: unknown;
} | null;
export type Zeitraum = {
  einheit:
    | null
    | "SEKUNDE"
    | "MINUTE"
    | "STUNDE"
    | "VIERTEL_STUNDE"
    | "TAG"
    | "WOCHE"
    | "MONAT"
    | "QUARTAL"
    | "HALBJAHR"
    | "JAHR";
  dauer: number | null;
  startdatum: string | null;
  enddatum: string | null;
  startzeitpunkt: string | null;
  endzeitpunkt: string | null;
  timestamp?: string | null;
  guid?: string | null;
  [k: string]: unknown;
} & Zeitraum1;
export type Zeitraum1 = {
  einheit:
    | null
    | "SEKUNDE"
    | "MINUTE"
    | "STUNDE"
    | "VIERTEL_STUNDE"
    | "TAG"
    | "WOCHE"
    | "MONAT"
    | "QUARTAL"
    | "HALBJAHR"
    | "JAHR";
  dauer: number | null;
  startdatum: string | null;
  enddatum: string | null;
  startzeitpunkt: string | null;
  endzeitpunkt: string | null;
  timestamp?: string | null;
  guid?: string | null;
  [k: string]: unknown;
} | null;

export interface Avis {
  avisNummer: string | null;
  avisTyp: null | "ABGELEHNTE_FORDERUNG" | "ZAHLUNGSAVIS";
  positionen: Avisposition[] | null;
  zuZahlen: Betrag;
  boTyp: string | null;
  versionStruktur: string | null;
  timestamp?: string | null;
  externeReferenzen: ExterneReferenz[] | null;
  guid?: string | null;
  gueltigkeitszeitraum?: Zeitraum;
  qualitaet?:
    null | "VOLLSTAENDIG" | "INFORMATIV" | "IM_SYSTEM_VORHANDEN" | "ERWARTET" | "VORLAEUFIG" | "UNVOLLSTAENDIG";
  [k: string]: unknown;
}
