/* eslint-disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

export type ExterneReferenz = {
  exRefName: string | null;
  exRefWert: string | null;
  timestamp?: string | null;
  guid?: string | null;
  [k: string]: unknown;
} & ExterneReferenz1;
export type ExterneReferenz1 = {
  exRefName: string | null;
  exRefWert: string | null;
  timestamp?: string | null;
  guid?: string | null;
  [k: string]: unknown;
} | null;
export type Verwendungszweck = {
  marktrolle:
    | "NB"
    | "LF"
    | "MSB"
    | "MDL"
    | "DL"
    | "BKV"
    | "BIKO"
    | "UENB"
    | "KUNDE_SELBST_NN"
    | "MGV"
    | "EIV"
    | "RB"
    | "KUNDE"
    | "INTERESSENT"
    | "GMSB"
    | "AMSB";
  zweck:
    | (
        | "NETZNUTZUNGSABRECHNUNG"
        | "BILANZKREISABRECHNUNG"
        | "MEHRMINDERMENGENABRECHNUNG"
        | "ENDKUNDENABRECHNUNG"
        | "BLINDARBEITABRECHNUNG_BETRIEBSFUEHRUNG"
        | "UEBERMITTLUNG_AN_DAS_HKNR"
        | "ERMITTLUNG_AUSGEGLICHENHEIT_BILANZKREIS"
        | "SELBSTVERBRAUCH"
        | "ES_LIEGT_KEIN_VERWENDUNGSZWECK_VOR"
        | "KEINE_DATENLIEFERUNG_AN_MARKTROLLE"
      )[]
    | null;
  timestamp?: string | null;
  guid?: string | null;
  [k: string]: unknown;
} & Verwendungszweck1;
export type Verwendungszweck1 = {
  marktrolle:
    | "NB"
    | "LF"
    | "MSB"
    | "MDL"
    | "DL"
    | "BKV"
    | "BIKO"
    | "UENB"
    | "KUNDE_SELBST_NN"
    | "MGV"
    | "EIV"
    | "RB"
    | "KUNDE"
    | "INTERESSENT"
    | "GMSB"
    | "AMSB";
  zweck:
    | (
        | "NETZNUTZUNGSABRECHNUNG"
        | "BILANZKREISABRECHNUNG"
        | "MEHRMINDERMENGENABRECHNUNG"
        | "ENDKUNDENABRECHNUNG"
        | "BLINDARBEITABRECHNUNG_BETRIEBSFUEHRUNG"
        | "UEBERMITTLUNG_AN_DAS_HKNR"
        | "ERMITTLUNG_AUSGEGLICHENHEIT_BILANZKREIS"
        | "SELBSTVERBRAUCH"
        | "ES_LIEGT_KEIN_VERWENDUNGSZWECK_VOR"
        | "KEINE_DATENLIEFERUNG_AN_MARKTROLLE"
      )[]
    | null;
  timestamp?: string | null;
  guid?: string | null;
  [k: string]: unknown;
} | null;
export type Rechenschritt = {
  rechenschrittBestandteilId: number;
  referenzRechenschrittID: number;
  timestamp?: string | null;
  guid?: string | null;
  operation: "ADDITION" | "SUBTRAKTION" | "MULTIPLIKATION" | "DIVISION" | "DIVIDEND" | "POSITIVWERT";
  verlustfaktorTrafo: number | null;
  verlustfaktorLeitung: number | null;
  messlokationId: string | null;
  energieflussrichtung: null | "VERBRAUCH" | "ERZEUGUNG";
  weitererRechenschritt: Rechenschritt;
  aufteilungsfaktorEnergiemenge: number | null;
  [k: string]: unknown;
} & Rechenschritt1;
export type Rechenschritt1 = {
  rechenschrittBestandteilId: number;
  referenzRechenschrittID: number;
  timestamp?: string | null;
  guid?: string | null;
  operation: "ADDITION" | "SUBTRAKTION" | "MULTIPLIKATION" | "DIVISION" | "DIVIDEND" | "POSITIVWERT";
  verlustfaktorTrafo: number | null;
  verlustfaktorLeitung: number | null;
  messlokationId: string | null;
  energieflussrichtung: null | "VERBRAUCH" | "ERZEUGUNG";
  weitererRechenschritt: Rechenschritt;
  aufteilungsfaktorEnergiemenge: number | null;
  [k: string]: unknown;
} | null;
export type Zeitraum = {
  einheit:
    | null
    | "SEKUNDE"
    | "MINUTE"
    | "STUNDE"
    | "VIERTEL_STUNDE"
    | "TAG"
    | "WOCHE"
    | "MONAT"
    | "QUARTAL"
    | "HALBJAHR"
    | "JAHR";
  dauer: number | null;
  startdatum: string | null;
  enddatum: string | null;
  startzeitpunkt: string | null;
  endzeitpunkt: string | null;
  timestamp?: string | null;
  guid?: string | null;
  [k: string]: unknown;
} & Zeitraum1;
export type Zeitraum1 = {
  einheit:
    | null
    | "SEKUNDE"
    | "MINUTE"
    | "STUNDE"
    | "VIERTEL_STUNDE"
    | "TAG"
    | "WOCHE"
    | "MONAT"
    | "QUARTAL"
    | "HALBJAHR"
    | "JAHR";
  dauer: number | null;
  startdatum: string | null;
  enddatum: string | null;
  startzeitpunkt: string | null;
  endzeitpunkt: string | null;
  timestamp?: string | null;
  guid?: string | null;
  [k: string]: unknown;
} | null;

export interface Berechnungsformel {
  boTyp: string | null;
  versionStruktur: string | null;
  timestamp?: string | null;
  externeReferenzen: ExterneReferenz[] | null;
  beginndatum: string;
  guid?: string | null;
  notwendigkeit:
    | "BERECHNUNGSFORMEL_NOTWENDIG"
    | "BERECHNUNGSFORMEL_MUSS_ANGEFRAGT_WERDEN"
    | "BERECHNUNGSFORMEL_TRIVIAL"
    | "BERECHNUNGSFORMEL_NICHT_NOTWENDIG";
  rechenschrittId: number | null;
  verwendungszweck: Verwendungszweck;
  rechenschritt: Rechenschritt;
  rechenschritte: Rechenschritt[] | null;
  gueltigkeitszeitraum?: Zeitraum;
  qualitaet?:
    null | "VOLLSTAENDIG" | "INFORMATIV" | "IM_SYSTEM_VORHANDEN" | "ERWARTET" | "VORLAEUFIG" | "UNVOLLSTAENDIG";
  [k: string]: unknown;
}
