/* eslint-disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

export type ExterneReferenz = {
  exRefName: string | null;
  exRefWert: string | null;
  timestamp?: string | null;
  guid?: string | null;
  [k: string]: unknown;
} & ExterneReferenz1;
export type ExterneReferenz1 = {
  exRefName: string | null;
  exRefWert: string | null;
  timestamp?: string | null;
  guid?: string | null;
  [k: string]: unknown;
} | null;
export type Lastprofil = {
  bezeichnung: string | null;
  profilschar: string | null;
  verfahren: null | "SYNTHETISCH" | "ANALYTISCH";
  einspeisung: boolean | null;
  tagesparameter: Tagesparameter;
  profilart:
    | null
    | "ART_STANDARDLASTPROFIL"
    | "ART_TAGESPARAMETERABHAENGIGES_LASTPROFIL"
    | "ART_LASTPROFIL"
    | "ART_STANDARDEINSPEISEPROFIL"
    | "ART_TAGESPARAMETERABHAENGIGES_EINSPEISEPROFIL";
  herausgeber: string | null;
  profiltyp:
    | null
    | "GEWERBE"
    | "GEWERBE_WERKTAG_9_BIS_18"
    | "GEWERBE_ABEND"
    | "GEWERBE_DURCHLAUFEND"
    | "GEWERBE_LADEN_FRISEUR"
    | "GEWERBE_BAECKEREI"
    | "GEWERBE_WOCHENENDE"
    | "LANDWIRTSCHAFT"
    | "LANDWIRTSCHAFT_MIT_MILCH"
    | "LANDWIRTSCHAFT_OHNE_MILCH"
    | "HAUSHALT"
    | "BANDLAST"
    | "UNTERBRECHBARE_VERBRAUCHSEINRICHTUNG"
    | "HEIZWAERMESPEICHER"
    | "STRASSENBELEUCHTUNG"
    | "PHOTOVOLTAIK"
    | "BLOCKHEIZKRAFTWERK"
    | "SONSTIGE_VERBRAUCHENDE_MARKTLOKATION"
    | "SONSTIGE_ERZEUGENDE_MARKTLOKATION"
    | "EMOB_OEFFENTLICH"
    | "EMOB_HAUSHALT"
    | "EMOB_GEWERBE";
  normierungsfaktor:
    null | "NORMIERUNGSFAKTOR_1_000_000_KWH_A" | "NORMIERUNGSFAKTOR_300_KWH_K" | "NORMIERUNGSFAKTOR_1_000_000_KW";
  timestamp?: string | null;
  guid?: string | null;
  [k: string]: unknown;
} & Lastprofil1;
export type Tagesparameter = {
  klimazone: string | null;
  temperaturmessstelle: string | null;
  dienstanbieter: string | null;
  herausgeber: string | null;
  timestamp?: string | null;
  guid?: string | null;
  [k: string]: unknown;
} & Tagesparameter1;
export type Tagesparameter1 = {
  klimazone: string | null;
  temperaturmessstelle: string | null;
  dienstanbieter: string | null;
  herausgeber: string | null;
  timestamp?: string | null;
  guid?: string | null;
  [k: string]: unknown;
} | null;
export type Lastprofil1 = {
  bezeichnung: string | null;
  profilschar: string | null;
  verfahren: null | "SYNTHETISCH" | "ANALYTISCH";
  einspeisung: boolean | null;
  tagesparameter: Tagesparameter;
  profilart:
    | null
    | "ART_STANDARDLASTPROFIL"
    | "ART_TAGESPARAMETERABHAENGIGES_LASTPROFIL"
    | "ART_LASTPROFIL"
    | "ART_STANDARDEINSPEISEPROFIL"
    | "ART_TAGESPARAMETERABHAENGIGES_EINSPEISEPROFIL";
  herausgeber: string | null;
  profiltyp:
    | null
    | "GEWERBE"
    | "GEWERBE_WERKTAG_9_BIS_18"
    | "GEWERBE_ABEND"
    | "GEWERBE_DURCHLAUFEND"
    | "GEWERBE_LADEN_FRISEUR"
    | "GEWERBE_BAECKEREI"
    | "GEWERBE_WOCHENENDE"
    | "LANDWIRTSCHAFT"
    | "LANDWIRTSCHAFT_MIT_MILCH"
    | "LANDWIRTSCHAFT_OHNE_MILCH"
    | "HAUSHALT"
    | "BANDLAST"
    | "UNTERBRECHBARE_VERBRAUCHSEINRICHTUNG"
    | "HEIZWAERMESPEICHER"
    | "STRASSENBELEUCHTUNG"
    | "PHOTOVOLTAIK"
    | "BLOCKHEIZKRAFTWERK"
    | "SONSTIGE_VERBRAUCHENDE_MARKTLOKATION"
    | "SONSTIGE_ERZEUGENDE_MARKTLOKATION"
    | "EMOB_OEFFENTLICH"
    | "EMOB_HAUSHALT"
    | "EMOB_GEWERBE";
  normierungsfaktor:
    null | "NORMIERUNGSFAKTOR_1_000_000_KWH_A" | "NORMIERUNGSFAKTOR_300_KWH_K" | "NORMIERUNGSFAKTOR_1_000_000_KW";
  timestamp?: string | null;
  guid?: string | null;
  [k: string]: unknown;
} | null;
export type Menge = {
  timestamp?: string | null;
  guid?: string | null;
  wert: number;
  einheit:
    | null
    | "ZERO"
    | "WH"
    | "KW"
    | "ANZAHL"
    | "KUBIKMETER"
    | "STUNDE"
    | "TAG"
    | "MONAT"
    | "VAR"
    | "VARH"
    | "KWHK"
    | "W_M2"
    | "M_S"
    | "STUECK"
    | "JAHR"
    | "KWH"
    | "MW"
    | "KVAR"
    | "KVARH"
    | "MWH";
  [k: string]: unknown;
} & Menge1;
export type Menge1 = {
  timestamp?: string | null;
  guid?: string | null;
  wert: number;
  einheit:
    | null
    | "ZERO"
    | "WH"
    | "KW"
    | "ANZAHL"
    | "KUBIKMETER"
    | "STUNDE"
    | "TAG"
    | "MONAT"
    | "VAR"
    | "VARH"
    | "KWHK"
    | "W_M2"
    | "M_S"
    | "STUECK"
    | "JAHR"
    | "KWH"
    | "MW"
    | "KVAR"
    | "KVARH"
    | "MWH";
  [k: string]: unknown;
} | null;
export type Zeitraum = {
  einheit:
    | null
    | "SEKUNDE"
    | "MINUTE"
    | "STUNDE"
    | "VIERTEL_STUNDE"
    | "TAG"
    | "WOCHE"
    | "MONAT"
    | "QUARTAL"
    | "HALBJAHR"
    | "JAHR";
  dauer: number | null;
  startdatum: string | null;
  enddatum: string | null;
  startzeitpunkt: string | null;
  endzeitpunkt: string | null;
  timestamp?: string | null;
  guid?: string | null;
  [k: string]: unknown;
} & Zeitraum1;
export type Zeitraum1 = {
  einheit:
    | null
    | "SEKUNDE"
    | "MINUTE"
    | "STUNDE"
    | "VIERTEL_STUNDE"
    | "TAG"
    | "WOCHE"
    | "MONAT"
    | "QUARTAL"
    | "HALBJAHR"
    | "JAHR";
  dauer: number | null;
  startdatum: string | null;
  enddatum: string | null;
  startzeitpunkt: string | null;
  endzeitpunkt: string | null;
  timestamp?: string | null;
  guid?: string | null;
  [k: string]: unknown;
} | null;

export interface Bilanzierung {
  boTyp: string | null;
  versionStruktur: string | null;
  timestamp?: string | null;
  externeReferenzen: ExterneReferenz[] | null;
  guid?: string | null;
  marktlokationsId: string | null;
  lastprofile: Lastprofil[] | null;
  bilanzierungsbeginn: string | null;
  bilanzierungsende: string | null;
  bilanzkreis: string | null;
  jahresverbrauchsprognose: Menge;
  temperaturarbeit: Menge;
  kundenwert: Menge;
  verbrauchsaufteilung: number | null;
  zeitreihentyp:
    | null
    | "EGS"
    | "LGS"
    | "NZR"
    | "SES"
    | "SLS"
    | "TES"
    | "TLS"
    | "SLS_TLS"
    | "SES_TES"
    | "AUS"
    | "BAS"
    | "DBA"
    | "DZR"
    | "DZÜ"
    | "FPE"
    | "FPI"
    | "SRE"
    | "SRI"
    | "VZR";
  aggregationsverantwortung: null | "UENB" | "VNB";
  prognosegrundlage: null | "WERTE" | "PROFILE";
  detailsPrognosegrundlage: ("SLP_SEP" | "TLP_TEP")[] | null;
  wahlrechtPrognosegrundlage:
    | null
    | "DURCH_LF"
    | "DURCH_LF_NICHT_GEGEBEN"
    | "NICHT_WEGEN_GROSSEN_VERBRAUCHS"
    | "NICHT_WEGEN_EIGENVERBRAUCH"
    | "NICHT_WEGEN_TAGES_VERBRAUCH"
    | "NICHT_WEGEN_ENWG";
  fallgruppenzuordnung: null | "GABI_RLMmT" | "GABI_RLMoT" | "GABI_RLMNEV";
  prioritaet: number | null;
  grundWahlrechtPrognosegrundlage:
    | null
    | "DURCH_LF"
    | "DURCH_LF_NICHT_GEGEBEN"
    | "NICHT_WEGEN_GROSSEN_VERBRAUCHS"
    | "NICHT_WEGEN_EIGENVERBRAUCH"
    | "NICHT_WEGEN_TAGES_VERBRAUCH"
    | "NICHT_WEGEN_ENWG";
  abwicklungsmodell: null | "MODELL_1" | "MODELL_2";
  positionsnummer: string | null;
  gueltigkeitszeitraum?: Zeitraum;
  qualitaet?:
    null | "VOLLSTAENDIG" | "INFORMATIV" | "IM_SYSTEM_VORHANDEN" | "ERWARTET" | "VORLAEUFIG" | "UNVOLLSTAENDIG";
  [k: string]: unknown;
}
