/* tslint:disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

export type Adresse = {
  postleitzahl: string;
  ort: string;
  strasse?: string | null;
  hausnummer?: string | null;
  postfach?: string | null;
  adresszusatz?: string | null;
  coErgaenzung?: string | null;
  landescode?:
    | null
    | "AC"
    | "AD"
    | "AE"
    | "AF"
    | "AG"
    | "AI"
    | "AL"
    | "AM"
    | "AN"
    | "AO"
    | "AQ"
    | "AR"
    | "AS"
    | "AT"
    | "AU"
    | "AW"
    | "AX"
    | "AZ"
    | "BA"
    | "BB"
    | "BD"
    | "BE"
    | "BF"
    | "BG"
    | "BH"
    | "BI"
    | "BJ"
    | "BL"
    | "BM"
    | "BN"
    | "BO"
    | "BQ"
    | "BR"
    | "BS"
    | "BT"
    | "BU"
    | "BV"
    | "BW"
    | "BY"
    | "BZ"
    | "CA"
    | "CC"
    | "CD"
    | "CF"
    | "CG"
    | "CH"
    | "CI"
    | "CK"
    | "CL"
    | "CM"
    | "CN"
    | "CO"
    | "CP"
    | "CR"
    | "CS"
    | "CU"
    | "CV"
    | "CW"
    | "CX"
    | "CY"
    | "CZ"
    | "DE"
    | "DG"
    | "DJ"
    | "DK"
    | "DM"
    | "DO"
    | "DZ"
    | "EA"
    | "EC"
    | "EE"
    | "EG"
    | "EH"
    | "ER"
    | "ES"
    | "ET"
    | "EU"
    | "FI"
    | "FJ"
    | "FK"
    | "FM"
    | "FO"
    | "FR"
    | "FX"
    | "GA"
    | "GB"
    | "GD"
    | "GE"
    | "GF"
    | "GG"
    | "GH"
    | "GI"
    | "GL"
    | "GM"
    | "GN"
    | "GP"
    | "GQ"
    | "GR"
    | "GS"
    | "GT"
    | "GU"
    | "GW"
    | "GY"
    | "HK"
    | "HM"
    | "HN"
    | "HR"
    | "HT"
    | "HU"
    | "IC"
    | "ID"
    | "IE"
    | "IL"
    | "IM"
    | "IN"
    | "IO"
    | "IQ"
    | "IR"
    | "IS"
    | "IT"
    | "JE"
    | "JM"
    | "JO"
    | "JP"
    | "KE"
    | "KG"
    | "KH"
    | "KI"
    | "KM"
    | "KN"
    | "KP"
    | "KR"
    | "KW"
    | "KY"
    | "KZ"
    | "LA"
    | "LB"
    | "LC"
    | "LI"
    | "LK"
    | "LR"
    | "LS"
    | "LT"
    | "LU"
    | "LV"
    | "LY"
    | "MA"
    | "MC"
    | "MD"
    | "ME"
    | "MF"
    | "MG"
    | "MH"
    | "MK"
    | "ML"
    | "MM"
    | "MN"
    | "MO"
    | "MP"
    | "MQ"
    | "MR"
    | "MS"
    | "MT"
    | "MU"
    | "MV"
    | "MW"
    | "MX"
    | "MY"
    | "MZ"
    | "NA"
    | "NC"
    | "NE"
    | "NF"
    | "NG"
    | "NI"
    | "NL"
    | "NO"
    | "NP"
    | "NR"
    | "NT"
    | "NU"
    | "NZ"
    | "OM"
    | "PA"
    | "PE"
    | "PF"
    | "PG"
    | "PH"
    | "PK"
    | "PL"
    | "PM"
    | "PN"
    | "PR"
    | "PS"
    | "PT"
    | "PW"
    | "PY"
    | "QA"
    | "RE"
    | "RO"
    | "RS"
    | "RU"
    | "RW"
    | "SA"
    | "SB"
    | "SC"
    | "SD"
    | "SE"
    | "SF"
    | "SG"
    | "SH"
    | "SI"
    | "SJ"
    | "SK"
    | "SL"
    | "SM"
    | "SN"
    | "SO"
    | "SR"
    | "SS"
    | "ST"
    | "SU"
    | "SV"
    | "SX"
    | "SY"
    | "SZ"
    | "TA"
    | "TC"
    | "TD"
    | "TF"
    | "TG"
    | "TJ"
    | "TK"
    | "TL"
    | "TM"
    | "TN"
    | "TO"
    | "TP"
    | "TR"
    | "TT"
    | "TV"
    | "TW"
    | "TZ"
    | "UA"
    | "UG"
    | "UK"
    | "UM"
    | "US"
    | "UY"
    | "UZ"
    | "VA"
    | "VC"
    | "VE"
    | "VG"
    | "VI"
    | "VN"
    | "VU"
    | "WF"
    | "WS"
    | "XK"
    | "YE"
    | "YT"
    | "YU"
    | "ZA"
    | "ZM"
    | "ZR"
    | "ZW";
  guid?: string | null;
  [k: string]: unknown;
} & Adresse1;
export type Adresse1 = {
  postleitzahl: string;
  ort: string;
  strasse?: string | null;
  hausnummer?: string | null;
  postfach?: string | null;
  adresszusatz?: string | null;
  coErgaenzung?: string | null;
  landescode?:
    | null
    | "AC"
    | "AD"
    | "AE"
    | "AF"
    | "AG"
    | "AI"
    | "AL"
    | "AM"
    | "AN"
    | "AO"
    | "AQ"
    | "AR"
    | "AS"
    | "AT"
    | "AU"
    | "AW"
    | "AX"
    | "AZ"
    | "BA"
    | "BB"
    | "BD"
    | "BE"
    | "BF"
    | "BG"
    | "BH"
    | "BI"
    | "BJ"
    | "BL"
    | "BM"
    | "BN"
    | "BO"
    | "BQ"
    | "BR"
    | "BS"
    | "BT"
    | "BU"
    | "BV"
    | "BW"
    | "BY"
    | "BZ"
    | "CA"
    | "CC"
    | "CD"
    | "CF"
    | "CG"
    | "CH"
    | "CI"
    | "CK"
    | "CL"
    | "CM"
    | "CN"
    | "CO"
    | "CP"
    | "CR"
    | "CS"
    | "CU"
    | "CV"
    | "CW"
    | "CX"
    | "CY"
    | "CZ"
    | "DE"
    | "DG"
    | "DJ"
    | "DK"
    | "DM"
    | "DO"
    | "DZ"
    | "EA"
    | "EC"
    | "EE"
    | "EG"
    | "EH"
    | "ER"
    | "ES"
    | "ET"
    | "EU"
    | "FI"
    | "FJ"
    | "FK"
    | "FM"
    | "FO"
    | "FR"
    | "FX"
    | "GA"
    | "GB"
    | "GD"
    | "GE"
    | "GF"
    | "GG"
    | "GH"
    | "GI"
    | "GL"
    | "GM"
    | "GN"
    | "GP"
    | "GQ"
    | "GR"
    | "GS"
    | "GT"
    | "GU"
    | "GW"
    | "GY"
    | "HK"
    | "HM"
    | "HN"
    | "HR"
    | "HT"
    | "HU"
    | "IC"
    | "ID"
    | "IE"
    | "IL"
    | "IM"
    | "IN"
    | "IO"
    | "IQ"
    | "IR"
    | "IS"
    | "IT"
    | "JE"
    | "JM"
    | "JO"
    | "JP"
    | "KE"
    | "KG"
    | "KH"
    | "KI"
    | "KM"
    | "KN"
    | "KP"
    | "KR"
    | "KW"
    | "KY"
    | "KZ"
    | "LA"
    | "LB"
    | "LC"
    | "LI"
    | "LK"
    | "LR"
    | "LS"
    | "LT"
    | "LU"
    | "LV"
    | "LY"
    | "MA"
    | "MC"
    | "MD"
    | "ME"
    | "MF"
    | "MG"
    | "MH"
    | "MK"
    | "ML"
    | "MM"
    | "MN"
    | "MO"
    | "MP"
    | "MQ"
    | "MR"
    | "MS"
    | "MT"
    | "MU"
    | "MV"
    | "MW"
    | "MX"
    | "MY"
    | "MZ"
    | "NA"
    | "NC"
    | "NE"
    | "NF"
    | "NG"
    | "NI"
    | "NL"
    | "NO"
    | "NP"
    | "NR"
    | "NT"
    | "NU"
    | "NZ"
    | "OM"
    | "PA"
    | "PE"
    | "PF"
    | "PG"
    | "PH"
    | "PK"
    | "PL"
    | "PM"
    | "PN"
    | "PR"
    | "PS"
    | "PT"
    | "PW"
    | "PY"
    | "QA"
    | "RE"
    | "RO"
    | "RS"
    | "RU"
    | "RW"
    | "SA"
    | "SB"
    | "SC"
    | "SD"
    | "SE"
    | "SF"
    | "SG"
    | "SH"
    | "SI"
    | "SJ"
    | "SK"
    | "SL"
    | "SM"
    | "SN"
    | "SO"
    | "SR"
    | "SS"
    | "ST"
    | "SU"
    | "SV"
    | "SX"
    | "SY"
    | "SZ"
    | "TA"
    | "TC"
    | "TD"
    | "TF"
    | "TG"
    | "TJ"
    | "TK"
    | "TL"
    | "TM"
    | "TN"
    | "TO"
    | "TP"
    | "TR"
    | "TT"
    | "TV"
    | "TW"
    | "TZ"
    | "UA"
    | "UG"
    | "UK"
    | "UM"
    | "US"
    | "UY"
    | "UZ"
    | "VA"
    | "VC"
    | "VE"
    | "VG"
    | "VI"
    | "VN"
    | "VU"
    | "WF"
    | "WS"
    | "XK"
    | "YE"
    | "YT"
    | "YU"
    | "ZA"
    | "ZM"
    | "ZR"
    | "ZW";
  guid?: string | null;
  [k: string]: unknown;
} | null;
export type Ansprechpartner = {
  guid?: string | null;
  boTyp?: string | null;
  versionStruktur?: number;
  anrede?: null | "HERR" | "FRAU" | "EHELEUTE" | "FIRMA" | "INDIVIDUELL" | "DR";
  individuelleAnrede?: string | null;
  titel?: null | "DR" | "PROF" | "PROF_DR";
  vorname?: string | null;
  nachname: string;
  eMailAdresse?: string | null;
  kommentar?: string | null;
  geschaeftspartner: Geschaeftspartner;
  adresse?: Adresse1;
  rufnummer?: Rufnummer[] | null;
  zustaendigkeit?: Zustaendigkeit[] | null;
  [k: string]: unknown;
} & Ansprechpartner1;
export type Rufnummer = {
  nummerntyp:
    | "RUF_ZENTRALE"
    | "FAX_ZENTRALE"
    | "SAMMELRUF"
    | "SAMMELFAX"
    | "ABTEILUNGRUF"
    | "ABTEILUNGFAX"
    | "RUF_DURCHWAHL"
    | "FAX_DURCHWAHL"
    | "MOBIL_NUMMER";
  rufnummer: string;
  guid?: string | null;
  [k: string]: unknown;
} & Rufnummer1;
export type Rufnummer1 = {
  nummerntyp:
    | "RUF_ZENTRALE"
    | "FAX_ZENTRALE"
    | "SAMMELRUF"
    | "SAMMELFAX"
    | "ABTEILUNGRUF"
    | "ABTEILUNGFAX"
    | "RUF_DURCHWAHL"
    | "FAX_DURCHWAHL"
    | "MOBIL_NUMMER";
  rufnummer: string;
  guid?: string | null;
  [k: string]: unknown;
} | null;
export type Zustaendigkeit = {
  jobtitel?: string | null;
  abteilung?: string | null;
  themengebiet?: string | null;
  guid?: string | null;
  [k: string]: unknown;
} & Zustaendigkeit1;
export type Zustaendigkeit1 = {
  jobtitel?: string | null;
  abteilung?: string | null;
  themengebiet?: string | null;
  guid?: string | null;
  [k: string]: unknown;
} | null;
export type Ansprechpartner1 = {
  guid?: string | null;
  boTyp?: string | null;
  versionStruktur?: number;
  anrede?: null | "HERR" | "FRAU" | "EHELEUTE" | "FIRMA" | "INDIVIDUELL" | "DR";
  individuelleAnrede?: string | null;
  titel?: null | "DR" | "PROF" | "PROF_DR";
  vorname?: string | null;
  nachname: string;
  eMailAdresse?: string | null;
  kommentar?: string | null;
  geschaeftspartner: Geschaeftspartner;
  adresse?: Adresse1;
  rufnummer?: Rufnummer[] | null;
  zustaendigkeit?: Zustaendigkeit[] | null;
  [k: string]: unknown;
} | null;
export type Angebotsvariante = {
  angebotsstatus:
    | "KONZEPTION"
    | "UNVERBINDLICH"
    | "VERBINDLICH"
    | "BEAUFTRAGT"
    | "UNGUELTIG"
    | "ABGELEHNT"
    | "NACHGEFASST"
    | "AUSSTEHEND"
    | "ERLEDIGT";
  beschreibung?: string | null;
  erstelldatum?: string;
  bindefrist: string;
  gesamtmenge?: Menge;
  gesamtkosten?: Betrag;
  teile: Angebotsteil[];
  guid?: string | null;
  [k: string]: unknown;
} & Angebotsvariante1;
export type Menge = {
  wert: number;
  einheit:
    | "WH"
    | "KW"
    | "ANZAHL"
    | "KUBIKMETER"
    | "STUNDE"
    | "TAG"
    | "MONAT"
    | "VAR"
    | "VARH"
    | "JAHR"
    | "KWH"
    | "MW"
    | "KVAR"
    | "KVARH"
    | "MWH";
  guid?: string | null;
  [k: string]: unknown;
} & Menge1;
export type Menge1 = {
  wert: number;
  einheit:
    | "WH"
    | "KW"
    | "ANZAHL"
    | "KUBIKMETER"
    | "STUNDE"
    | "TAG"
    | "MONAT"
    | "VAR"
    | "VARH"
    | "JAHR"
    | "KWH"
    | "MW"
    | "KVAR"
    | "KVARH"
    | "MWH";
  guid?: string | null;
  [k: string]: unknown;
} | null;
export type Betrag = {
  wert: number;
  waehrung:
    | "AFN"
    | "ALL"
    | "AMD"
    | "ANG"
    | "AOA"
    | "ARS"
    | "AUD"
    | "AWG"
    | "AZN"
    | "BAM"
    | "BBD"
    | "BDT"
    | "BGN"
    | "BHD"
    | "BIF"
    | "BMD"
    | "BND"
    | "BOB"
    | "BOV"
    | "BRL"
    | "BSD"
    | "BTN"
    | "BWP"
    | "BYN"
    | "BYR"
    | "BZD"
    | "CAD"
    | "CDF"
    | "CHE"
    | "CHF"
    | "CHW"
    | "CLF"
    | "CLP"
    | "CNY"
    | "COP"
    | "COU"
    | "CRC"
    | "CUC"
    | "CUP"
    | "CVE"
    | "CZK"
    | "DJF"
    | "DKK"
    | "DOP"
    | "DZD"
    | "EGP"
    | "ERN"
    | "ETB"
    | "EUR"
    | "FJD"
    | "FKP"
    | "GBP"
    | "GEL"
    | "GHS"
    | "GIP"
    | "GMD"
    | "GNF"
    | "GTQ"
    | "GYD"
    | "HKD"
    | "HNL"
    | "HRK"
    | "HTG"
    | "HUF"
    | "IDR"
    | "ILS"
    | "INR"
    | "IQD"
    | "IRR"
    | "ISK"
    | "JMD"
    | "JOD"
    | "JPY"
    | "KES"
    | "KGS"
    | "KHR"
    | "KMF"
    | "KPW"
    | "KRW"
    | "KWD"
    | "KYD"
    | "KZT"
    | "LAK"
    | "LBP"
    | "LKR"
    | "LRD"
    | "LSL"
    | "LTL"
    | "LYD"
    | "MAD"
    | "MDL"
    | "MGA"
    | "MKD"
    | "MMK"
    | "MNT"
    | "MOP"
    | "MRO"
    | "MUR"
    | "MVR"
    | "MWK"
    | "MXN"
    | "MXV"
    | "MYR"
    | "MZN"
    | "NAD"
    | "NGN"
    | "NIO"
    | "NOK"
    | "NPR"
    | "NZD"
    | "OMR"
    | "PAB"
    | "PEN"
    | "PGK"
    | "PHP"
    | "PKR"
    | "PLN"
    | "PYG"
    | "QAR"
    | "RON"
    | "RSD"
    | "RUB"
    | "RUR"
    | "RWF"
    | "SAR"
    | "SBD"
    | "SCR"
    | "SDG"
    | "SEK"
    | "SGD"
    | "SHP"
    | "SLL"
    | "SOS"
    | "SRD"
    | "SSP"
    | "STD"
    | "SVC"
    | "SYP"
    | "SZL"
    | "THB"
    | "TJS"
    | "TMT"
    | "TND"
    | "TOP"
    | "TRY"
    | "TTD"
    | "TWD"
    | "TZS"
    | "UAH"
    | "UGX"
    | "USD"
    | "USN"
    | "USS"
    | "UYI"
    | "UYU"
    | "UZS"
    | "VEF"
    | "VND"
    | "VUV"
    | "WST"
    | "XAF"
    | "XAG"
    | "XAU"
    | "XBA"
    | "XBB"
    | "XBC"
    | "XBD"
    | "XCD"
    | "XDR"
    | "XOF"
    | "XPD"
    | "XPF"
    | "XPT"
    | "XSU"
    | "XTS"
    | "XUA"
    | "XXX"
    | "YER"
    | "ZAR"
    | "ZMW"
    | "ZWL";
  guid?: string | null;
  [k: string]: unknown;
} & Betrag1;
export type Betrag1 = {
  wert: number;
  waehrung:
    | "AFN"
    | "ALL"
    | "AMD"
    | "ANG"
    | "AOA"
    | "ARS"
    | "AUD"
    | "AWG"
    | "AZN"
    | "BAM"
    | "BBD"
    | "BDT"
    | "BGN"
    | "BHD"
    | "BIF"
    | "BMD"
    | "BND"
    | "BOB"
    | "BOV"
    | "BRL"
    | "BSD"
    | "BTN"
    | "BWP"
    | "BYN"
    | "BYR"
    | "BZD"
    | "CAD"
    | "CDF"
    | "CHE"
    | "CHF"
    | "CHW"
    | "CLF"
    | "CLP"
    | "CNY"
    | "COP"
    | "COU"
    | "CRC"
    | "CUC"
    | "CUP"
    | "CVE"
    | "CZK"
    | "DJF"
    | "DKK"
    | "DOP"
    | "DZD"
    | "EGP"
    | "ERN"
    | "ETB"
    | "EUR"
    | "FJD"
    | "FKP"
    | "GBP"
    | "GEL"
    | "GHS"
    | "GIP"
    | "GMD"
    | "GNF"
    | "GTQ"
    | "GYD"
    | "HKD"
    | "HNL"
    | "HRK"
    | "HTG"
    | "HUF"
    | "IDR"
    | "ILS"
    | "INR"
    | "IQD"
    | "IRR"
    | "ISK"
    | "JMD"
    | "JOD"
    | "JPY"
    | "KES"
    | "KGS"
    | "KHR"
    | "KMF"
    | "KPW"
    | "KRW"
    | "KWD"
    | "KYD"
    | "KZT"
    | "LAK"
    | "LBP"
    | "LKR"
    | "LRD"
    | "LSL"
    | "LTL"
    | "LYD"
    | "MAD"
    | "MDL"
    | "MGA"
    | "MKD"
    | "MMK"
    | "MNT"
    | "MOP"
    | "MRO"
    | "MUR"
    | "MVR"
    | "MWK"
    | "MXN"
    | "MXV"
    | "MYR"
    | "MZN"
    | "NAD"
    | "NGN"
    | "NIO"
    | "NOK"
    | "NPR"
    | "NZD"
    | "OMR"
    | "PAB"
    | "PEN"
    | "PGK"
    | "PHP"
    | "PKR"
    | "PLN"
    | "PYG"
    | "QAR"
    | "RON"
    | "RSD"
    | "RUB"
    | "RUR"
    | "RWF"
    | "SAR"
    | "SBD"
    | "SCR"
    | "SDG"
    | "SEK"
    | "SGD"
    | "SHP"
    | "SLL"
    | "SOS"
    | "SRD"
    | "SSP"
    | "STD"
    | "SVC"
    | "SYP"
    | "SZL"
    | "THB"
    | "TJS"
    | "TMT"
    | "TND"
    | "TOP"
    | "TRY"
    | "TTD"
    | "TWD"
    | "TZS"
    | "UAH"
    | "UGX"
    | "USD"
    | "USN"
    | "USS"
    | "UYI"
    | "UYU"
    | "UZS"
    | "VEF"
    | "VND"
    | "VUV"
    | "WST"
    | "XAF"
    | "XAG"
    | "XAU"
    | "XBA"
    | "XBB"
    | "XBC"
    | "XBD"
    | "XCD"
    | "XDR"
    | "XOF"
    | "XPD"
    | "XPF"
    | "XPT"
    | "XSU"
    | "XTS"
    | "XUA"
    | "XXX"
    | "YER"
    | "ZAR"
    | "ZMW"
    | "ZWL";
  guid?: string | null;
  [k: string]: unknown;
} | null;
export type Angebotsteil = {
  anfrageSubreferenz?: string | null;
  lieferstellenangebotsteil?: Marktlokation[] | null;
  gesamtmengeangebotsteil?: Menge1;
  gesamtkostenangebotsteil?: Betrag1;
  positionen: Angebotsposition[];
  guid?: string | null;
  [k: string]: unknown;
} & Angebotsteil1;
export type Marktlokation = {
  guid?: string | null;
  boTyp?: string | null;
  versionStruktur?: number;
  marktlokationsId: string;
  sparte: "STROM" | "GAS" | "FERNWAERME" | "NAHWAERME" | "WASSER" | "ABWASSER";
  energierichtung: "AUSSP" | "EINSP";
  bilanzierungsmethode: "RLM" | "SLP" | "TLP_GEMEINSAM" | "TLP_GETRENNT" | "PAUSCHAL" | "IMS";
  verbrauchsart?: null | "KL" | "KLW" | "KLWS" | "W" | "WS";
  unterbrechbar?: boolean | null;
  netzebene: "NSP" | "MSP" | "HSP" | "HSS" | "MSP_NSP_UMSP" | "HSP_MSP_UMSP" | "HSS_HSP_UMSP" | "HD" | "MD" | "ND";
  netzbetreiberCodeNr?: string | null;
  gebietTyp?:
    | null
    | "REGELZONE"
    | "MARKTGEBIET"
    | "BILANZIERUNGSGEBIET"
    | "VERTEILNETZ"
    | "TRANSPORTNETZ"
    | "REGIONALNETZ"
    | "AREALNETZ"
    | "GRUNDVERSORGUNGSGEBIET"
    | "VERSORGUNGSGEBIET";
  netzgebietNr?: string | null;
  bilanzierungsgebiet?: string | null;
  grundversorgerCodeNr?: string | null;
  gasqualitaet?: null | "H_GAS" | "H_GAS" | "L_GAS" | "L_GAS";
  endkunde?: Geschaeftspartner1;
  lokationsadresse?: Adresse1;
  geoadresse?: Geokoordinaten;
  katasterinformation?: Katasteradresse;
  marktrollen?: Marktrolle[] | null;
  regelzone?: string | null;
  marktgebiet?: string | null;
  zeitreihentyp?: null | "EGS" | "LGS" | "NZR" | "SES" | "SLS" | "TES" | "TLS";
  zaehlwerke?: Zaehlwerk[] | null;
  verbauchsmenge?: Verbrauch[] | null;
  messlokationen?: Messlokation[] | null;
  zugehoerigeMesslokationen?: Messlokationszuordnung[] | null;
  [k: string]: unknown;
} & Marktlokation1;
export type Geschaeftspartner1 = {
  guid?: string | null;
  boTyp?: string | null;
  versionStruktur?: number;
  anrede?: null | "HERR" | "FRAU" | "EHELEUTE" | "FIRMA" | "INDIVIDUELL" | "DR";
  title?: string | null;
  name1?: string | null;
  name2?: string | null;
  name3?: string | null;
  gewerbekennzeichnung: boolean;
  hrnummer?: string | null;
  amtsgericht?: string | null;
  kontaktweg?: ("ANSCHREIBEN" | "TELEFONAT" | "FAX" | "E_MAIL" | "SMS")[] | null;
  umsatzsteuerId?: string | null;
  glaeubigerId?: string | null;
  eMailAdresse?: string | null;
  website?: string | null;
  geschaeftspartnerrolle?: ("LIEFERANT" | "DIENSTLEISTER" | "KUNDE" | "INTERESSENT" | "MARKTPARTNER")[] | null;
  partneradresse?: Adresse1;
  [k: string]: unknown;
} & Geschaeftspartner11;
export type Geschaeftspartner11 = {
  guid?: string | null;
  boTyp?: string | null;
  versionStruktur?: number;
  anrede?: null | "HERR" | "FRAU" | "EHELEUTE" | "FIRMA" | "INDIVIDUELL" | "DR";
  title?: string | null;
  name1?: string | null;
  name2?: string | null;
  name3?: string | null;
  gewerbekennzeichnung: boolean;
  hrnummer?: string | null;
  amtsgericht?: string | null;
  kontaktweg?: ("ANSCHREIBEN" | "TELEFONAT" | "FAX" | "E_MAIL" | "SMS")[] | null;
  umsatzsteuerId?: string | null;
  glaeubigerId?: string | null;
  eMailAdresse?: string | null;
  website?: string | null;
  geschaeftspartnerrolle?: ("LIEFERANT" | "DIENSTLEISTER" | "KUNDE" | "INTERESSENT" | "MARKTPARTNER")[] | null;
  partneradresse?: Adresse1;
  [k: string]: unknown;
} | null;
export type Geokoordinaten = {
  breitengrad: number;
  laengengrad: number;
  guid?: string | null;
  [k: string]: unknown;
} & Geokoordinaten1;
export type Geokoordinaten1 = {
  breitengrad: number;
  laengengrad: number;
  guid?: string | null;
  [k: string]: unknown;
} | null;
export type Katasteradresse = {
  gemarkung_flur: string;
  flurstueck: string;
  guid?: string | null;
  [k: string]: unknown;
} & Katasteradresse1;
export type Katasteradresse1 = {
  gemarkung_flur: string;
  flurstueck: string;
  guid?: string | null;
  [k: string]: unknown;
} | null;
export type Marktrolle = {
  rollencodenummer?: string | null;
  code?: string | null;
  marktrolle:
    | "NB"
    | "LF"
    | "MSB"
    | "MDL"
    | "DL"
    | "BKV"
    | "BIKO"
    | "UENB"
    | "KUNDE_SELBST_NN"
    | "MGV"
    | "EIV"
    | "RB"
    | "KUNDE"
    | "INTERESSENT";
  guid?: string | null;
  [k: string]: unknown;
} & Marktrolle1;
export type Marktrolle1 = {
  rollencodenummer?: string | null;
  code?: string | null;
  marktrolle:
    | "NB"
    | "LF"
    | "MSB"
    | "MDL"
    | "DL"
    | "BKV"
    | "BIKO"
    | "UENB"
    | "KUNDE_SELBST_NN"
    | "MGV"
    | "EIV"
    | "RB"
    | "KUNDE"
    | "INTERESSENT";
  guid?: string | null;
  [k: string]: unknown;
} | null;
export type Zaehlwerk = {
  zaehlwerkId: string;
  bezeichnung: string;
  richtung: "AUSSP" | "EINSP";
  obisKennzahl: string;
  wandlerfaktor: number;
  einheit:
    | "WH"
    | "KW"
    | "ANZAHL"
    | "KUBIKMETER"
    | "STUNDE"
    | "TAG"
    | "MONAT"
    | "VAR"
    | "VARH"
    | "JAHR"
    | "KWH"
    | "MW"
    | "KVAR"
    | "KVARH"
    | "MWH";
  kennzahl?: string | null;
  schwachlastfaehig?: null | "NICHT_SCHWACHLASTFAEHIG" | "SCHWACHLASTFAEHIG";
  verwendungszwecke?:
    | ("NETZNUTZUNGSABRECHNUNG" | "BILANZKREISABRECHNUNG" | "MEHRMINDERMBENGENABRECHNUNG" | "ENDKUNDENABRECHNUNG")[]
    | null;
  verbrauchsart?: null | "KL" | "KLW" | "KLWS" | "W" | "WS";
  unterbrechbarkeit?: null | "UV" | "NUV";
  waermenutzung?: null | "SPEICHERHEIZUNG" | "WAERMEPUMPE" | "DIREKTHEIZUNG";
  konzessionsabgabe?: Konzessionsabgabe;
  steuerbefreit?: boolean | null;
  vorkommastelle?: number | null;
  nachkommastelle?: number | null;
  guid?: string | null;
  [k: string]: unknown;
} & Zaehlwerk1;
export type Konzessionsabgabe = {
  guid?: string | null;
  kosten: number;
  kategorie: string;
  satz: "KAS" | "SA" | "SAS" | "TA" | "TAS" | "TK" | "TKS" | "TS" | "TSS";
  [k: string]: unknown;
} & Konzessionsabgabe1;
export type Konzessionsabgabe1 = {
  guid?: string | null;
  kosten: number;
  kategorie: string;
  satz: "KAS" | "SA" | "SAS" | "TA" | "TAS" | "TK" | "TKS" | "TS" | "TSS";
  [k: string]: unknown;
} | null;
export type Zaehlwerk1 = {
  zaehlwerkId: string;
  bezeichnung: string;
  richtung: "AUSSP" | "EINSP";
  obisKennzahl: string;
  wandlerfaktor: number;
  einheit:
    | "WH"
    | "KW"
    | "ANZAHL"
    | "KUBIKMETER"
    | "STUNDE"
    | "TAG"
    | "MONAT"
    | "VAR"
    | "VARH"
    | "JAHR"
    | "KWH"
    | "MW"
    | "KVAR"
    | "KVARH"
    | "MWH";
  kennzahl?: string | null;
  schwachlastfaehig?: null | "NICHT_SCHWACHLASTFAEHIG" | "SCHWACHLASTFAEHIG";
  verwendungszwecke?:
    | ("NETZNUTZUNGSABRECHNUNG" | "BILANZKREISABRECHNUNG" | "MEHRMINDERMBENGENABRECHNUNG" | "ENDKUNDENABRECHNUNG")[]
    | null;
  verbrauchsart?: null | "KL" | "KLW" | "KLWS" | "W" | "WS";
  unterbrechbarkeit?: null | "UV" | "NUV";
  waermenutzung?: null | "SPEICHERHEIZUNG" | "WAERMEPUMPE" | "DIREKTHEIZUNG";
  konzessionsabgabe?: Konzessionsabgabe1;
  steuerbefreit?: boolean | null;
  vorkommastelle?: number | null;
  nachkommastelle?: number | null;
  guid?: string | null;
  [k: string]: unknown;
} | null;
export type Verbrauch = {
  type?: null | "ARBEITLEISTUNGTAGESPARAMETERABHMALO" | "VERANSCHLAGTEJAHRESMENGE" | "TUMKUNDENWERT";
  guid?: string | null;
  wertermittlungsverfahren: "PROGNOSE" | "MESSUNG";
  obiskennzahl: string;
  startdatum?: string;
  wert: number;
  enddatum?: string;
  einheit:
    | "WH"
    | "KW"
    | "ANZAHL"
    | "KUBIKMETER"
    | "STUNDE"
    | "TAG"
    | "MONAT"
    | "VAR"
    | "VARH"
    | "JAHR"
    | "KWH"
    | "MW"
    | "KVAR"
    | "KVARH"
    | "MWH";
  [k: string]: unknown;
} & Verbrauch1;
export type Verbrauch1 = {
  type?: null | "ARBEITLEISTUNGTAGESPARAMETERABHMALO" | "VERANSCHLAGTEJAHRESMENGE" | "TUMKUNDENWERT";
  guid?: string | null;
  wertermittlungsverfahren: "PROGNOSE" | "MESSUNG";
  obiskennzahl: string;
  startdatum?: string;
  wert: number;
  enddatum?: string;
  einheit:
    | "WH"
    | "KW"
    | "ANZAHL"
    | "KUBIKMETER"
    | "STUNDE"
    | "TAG"
    | "MONAT"
    | "VAR"
    | "VARH"
    | "JAHR"
    | "KWH"
    | "MW"
    | "KVAR"
    | "KVARH"
    | "MWH";
  [k: string]: unknown;
} | null;
export type Messlokation = {
  guid?: string | null;
  boTyp?: string | null;
  versionStruktur?: number;
  messLokationsId: string;
  sparte: "STROM" | "GAS" | "FERNWAERME" | "NAHWAERME" | "WASSER" | "ABWASSER";
  netzebeneMessung?:
    | null
    | "NSP"
    | "MSP"
    | "HSP"
    | "HSS"
    | "MSP_NSP_UMSP"
    | "HSP_MSP_UMSP"
    | "HSS_HSP_UMSP"
    | "HD"
    | "MD"
    | "ND";
  messgebietNr?: string | null;
  grundzustaendigerMSBCodeNr?: string | null;
  grundzustaendigerMSBIMCodeNr?: string | null;
  grundzustaendigerMDLodeNr?: string | null;
  messadresse?: Adresse1;
  geoadresse?: Geokoordinaten1;
  katasterinformation?: Katasteradresse1;
  geraete?: Hardware[] | null;
  messdienstleistung?: Dienstleistung[] | null;
  messlokationszaehler?: Zaehler[] | null;
  bilanzierungsmethode?: null | "RLM" | "SLP" | "TLP_GEMEINSAM" | "TLP_GETRENNT" | "PAUSCHAL" | "IMS";
  abrechnungmessstellenbetriebnna?: boolean | null;
  marktrollen?: Marktrolle1[] | null;
  gasqualitaet?: null | "H_GAS" | "H_GAS" | "L_GAS" | "L_GAS";
  verlustfaktor?: number | null;
  [k: string]: unknown;
} & Messlokation1;
export type Hardware = {
  geraetetyp:
    | "WECHSELSTROMZAEHLER"
    | "DREHSTROMZAEHLER"
    | "ZWEIRICHTUNGSZAEHLER"
    | "RLM_ZAEHLER"
    | "IMS_ZAEHLER"
    | "BALGENGASZAEHLER"
    | "MAXIMUMZAEHLER"
    | "MULTIPLEXANLAGE"
    | "PAUSCHALANLAGE"
    | "VERSTAERKERANLAGE"
    | "SUMMATIONSGERAET"
    | "IMPULSGEBER"
    | "EDL_21_ZAEHLERAUFSATZ"
    | "VIER_QUADRANTEN_LASTGANGZAEHLER"
    | "MENGENUMWERTER"
    | "STROMWANDLER"
    | "SPANNUNGSWANDLER"
    | "DATENLOGGER"
    | "KOMMUNIKATIONSANSCHLUSS"
    | "MODEM"
    | "TELEKOMMUNIKATIONSEINRICHTUNG"
    | "DREHKOLBENGASZAEHLER"
    | "TURBINENRADGASZAEHLER"
    | "ULTRASCHALLZAEHLER"
    | "WIRBELGASZAEHLER"
    | "MODERNE_MESSEINRICHTUNG"
    | "ELEKTRONISCHER_HAUSHALTSZAEHLER"
    | "STEUEREINRICHTUNG"
    | "TECHNISCHESTEUEREINRICHTUNG"
    | "TARIFSCHALTGERAET"
    | "RUNDSTEUEREMPFAENGER"
    | "OPTIONALE_ZUS_ZAEHLEINRICHTUNG"
    | "MESSWANDLERSATZ_IMS_MME"
    | "KOMBIMESSWANDLER_IMS_MME"
    | "TARIFSCHALTGERAET_IMS_MME"
    | "RUNDSTEUEREMPFAENGER_IMS_MME"
    | "TEMPERATUR_KOMPENSATION"
    | "HOECHSTBELASTUNGS_ANZEIGER"
    | "SONSTIGES_GERAET"
    | "SMARTMETERGATEWAY"
    | "STEUERBOX"
    | "BLOCKSTROMWANDLER"
    | "KOMBIMESSWANDLER";
  bezeichnung: string;
  geraeteeigenschaften?: Geraeteeigenschaften;
  geraetenummer?: string | null;
  geraetereferenz?: string | null;
  guid?: string | null;
  [k: string]: unknown;
} & Hardware1;
export type Geraeteeigenschaften = {
  geraetetyp:
    | "WECHSELSTROMZAEHLER"
    | "DREHSTROMZAEHLER"
    | "ZWEIRICHTUNGSZAEHLER"
    | "RLM_ZAEHLER"
    | "IMS_ZAEHLER"
    | "BALGENGASZAEHLER"
    | "MAXIMUMZAEHLER"
    | "MULTIPLEXANLAGE"
    | "PAUSCHALANLAGE"
    | "VERSTAERKERANLAGE"
    | "SUMMATIONSGERAET"
    | "IMPULSGEBER"
    | "EDL_21_ZAEHLERAUFSATZ"
    | "VIER_QUADRANTEN_LASTGANGZAEHLER"
    | "MENGENUMWERTER"
    | "STROMWANDLER"
    | "SPANNUNGSWANDLER"
    | "DATENLOGGER"
    | "KOMMUNIKATIONSANSCHLUSS"
    | "MODEM"
    | "TELEKOMMUNIKATIONSEINRICHTUNG"
    | "DREHKOLBENGASZAEHLER"
    | "TURBINENRADGASZAEHLER"
    | "ULTRASCHALLZAEHLER"
    | "WIRBELGASZAEHLER"
    | "MODERNE_MESSEINRICHTUNG"
    | "ELEKTRONISCHER_HAUSHALTSZAEHLER"
    | "STEUEREINRICHTUNG"
    | "TECHNISCHESTEUEREINRICHTUNG"
    | "TARIFSCHALTGERAET"
    | "RUNDSTEUEREMPFAENGER"
    | "OPTIONALE_ZUS_ZAEHLEINRICHTUNG"
    | "MESSWANDLERSATZ_IMS_MME"
    | "KOMBIMESSWANDLER_IMS_MME"
    | "TARIFSCHALTGERAET_IMS_MME"
    | "RUNDSTEUEREMPFAENGER_IMS_MME"
    | "TEMPERATUR_KOMPENSATION"
    | "HOECHSTBELASTUNGS_ANZEIGER"
    | "SONSTIGES_GERAET"
    | "SMARTMETERGATEWAY"
    | "STEUERBOX"
    | "BLOCKSTROMWANDLER"
    | "KOMBIMESSWANDLER";
  geraetemerkmal?:
    | null
    | "EINTARIF"
    | "ZWEITARIF"
    | "MEHRTARIF"
    | "GAS_G2_5"
    | "GAS_G4"
    | "GAS_G6"
    | "GAS_G10"
    | "GAS_G16"
    | "GAS_G25"
    | "GAS_G40"
    | "GAS_G65"
    | "GAS_G100"
    | "GAS_G160"
    | "GAS_G250"
    | "GAS_G400"
    | "GAS_G650"
    | "GAS_G1000"
    | "GAS_G1600"
    | "GAS_G2500"
    | "IMPULSGEBER_G4_G100"
    | "IMPULSGEBER_G100"
    | "MODEM_GSM"
    | "MODEM_GPRS"
    | "MODEM_FUNK"
    | "MODEM_GSM_O_LG"
    | "MODEM_GSM_M_LG"
    | "MODEM_FESTNETZ"
    | "MODEM_GPRS_M_LG"
    | "PLC_COM"
    | "ETHERNET_KOM"
    | "DSL_KOM"
    | "LTE_KOM"
    | "RUNDSTEUEREMPFAENGER"
    | "TARIFSCHALTGERAET"
    | "ZUSTANDS_MU"
    | "TEMPERATUR_MU"
    | "KOMPAKT_MU"
    | "SYSTEM_MU";
  parameter?: {
    [k: string]: string | null;
  } | null;
  guid?: string | null;
  [k: string]: unknown;
} & Geraeteeigenschaften1;
export type Geraeteeigenschaften1 = {
  geraetetyp:
    | "WECHSELSTROMZAEHLER"
    | "DREHSTROMZAEHLER"
    | "ZWEIRICHTUNGSZAEHLER"
    | "RLM_ZAEHLER"
    | "IMS_ZAEHLER"
    | "BALGENGASZAEHLER"
    | "MAXIMUMZAEHLER"
    | "MULTIPLEXANLAGE"
    | "PAUSCHALANLAGE"
    | "VERSTAERKERANLAGE"
    | "SUMMATIONSGERAET"
    | "IMPULSGEBER"
    | "EDL_21_ZAEHLERAUFSATZ"
    | "VIER_QUADRANTEN_LASTGANGZAEHLER"
    | "MENGENUMWERTER"
    | "STROMWANDLER"
    | "SPANNUNGSWANDLER"
    | "DATENLOGGER"
    | "KOMMUNIKATIONSANSCHLUSS"
    | "MODEM"
    | "TELEKOMMUNIKATIONSEINRICHTUNG"
    | "DREHKOLBENGASZAEHLER"
    | "TURBINENRADGASZAEHLER"
    | "ULTRASCHALLZAEHLER"
    | "WIRBELGASZAEHLER"
    | "MODERNE_MESSEINRICHTUNG"
    | "ELEKTRONISCHER_HAUSHALTSZAEHLER"
    | "STEUEREINRICHTUNG"
    | "TECHNISCHESTEUEREINRICHTUNG"
    | "TARIFSCHALTGERAET"
    | "RUNDSTEUEREMPFAENGER"
    | "OPTIONALE_ZUS_ZAEHLEINRICHTUNG"
    | "MESSWANDLERSATZ_IMS_MME"
    | "KOMBIMESSWANDLER_IMS_MME"
    | "TARIFSCHALTGERAET_IMS_MME"
    | "RUNDSTEUEREMPFAENGER_IMS_MME"
    | "TEMPERATUR_KOMPENSATION"
    | "HOECHSTBELASTUNGS_ANZEIGER"
    | "SONSTIGES_GERAET"
    | "SMARTMETERGATEWAY"
    | "STEUERBOX"
    | "BLOCKSTROMWANDLER"
    | "KOMBIMESSWANDLER";
  geraetemerkmal?:
    | null
    | "EINTARIF"
    | "ZWEITARIF"
    | "MEHRTARIF"
    | "GAS_G2_5"
    | "GAS_G4"
    | "GAS_G6"
    | "GAS_G10"
    | "GAS_G16"
    | "GAS_G25"
    | "GAS_G40"
    | "GAS_G65"
    | "GAS_G100"
    | "GAS_G160"
    | "GAS_G250"
    | "GAS_G400"
    | "GAS_G650"
    | "GAS_G1000"
    | "GAS_G1600"
    | "GAS_G2500"
    | "IMPULSGEBER_G4_G100"
    | "IMPULSGEBER_G100"
    | "MODEM_GSM"
    | "MODEM_GPRS"
    | "MODEM_FUNK"
    | "MODEM_GSM_O_LG"
    | "MODEM_GSM_M_LG"
    | "MODEM_FESTNETZ"
    | "MODEM_GPRS_M_LG"
    | "PLC_COM"
    | "ETHERNET_KOM"
    | "DSL_KOM"
    | "LTE_KOM"
    | "RUNDSTEUEREMPFAENGER"
    | "TARIFSCHALTGERAET"
    | "ZUSTANDS_MU"
    | "TEMPERATUR_MU"
    | "KOMPAKT_MU"
    | "SYSTEM_MU";
  parameter?: {
    [k: string]: string | null;
  } | null;
  guid?: string | null;
  [k: string]: unknown;
} | null;
export type Hardware1 = {
  geraetetyp:
    | "WECHSELSTROMZAEHLER"
    | "DREHSTROMZAEHLER"
    | "ZWEIRICHTUNGSZAEHLER"
    | "RLM_ZAEHLER"
    | "IMS_ZAEHLER"
    | "BALGENGASZAEHLER"
    | "MAXIMUMZAEHLER"
    | "MULTIPLEXANLAGE"
    | "PAUSCHALANLAGE"
    | "VERSTAERKERANLAGE"
    | "SUMMATIONSGERAET"
    | "IMPULSGEBER"
    | "EDL_21_ZAEHLERAUFSATZ"
    | "VIER_QUADRANTEN_LASTGANGZAEHLER"
    | "MENGENUMWERTER"
    | "STROMWANDLER"
    | "SPANNUNGSWANDLER"
    | "DATENLOGGER"
    | "KOMMUNIKATIONSANSCHLUSS"
    | "MODEM"
    | "TELEKOMMUNIKATIONSEINRICHTUNG"
    | "DREHKOLBENGASZAEHLER"
    | "TURBINENRADGASZAEHLER"
    | "ULTRASCHALLZAEHLER"
    | "WIRBELGASZAEHLER"
    | "MODERNE_MESSEINRICHTUNG"
    | "ELEKTRONISCHER_HAUSHALTSZAEHLER"
    | "STEUEREINRICHTUNG"
    | "TECHNISCHESTEUEREINRICHTUNG"
    | "TARIFSCHALTGERAET"
    | "RUNDSTEUEREMPFAENGER"
    | "OPTIONALE_ZUS_ZAEHLEINRICHTUNG"
    | "MESSWANDLERSATZ_IMS_MME"
    | "KOMBIMESSWANDLER_IMS_MME"
    | "TARIFSCHALTGERAET_IMS_MME"
    | "RUNDSTEUEREMPFAENGER_IMS_MME"
    | "TEMPERATUR_KOMPENSATION"
    | "HOECHSTBELASTUNGS_ANZEIGER"
    | "SONSTIGES_GERAET"
    | "SMARTMETERGATEWAY"
    | "STEUERBOX"
    | "BLOCKSTROMWANDLER"
    | "KOMBIMESSWANDLER";
  bezeichnung: string;
  geraeteeigenschaften?: Geraeteeigenschaften1;
  geraetenummer?: string | null;
  geraetereferenz?: string | null;
  guid?: string | null;
  [k: string]: unknown;
} | null;
export type Dienstleistung = {
  dienstleistungstyp:
    | "DATENBEREITSTELLUNG_TAEGLICH"
    | "DATENBEREITSTELLUNG_WOECHENTLICH"
    | "DATENBEREITSTELLUNG_MONATLICH"
    | "DATENBEREITSTELLUNG_JAEHRLICH"
    | "DATENBEREITSTELLUNG_HISTORISCHE_LG"
    | "DATENBEREITSTELLUNG_STUENDLICH"
    | "DATENBEREITSTELLUNG_VIERTELJAEHRLICH"
    | "DATENBEREITSTELLUNG_HALBJAEHRLICH"
    | "DATENBEREITSTELLUNG_MONATLICH_ZUSAETZLICH"
    | "DATENBEREITSTELLUNG_EINMALIG"
    | "AUSLESUNG_2X_TAEGLICH_FERNAUSLESUNG"
    | "AUSLESUNG_TAEGLICH_FERNAUSLESUNG"
    | "AUSLESUNG_LGK_MANUELL_MSB"
    | "AUSLESUNG_MONATLICH_SLP_FERNAUSLESUNG"
    | "AUSLESUNG_JAEHRLICH_SLP_FERNAUSLESUNG"
    | "AUSLESUNG_MDE_SLP"
    | "ABLESUNG_MONATLICH_SLP"
    | "ABLESUNG_VIERTELJAEHRLICH_SLP"
    | "ABLESUNG_HALBJAEHRLICH_SLP"
    | "ABLESUNG_JAEHRLICH_SLP"
    | "AUSLESUNG_SLP_FERNAUSLESUNG"
    | "ABLESUNG_SLP_ZUSAETZLICH_MSB"
    | "ABLESUNG_SLP_ZUSAETZLICH_KUNDE"
    | "AUSLESUNG_LGK_FERNAUSLESUNG_ZUSAETZLICH_MSB"
    | "AUSLESUNG_MOATLICH_FERNAUSLESUNG"
    | "AUSLESUNG_STUENDLICH_FERNAUSLESUNG"
    | "ABLESUNG_MONATLICH_LGK"
    | "AUSLESUNG_TEMERATURMENGENUMWERTER"
    | "AUSLESUNG_ZUSTANDSMENGENUMWERTER"
    | "AUSLESUNG_SYSTEMMENGENUMWERTER"
    | "AUSLESUNG_VORGANG_SLP"
    | "AUSLESUUNG_KOMPAKTMENGENUMWERTER"
    | "AUSLESUNG_MDE_LGK"
    | "SPERRUNG_SLP"
    | "ENTSPERRUNG_SLP"
    | "SPERRUNG_RLM"
    | "ENTSPERRUNG_RLM"
    | "MAHNKOSTEN"
    | "INKASSOKOSTEN";
  bezeichnung: string;
  guid?: string | null;
  [k: string]: unknown;
} & Dienstleistung1;
export type Dienstleistung1 = {
  dienstleistungstyp:
    | "DATENBEREITSTELLUNG_TAEGLICH"
    | "DATENBEREITSTELLUNG_WOECHENTLICH"
    | "DATENBEREITSTELLUNG_MONATLICH"
    | "DATENBEREITSTELLUNG_JAEHRLICH"
    | "DATENBEREITSTELLUNG_HISTORISCHE_LG"
    | "DATENBEREITSTELLUNG_STUENDLICH"
    | "DATENBEREITSTELLUNG_VIERTELJAEHRLICH"
    | "DATENBEREITSTELLUNG_HALBJAEHRLICH"
    | "DATENBEREITSTELLUNG_MONATLICH_ZUSAETZLICH"
    | "DATENBEREITSTELLUNG_EINMALIG"
    | "AUSLESUNG_2X_TAEGLICH_FERNAUSLESUNG"
    | "AUSLESUNG_TAEGLICH_FERNAUSLESUNG"
    | "AUSLESUNG_LGK_MANUELL_MSB"
    | "AUSLESUNG_MONATLICH_SLP_FERNAUSLESUNG"
    | "AUSLESUNG_JAEHRLICH_SLP_FERNAUSLESUNG"
    | "AUSLESUNG_MDE_SLP"
    | "ABLESUNG_MONATLICH_SLP"
    | "ABLESUNG_VIERTELJAEHRLICH_SLP"
    | "ABLESUNG_HALBJAEHRLICH_SLP"
    | "ABLESUNG_JAEHRLICH_SLP"
    | "AUSLESUNG_SLP_FERNAUSLESUNG"
    | "ABLESUNG_SLP_ZUSAETZLICH_MSB"
    | "ABLESUNG_SLP_ZUSAETZLICH_KUNDE"
    | "AUSLESUNG_LGK_FERNAUSLESUNG_ZUSAETZLICH_MSB"
    | "AUSLESUNG_MOATLICH_FERNAUSLESUNG"
    | "AUSLESUNG_STUENDLICH_FERNAUSLESUNG"
    | "ABLESUNG_MONATLICH_LGK"
    | "AUSLESUNG_TEMERATURMENGENUMWERTER"
    | "AUSLESUNG_ZUSTANDSMENGENUMWERTER"
    | "AUSLESUNG_SYSTEMMENGENUMWERTER"
    | "AUSLESUNG_VORGANG_SLP"
    | "AUSLESUUNG_KOMPAKTMENGENUMWERTER"
    | "AUSLESUNG_MDE_LGK"
    | "SPERRUNG_SLP"
    | "ENTSPERRUNG_SLP"
    | "SPERRUNG_RLM"
    | "ENTSPERRUNG_RLM"
    | "MAHNKOSTEN"
    | "INKASSOKOSTEN";
  bezeichnung: string;
  guid?: string | null;
  [k: string]: unknown;
} | null;
export type Zaehler = {
  guid?: string | null;
  boTyp?: string | null;
  versionStruktur?: number;
  zaehlernummer: string;
  sparte: "STROM" | "GAS" | "FERNWAERME" | "NAHWAERME" | "WASSER" | "ABWASSER";
  zaehlerauspraegung: "EINRICHTUNGSZAEHLER" | "ZWEIRICHTUNGSZAEHLER";
  zaehlertyp:
    | "DREHSTROMZAEHLER"
    | "BALGENGASZAEHLER"
    | "DREHKOLBENZAEHLER"
    | "SMARTMETER"
    | "LEISTUNGSZAEHLER"
    | "MAXIMUMZAEHLER"
    | "TURBINENRADGASZAEHLER"
    | "ULTRASCHALLGASZAEHLER"
    | "WECHSELSTROMZAEHLER";
  tarifart: "EINTARIF" | "ZWEITARIF" | "MEHRTARIF" | "SMART_METER" | "LEISTUNGSGEMESSEN";
  zaehlerkonstante?: number;
  eichungBis?: string | null;
  letzteEichung?: string | null;
  /**
   * @minItems 1
   */
  zaehlwerke: [Zaehlwerk1, ...Zaehlwerk1[]];
  zaehlerhersteller?: Geschaeftspartner11;
  gateway?: string | null;
  fernschaltung?: null | "VORHANDEN" | "NICHT_VORHANDEN";
  messwerterfassung?: null | "FERNAUSLESBAR" | "MANUELL_AUSGELESENE";
  [k: string]: unknown;
} & Zaehler1;
export type Zaehler1 = {
  guid?: string | null;
  boTyp?: string | null;
  versionStruktur?: number;
  zaehlernummer: string;
  sparte: "STROM" | "GAS" | "FERNWAERME" | "NAHWAERME" | "WASSER" | "ABWASSER";
  zaehlerauspraegung: "EINRICHTUNGSZAEHLER" | "ZWEIRICHTUNGSZAEHLER";
  zaehlertyp:
    | "DREHSTROMZAEHLER"
    | "BALGENGASZAEHLER"
    | "DREHKOLBENZAEHLER"
    | "SMARTMETER"
    | "LEISTUNGSZAEHLER"
    | "MAXIMUMZAEHLER"
    | "TURBINENRADGASZAEHLER"
    | "ULTRASCHALLGASZAEHLER"
    | "WECHSELSTROMZAEHLER";
  tarifart: "EINTARIF" | "ZWEITARIF" | "MEHRTARIF" | "SMART_METER" | "LEISTUNGSGEMESSEN";
  zaehlerkonstante?: number;
  eichungBis?: string | null;
  letzteEichung?: string | null;
  /**
   * @minItems 1
   */
  zaehlwerke: [Zaehlwerk1, ...Zaehlwerk1[]];
  zaehlerhersteller?: Geschaeftspartner11;
  gateway?: string | null;
  fernschaltung?: null | "VORHANDEN" | "NICHT_VORHANDEN";
  messwerterfassung?: null | "FERNAUSLESBAR" | "MANUELL_AUSGELESENE";
  [k: string]: unknown;
} | null;
export type Messlokation1 = {
  guid?: string | null;
  boTyp?: string | null;
  versionStruktur?: number;
  messLokationsId: string;
  sparte: "STROM" | "GAS" | "FERNWAERME" | "NAHWAERME" | "WASSER" | "ABWASSER";
  netzebeneMessung?:
    | null
    | "NSP"
    | "MSP"
    | "HSP"
    | "HSS"
    | "MSP_NSP_UMSP"
    | "HSP_MSP_UMSP"
    | "HSS_HSP_UMSP"
    | "HD"
    | "MD"
    | "ND";
  messgebietNr?: string | null;
  grundzustaendigerMSBCodeNr?: string | null;
  grundzustaendigerMSBIMCodeNr?: string | null;
  grundzustaendigerMDLodeNr?: string | null;
  messadresse?: Adresse1;
  geoadresse?: Geokoordinaten1;
  katasterinformation?: Katasteradresse1;
  geraete?: Hardware[] | null;
  messdienstleistung?: Dienstleistung[] | null;
  messlokationszaehler?: Zaehler[] | null;
  bilanzierungsmethode?: null | "RLM" | "SLP" | "TLP_GEMEINSAM" | "TLP_GETRENNT" | "PAUSCHAL" | "IMS";
  abrechnungmessstellenbetriebnna?: boolean | null;
  marktrollen?: Marktrolle1[] | null;
  gasqualitaet?: null | "H_GAS" | "H_GAS" | "L_GAS" | "L_GAS";
  verlustfaktor?: number | null;
  [k: string]: unknown;
} | null;
export type Messlokationszuordnung = {
  messlokationsId: string;
  arithmetik?: null | "ADDITION" | "SUBTRAKTION" | "MULTIPLIKATION" | "DIVISION";
  gueltigSeit?: string | null;
  gueltigBis?: string | null;
  guid?: string | null;
  [k: string]: unknown;
} & Messlokationszuordnung1;
export type Messlokationszuordnung1 = {
  messlokationsId: string;
  arithmetik?: null | "ADDITION" | "SUBTRAKTION" | "MULTIPLIKATION" | "DIVISION";
  gueltigSeit?: string | null;
  gueltigBis?: string | null;
  guid?: string | null;
  [k: string]: unknown;
} | null;
export type Marktlokation1 = {
  guid?: string | null;
  boTyp?: string | null;
  versionStruktur?: number;
  marktlokationsId: string;
  sparte: "STROM" | "GAS" | "FERNWAERME" | "NAHWAERME" | "WASSER" | "ABWASSER";
  energierichtung: "AUSSP" | "EINSP";
  bilanzierungsmethode: "RLM" | "SLP" | "TLP_GEMEINSAM" | "TLP_GETRENNT" | "PAUSCHAL" | "IMS";
  verbrauchsart?: null | "KL" | "KLW" | "KLWS" | "W" | "WS";
  unterbrechbar?: boolean | null;
  netzebene: "NSP" | "MSP" | "HSP" | "HSS" | "MSP_NSP_UMSP" | "HSP_MSP_UMSP" | "HSS_HSP_UMSP" | "HD" | "MD" | "ND";
  netzbetreiberCodeNr?: string | null;
  gebietTyp?:
    | null
    | "REGELZONE"
    | "MARKTGEBIET"
    | "BILANZIERUNGSGEBIET"
    | "VERTEILNETZ"
    | "TRANSPORTNETZ"
    | "REGIONALNETZ"
    | "AREALNETZ"
    | "GRUNDVERSORGUNGSGEBIET"
    | "VERSORGUNGSGEBIET";
  netzgebietNr?: string | null;
  bilanzierungsgebiet?: string | null;
  grundversorgerCodeNr?: string | null;
  gasqualitaet?: null | "H_GAS" | "H_GAS" | "L_GAS" | "L_GAS";
  endkunde?: Geschaeftspartner11;
  lokationsadresse?: Adresse1;
  geoadresse?: Geokoordinaten1;
  katasterinformation?: Katasteradresse1;
  marktrollen?: Marktrolle[] | null;
  regelzone?: string | null;
  marktgebiet?: string | null;
  zeitreihentyp?: null | "EGS" | "LGS" | "NZR" | "SES" | "SLS" | "TES" | "TLS";
  zaehlwerke?: Zaehlwerk[] | null;
  verbauchsmenge?: Verbrauch[] | null;
  messlokationen?: Messlokation[] | null;
  zugehoerigeMesslokationen?: Messlokationszuordnung[] | null;
  [k: string]: unknown;
} | null;
export type Angebotsposition = {
  positionsbezeichung: string;
  positionsmenge?: Menge1;
  positionspreis: Preis;
  positionsbetrag?: Betrag1;
  guid?: string | null;
  [k: string]: unknown;
} & Angebotsposition1;
export type Angebotsposition1 = {
  positionsbezeichung: string;
  positionsmenge?: Menge1;
  positionspreis: Preis;
  positionsbetrag?: Betrag1;
  guid?: string | null;
  [k: string]: unknown;
} | null;
export type Angebotsteil1 = {
  anfrageSubreferenz?: string | null;
  lieferstellenangebotsteil?: Marktlokation[] | null;
  gesamtmengeangebotsteil?: Menge1;
  gesamtkostenangebotsteil?: Betrag1;
  positionen: Angebotsposition[];
  guid?: string | null;
  [k: string]: unknown;
} | null;
export type Angebotsvariante1 = {
  angebotsstatus:
    | "KONZEPTION"
    | "UNVERBINDLICH"
    | "VERBINDLICH"
    | "BEAUFTRAGT"
    | "UNGUELTIG"
    | "ABGELEHNT"
    | "NACHGEFASST"
    | "AUSSTEHEND"
    | "ERLEDIGT";
  beschreibung?: string | null;
  erstelldatum?: string;
  bindefrist: string;
  gesamtmenge?: Menge1;
  gesamtkosten?: Betrag1;
  teile: Angebotsteil[];
  guid?: string | null;
  [k: string]: unknown;
} | null;

export interface BO4EBOAngebot {
  guid?: string | null;
  boTyp?: string | null;
  versionStruktur?: number;
  angebotsnummer: string;
  anfragereferenz?: string | null;
  angebotsdatum: string;
  sparte: "STROM" | "GAS" | "FERNWAERME" | "NAHWAERME" | "WASSER" | "ABWASSER";
  bindefrist?: string;
  angebotgeber: Geschaeftspartner;
  angebotnehmer: Geschaeftspartner;
  unterzeichnerAngebotsnehmer?: Ansprechpartner;
  unterzeichnerAngebotsgeber?: Ansprechpartner1;
  /**
   * @minItems 1
   */
  varianten?: [Angebotsvariante, ...Angebotsvariante1[]] | null;
  [k: string]: unknown;
}
export interface Geschaeftspartner {
  guid?: string | null;
  boTyp?: string | null;
  versionStruktur?: number;
  anrede?: null | "HERR" | "FRAU" | "EHELEUTE" | "FIRMA" | "INDIVIDUELL" | "DR";
  title?: string | null;
  name1?: string | null;
  name2?: string | null;
  name3?: string | null;
  gewerbekennzeichnung: boolean;
  hrnummer?: string | null;
  amtsgericht?: string | null;
  kontaktweg?: ("ANSCHREIBEN" | "TELEFONAT" | "FAX" | "E_MAIL" | "SMS")[] | null;
  umsatzsteuerId?: string | null;
  glaeubigerId?: string | null;
  eMailAdresse?: string | null;
  website?: string | null;
  geschaeftspartnerrolle?: ("LIEFERANT" | "DIENSTLEISTER" | "KUNDE" | "INTERESSENT" | "MARKTPARTNER")[] | null;
  partneradresse?: Adresse;
  [k: string]: unknown;
}
export interface Preis {
  wert: number;
  einheit: "EUR" | "CT";
  bezugswert:
    | "WH"
    | "KW"
    | "ANZAHL"
    | "KUBIKMETER"
    | "STUNDE"
    | "TAG"
    | "MONAT"
    | "VAR"
    | "VARH"
    | "JAHR"
    | "KWH"
    | "MW"
    | "KVAR"
    | "KVARH"
    | "MWH";
  status?: null | "VORLAEUFIG" | "ENDGUELTIG";
  guid?: string | null;
  [k: string]: unknown;
}
