/* eslint-disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

export type ExterneReferenz = {
  exRefName?: string | null;
  exRefWert?: string | null;
  timestamp?: string | null;
  guid?: string | null;
  [k: string]: unknown;
} & ExterneReferenz1;
export type ExterneReferenz1 = {
  exRefName?: string | null;
  exRefWert?: string | null;
  timestamp?: string | null;
  guid?: string | null;
  [k: string]: unknown;
} | null;
export type Notiz = {
  timestamp?: string | null;
  guid?: string | null;
  inhalt: string;
  autor: string;
  zeitpunkt: string;
  [k: string]: unknown;
} & Notiz1;
export type Notiz1 = {
  timestamp?: string | null;
  guid?: string | null;
  inhalt: string;
  autor: string;
  zeitpunkt: string;
  [k: string]: unknown;
} | null;
export type Aufgabe = {
  aufgabenId: string;
  beschreibung?: string | null;
  deadline?: string | null;
  ausgefuehrt: boolean;
  ausfuehrungszeitpunkt?: string | null;
  ausfuehrender?: string | null;
  timestamp?: string | null;
  guid?: string | null;
  [k: string]: unknown;
} & Aufgabe1;
export type Aufgabe1 = {
  aufgabenId: string;
  beschreibung?: string | null;
  deadline?: string | null;
  ausgefuehrt: boolean;
  ausfuehrungszeitpunkt?: string | null;
  ausfuehrender?: string | null;
  timestamp?: string | null;
  guid?: string | null;
  [k: string]: unknown;
} | null;
export type GenericStringStringInfo = {
  keyColumn: string | null;
  value: string | null;
  timestamp?: string | null;
  guid?: string | null;
  [k: string]: unknown;
} & GenericStringStringInfo1;
export type GenericStringStringInfo1 = {
  keyColumn: string | null;
  value: string | null;
  timestamp?: string | null;
  guid?: string | null;
  [k: string]: unknown;
} | null;

export interface BO4EBOBenachrichtigung {
  boTyp?: string | null;
  versionStruktur?: string | null;
  timestamp?: string | null;
  benachrichtigungsId: string;
  externeReferenzen?: ExterneReferenz[] | null;
  prioritaet: "SEHR_NIEDRIG" | "NIEDRIG" | "NORMAL" | "HOCH" | "SEHR_HOCH";
  guid?: string | null;
  bearbeitungsstatus: "OFFEN" | "IN_BEARBEITUNG" | "ABGESCHLOSSEN" | "STORNIERT" | "QUITTIERT" | "IGNORIERT";
  kurztext: string;
  erstellungsZeitpunkt: string;
  kategorie?: string | null;
  bearbeiter?: string | null;
  notizen?: Notiz[] | null;
  deadline?: string | null;
  aufgaben?: Aufgabe[] | null;
  infos?: GenericStringStringInfo[] | null;
  [k: string]: unknown;
}
