/* tslint:disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

export interface BO4EBOLogObject {
  guid?: string | null;
  boTyp?: string | null;
  versionStruktur?: number;
  id: string;
  datetime: string;
  logMessage: string;
  [k: string]: unknown;
}
