/* eslint-disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

export type ExterneReferenz = {
  exRefName?: string | null;
  exRefWert?: string | null;
  timestamp?: string | null;
  guid?: string | null;
  [k: string]: unknown;
} & ExterneReferenz1;
export type ExterneReferenz1 = {
  exRefName?: string | null;
  exRefWert?: string | null;
  timestamp?: string | null;
  guid?: string | null;
  [k: string]: unknown;
} | null;
export type Geschaeftspartner = {
  boTyp?: string | null;
  versionStruktur?: string | null;
  timestamp?: string | null;
  externeReferenzen?: ExterneReferenz1[] | null;
  guid?: string | null;
  anrede?:
    | null
    | "HERR"
    | "FRAU"
    | "EHELEUTE"
    | "FIRMA"
    | "INDIVIDUELL"
    | "FAMILIE"
    | "ERBENGEMEINSCHAFT"
    | "WOHNGEMEINSCHAFT"
    | "GRUNDSTUECKGEMEINSCHAFT"
    | "DR";
  title?: string | null;
  name1?: string | null;
  name2?: string | null;
  name3?: string | null;
  gewerbekennzeichnung: boolean;
  hrnummer?: string | null;
  amtsgericht?: string | null;
  kontaktweg?: ("ANSCHREIBEN" | "TELEFONAT" | "FAX" | "E_MAIL" | "SMS")[] | null;
  umsatzsteuerId?: string | null;
  glaeubigerId?: string | null;
  eMailAdresse?: string | null;
  website?: string | null;
  geschaeftspartnerrolle?: ("LIEFERANT" | "DIENSTLEISTER" | "KUNDE" | "INTERESSENT" | "MARKTPARTNER")[] | null;
  partneradresse?: Adresse;
  grundlageZurVerringerungDerUmlagenNachEnfg?:
    | null
    | "KUNDE_ERFUELLT_VORAUSSETZUNG"
    | "KUNDE_ERFUELLT_VORAUSSETZUNG_NICHT"
    | "KEINE_ANGABE";
  [k: string]: unknown;
} & Geschaeftspartner1;
export type Adresse = {
  timestamp?: string | null;
  guid?: string | null;
  postleitzahl: string;
  ort: string;
  strasse?: string | null;
  hausnummer?: string | null;
  postfach?: string | null;
  adresszusatz?: string | null;
  coErgaenzung?: string | null;
  landescode?:
    | null
    | "AC"
    | "AD"
    | "AE"
    | "AF"
    | "AG"
    | "AI"
    | "AL"
    | "AM"
    | "AN"
    | "AO"
    | "AQ"
    | "AR"
    | "AS"
    | "AT"
    | "AU"
    | "AW"
    | "AX"
    | "AZ"
    | "BA"
    | "BB"
    | "BD"
    | "BE"
    | "BF"
    | "BG"
    | "BH"
    | "BI"
    | "BJ"
    | "BL"
    | "BM"
    | "BN"
    | "BO"
    | "BQ"
    | "BR"
    | "BS"
    | "BT"
    | "BU"
    | "BV"
    | "BW"
    | "BY"
    | "BZ"
    | "CA"
    | "CC"
    | "CD"
    | "CF"
    | "CG"
    | "CH"
    | "CI"
    | "CK"
    | "CL"
    | "CM"
    | "CN"
    | "CO"
    | "CP"
    | "CR"
    | "CS"
    | "CU"
    | "CV"
    | "CW"
    | "CX"
    | "CY"
    | "CZ"
    | "DE"
    | "DG"
    | "DJ"
    | "DK"
    | "DM"
    | "DO"
    | "DZ"
    | "EA"
    | "EC"
    | "EE"
    | "EG"
    | "EH"
    | "ER"
    | "ES"
    | "ET"
    | "EU"
    | "FI"
    | "FJ"
    | "FK"
    | "FM"
    | "FO"
    | "FR"
    | "FX"
    | "GA"
    | "GB"
    | "GD"
    | "GE"
    | "GF"
    | "GG"
    | "GH"
    | "GI"
    | "GL"
    | "GM"
    | "GN"
    | "GP"
    | "GQ"
    | "GR"
    | "GS"
    | "GT"
    | "GU"
    | "GW"
    | "GY"
    | "HK"
    | "HM"
    | "HN"
    | "HR"
    | "HT"
    | "HU"
    | "IC"
    | "ID"
    | "IE"
    | "IL"
    | "IM"
    | "IN"
    | "IO"
    | "IQ"
    | "IR"
    | "IS"
    | "IT"
    | "JE"
    | "JM"
    | "JO"
    | "JP"
    | "KE"
    | "KG"
    | "KH"
    | "KI"
    | "KM"
    | "KN"
    | "KP"
    | "KR"
    | "KW"
    | "KY"
    | "KZ"
    | "LA"
    | "LB"
    | "LC"
    | "LI"
    | "LK"
    | "LR"
    | "LS"
    | "LT"
    | "LU"
    | "LV"
    | "LY"
    | "MA"
    | "MC"
    | "MD"
    | "ME"
    | "MF"
    | "MG"
    | "MH"
    | "MK"
    | "ML"
    | "MM"
    | "MN"
    | "MO"
    | "MP"
    | "MQ"
    | "MR"
    | "MS"
    | "MT"
    | "MU"
    | "MV"
    | "MW"
    | "MX"
    | "MY"
    | "MZ"
    | "NA"
    | "NC"
    | "NE"
    | "NF"
    | "NG"
    | "NI"
    | "NL"
    | "NO"
    | "NP"
    | "NR"
    | "NT"
    | "NU"
    | "NZ"
    | "OM"
    | "PA"
    | "PE"
    | "PF"
    | "PG"
    | "PH"
    | "PK"
    | "PL"
    | "PM"
    | "PN"
    | "PR"
    | "PS"
    | "PT"
    | "PW"
    | "PY"
    | "QA"
    | "RE"
    | "RO"
    | "RS"
    | "RU"
    | "RW"
    | "SA"
    | "SB"
    | "SC"
    | "SD"
    | "SE"
    | "SF"
    | "SG"
    | "SH"
    | "SI"
    | "SJ"
    | "SK"
    | "SL"
    | "SM"
    | "SN"
    | "SO"
    | "SR"
    | "SS"
    | "ST"
    | "SU"
    | "SV"
    | "SX"
    | "SY"
    | "SZ"
    | "TA"
    | "TC"
    | "TD"
    | "TF"
    | "TG"
    | "TJ"
    | "TK"
    | "TL"
    | "TM"
    | "TN"
    | "TO"
    | "TP"
    | "TR"
    | "TT"
    | "TV"
    | "TW"
    | "TZ"
    | "UA"
    | "UG"
    | "UK"
    | "UM"
    | "US"
    | "UY"
    | "UZ"
    | "VA"
    | "VC"
    | "VE"
    | "VG"
    | "VI"
    | "VN"
    | "VU"
    | "WF"
    | "WS"
    | "XK"
    | "YE"
    | "YT"
    | "YU"
    | "ZA"
    | "ZM"
    | "ZR"
    | "ZW";
  ortsteil?: string | null;
  [k: string]: unknown;
} & Adresse1;
export type Adresse1 = {
  timestamp?: string | null;
  guid?: string | null;
  postleitzahl: string;
  ort: string;
  strasse?: string | null;
  hausnummer?: string | null;
  postfach?: string | null;
  adresszusatz?: string | null;
  coErgaenzung?: string | null;
  landescode?:
    | null
    | "AC"
    | "AD"
    | "AE"
    | "AF"
    | "AG"
    | "AI"
    | "AL"
    | "AM"
    | "AN"
    | "AO"
    | "AQ"
    | "AR"
    | "AS"
    | "AT"
    | "AU"
    | "AW"
    | "AX"
    | "AZ"
    | "BA"
    | "BB"
    | "BD"
    | "BE"
    | "BF"
    | "BG"
    | "BH"
    | "BI"
    | "BJ"
    | "BL"
    | "BM"
    | "BN"
    | "BO"
    | "BQ"
    | "BR"
    | "BS"
    | "BT"
    | "BU"
    | "BV"
    | "BW"
    | "BY"
    | "BZ"
    | "CA"
    | "CC"
    | "CD"
    | "CF"
    | "CG"
    | "CH"
    | "CI"
    | "CK"
    | "CL"
    | "CM"
    | "CN"
    | "CO"
    | "CP"
    | "CR"
    | "CS"
    | "CU"
    | "CV"
    | "CW"
    | "CX"
    | "CY"
    | "CZ"
    | "DE"
    | "DG"
    | "DJ"
    | "DK"
    | "DM"
    | "DO"
    | "DZ"
    | "EA"
    | "EC"
    | "EE"
    | "EG"
    | "EH"
    | "ER"
    | "ES"
    | "ET"
    | "EU"
    | "FI"
    | "FJ"
    | "FK"
    | "FM"
    | "FO"
    | "FR"
    | "FX"
    | "GA"
    | "GB"
    | "GD"
    | "GE"
    | "GF"
    | "GG"
    | "GH"
    | "GI"
    | "GL"
    | "GM"
    | "GN"
    | "GP"
    | "GQ"
    | "GR"
    | "GS"
    | "GT"
    | "GU"
    | "GW"
    | "GY"
    | "HK"
    | "HM"
    | "HN"
    | "HR"
    | "HT"
    | "HU"
    | "IC"
    | "ID"
    | "IE"
    | "IL"
    | "IM"
    | "IN"
    | "IO"
    | "IQ"
    | "IR"
    | "IS"
    | "IT"
    | "JE"
    | "JM"
    | "JO"
    | "JP"
    | "KE"
    | "KG"
    | "KH"
    | "KI"
    | "KM"
    | "KN"
    | "KP"
    | "KR"
    | "KW"
    | "KY"
    | "KZ"
    | "LA"
    | "LB"
    | "LC"
    | "LI"
    | "LK"
    | "LR"
    | "LS"
    | "LT"
    | "LU"
    | "LV"
    | "LY"
    | "MA"
    | "MC"
    | "MD"
    | "ME"
    | "MF"
    | "MG"
    | "MH"
    | "MK"
    | "ML"
    | "MM"
    | "MN"
    | "MO"
    | "MP"
    | "MQ"
    | "MR"
    | "MS"
    | "MT"
    | "MU"
    | "MV"
    | "MW"
    | "MX"
    | "MY"
    | "MZ"
    | "NA"
    | "NC"
    | "NE"
    | "NF"
    | "NG"
    | "NI"
    | "NL"
    | "NO"
    | "NP"
    | "NR"
    | "NT"
    | "NU"
    | "NZ"
    | "OM"
    | "PA"
    | "PE"
    | "PF"
    | "PG"
    | "PH"
    | "PK"
    | "PL"
    | "PM"
    | "PN"
    | "PR"
    | "PS"
    | "PT"
    | "PW"
    | "PY"
    | "QA"
    | "RE"
    | "RO"
    | "RS"
    | "RU"
    | "RW"
    | "SA"
    | "SB"
    | "SC"
    | "SD"
    | "SE"
    | "SF"
    | "SG"
    | "SH"
    | "SI"
    | "SJ"
    | "SK"
    | "SL"
    | "SM"
    | "SN"
    | "SO"
    | "SR"
    | "SS"
    | "ST"
    | "SU"
    | "SV"
    | "SX"
    | "SY"
    | "SZ"
    | "TA"
    | "TC"
    | "TD"
    | "TF"
    | "TG"
    | "TJ"
    | "TK"
    | "TL"
    | "TM"
    | "TN"
    | "TO"
    | "TP"
    | "TR"
    | "TT"
    | "TV"
    | "TW"
    | "TZ"
    | "UA"
    | "UG"
    | "UK"
    | "UM"
    | "US"
    | "UY"
    | "UZ"
    | "VA"
    | "VC"
    | "VE"
    | "VG"
    | "VI"
    | "VN"
    | "VU"
    | "WF"
    | "WS"
    | "XK"
    | "YE"
    | "YT"
    | "YU"
    | "ZA"
    | "ZM"
    | "ZR"
    | "ZW";
  ortsteil?: string | null;
  [k: string]: unknown;
} | null;
export type Geschaeftspartner1 = {
  boTyp?: string | null;
  versionStruktur?: string | null;
  timestamp?: string | null;
  externeReferenzen?: ExterneReferenz1[] | null;
  guid?: string | null;
  anrede?:
    | null
    | "HERR"
    | "FRAU"
    | "EHELEUTE"
    | "FIRMA"
    | "INDIVIDUELL"
    | "FAMILIE"
    | "ERBENGEMEINSCHAFT"
    | "WOHNGEMEINSCHAFT"
    | "GRUNDSTUECKGEMEINSCHAFT"
    | "DR";
  title?: string | null;
  name1?: string | null;
  name2?: string | null;
  name3?: string | null;
  gewerbekennzeichnung: boolean;
  hrnummer?: string | null;
  amtsgericht?: string | null;
  kontaktweg?: ("ANSCHREIBEN" | "TELEFONAT" | "FAX" | "E_MAIL" | "SMS")[] | null;
  umsatzsteuerId?: string | null;
  glaeubigerId?: string | null;
  eMailAdresse?: string | null;
  website?: string | null;
  geschaeftspartnerrolle?: ("LIEFERANT" | "DIENSTLEISTER" | "KUNDE" | "INTERESSENT" | "MARKTPARTNER")[] | null;
  partneradresse?: Adresse1;
  grundlageZurVerringerungDerUmlagenNachEnfg?:
    | null
    | "KUNDE_ERFUELLT_VORAUSSETZUNG"
    | "KUNDE_ERFUELLT_VORAUSSETZUNG_NICHT"
    | "KEINE_ANGABE";
  [k: string]: unknown;
} | null;
export type Geokoordinaten = {
  breitengrad: number;
  laengengrad: number;
  timestamp?: string | null;
  guid?: string | null;
  [k: string]: unknown;
} & Geokoordinaten1;
export type Geokoordinaten1 = {
  breitengrad: number;
  laengengrad: number;
  timestamp?: string | null;
  guid?: string | null;
  [k: string]: unknown;
} | null;
export type Katasteradresse = {
  gemarkung_flur: string;
  flurstueck: string;
  timestamp?: string | null;
  guid?: string | null;
  [k: string]: unknown;
} & Katasteradresse1;
export type Katasteradresse1 = {
  gemarkung_flur: string;
  flurstueck: string;
  timestamp?: string | null;
  guid?: string | null;
  [k: string]: unknown;
} | null;
export type MarktpartnerDetails = {
  rollencodenummer?: string | null;
  code?: string | null;
  marktrolle?:
    | null
    | "NB"
    | "LF"
    | "MSB"
    | "MDL"
    | "DL"
    | "BKV"
    | "BIKO"
    | "UENB"
    | "KUNDE_SELBST_NN"
    | "MGV"
    | "EIV"
    | "RB"
    | "KUNDE"
    | "INTERESSENT"
    | "GMSB";
  timestamp?: string | null;
  guid?: string | null;
  weiterverpflichtet?: boolean | null;
  [k: string]: unknown;
} & MarktpartnerDetails1;
export type MarktpartnerDetails1 = {
  rollencodenummer?: string | null;
  code?: string | null;
  marktrolle?:
    | null
    | "NB"
    | "LF"
    | "MSB"
    | "MDL"
    | "DL"
    | "BKV"
    | "BIKO"
    | "UENB"
    | "KUNDE_SELBST_NN"
    | "MGV"
    | "EIV"
    | "RB"
    | "KUNDE"
    | "INTERESSENT"
    | "GMSB";
  timestamp?: string | null;
  guid?: string | null;
  weiterverpflichtet?: boolean | null;
  [k: string]: unknown;
} | null;
export type Zaehlwerk = {
  timestamp?: string | null;
  guid?: string | null;
  zaehlwerkId?: string | null;
  bezeichnung?: string | null;
  richtung?: null | "AUSSP" | "EINSP";
  obisKennzahl?: string | null;
  wandlerfaktor?: number | null;
  einheit?:
    | null
    | "ZERO"
    | "WH"
    | "KW"
    | "ANZAHL"
    | "KUBIKMETER"
    | "STUNDE"
    | "TAG"
    | "MONAT"
    | "VAR"
    | "VARH"
    | "KWHK"
    | "JAHR"
    | "KWH"
    | "MW"
    | "KVAR"
    | "KVARH"
    | "MWH";
  kennzahl?: string | null;
  schwachlastfaehig?: null | "NICHT_SCHWACHLASTFAEHIG" | "SCHWACHLASTFAEHIG";
  verwendungszwecke?: Verwendungszweck[] | null;
  verbrauchsart?: null | "KL" | "KLW" | "KLWS" | "W" | "WS";
  unterbrechbarkeit?: null | "UV" | "NUV";
  waermenutzung?: null | "SPEICHERHEIZUNG" | "WAERMEPUMPE" | "DIREKTHEIZUNG";
  konzessionsabgabe?: Konzessionsabgabe;
  steuerbefreit?: boolean | null;
  vorkommastelle?: number | null;
  nachkommastelle?: number | null;
  abrechnungsrelevant?: boolean | null;
  anzahlAblesungen?: number | null;
  zaehlzeiten?: Zaehlzeitregister;
  konfiguration?: string | null;
  [k: string]: unknown;
} & Zaehlwerk1;
export type Verwendungszweck = {
  marktrolle:
    | "NB"
    | "LF"
    | "MSB"
    | "MDL"
    | "DL"
    | "BKV"
    | "BIKO"
    | "UENB"
    | "KUNDE_SELBST_NN"
    | "MGV"
    | "EIV"
    | "RB"
    | "KUNDE"
    | "INTERESSENT"
    | "GMSB";
  zweck?:
    | (
        | "NETZNUTZUNGSABRECHNUNG"
        | "BILANZKREISABRECHNUNG"
        | "MEHRMINDERMENGENABRECHNUNG"
        | "MEHRMINDERMBENGENABRECHNUNG"
        | "ENDKUNDENABRECHNUNG"
        | "BLINDARBEITABRECHNUNG_BETRIEBSFUEHRUNG"
        | "UEBERMITTLUNG_AN_DAS_HKNR"
        | "ERMITTLUNG_AUSGEGLICHENHEIT_BILANZKREIS"
      )[]
    | null;
  timestamp?: string | null;
  guid?: string | null;
  [k: string]: unknown;
} & Verwendungszweck1;
export type Verwendungszweck1 = {
  marktrolle:
    | "NB"
    | "LF"
    | "MSB"
    | "MDL"
    | "DL"
    | "BKV"
    | "BIKO"
    | "UENB"
    | "KUNDE_SELBST_NN"
    | "MGV"
    | "EIV"
    | "RB"
    | "KUNDE"
    | "INTERESSENT"
    | "GMSB";
  zweck?:
    | (
        | "NETZNUTZUNGSABRECHNUNG"
        | "BILANZKREISABRECHNUNG"
        | "MEHRMINDERMENGENABRECHNUNG"
        | "MEHRMINDERMBENGENABRECHNUNG"
        | "ENDKUNDENABRECHNUNG"
        | "BLINDARBEITABRECHNUNG_BETRIEBSFUEHRUNG"
        | "UEBERMITTLUNG_AN_DAS_HKNR"
        | "ERMITTLUNG_AUSGEGLICHENHEIT_BILANZKREIS"
      )[]
    | null;
  timestamp?: string | null;
  guid?: string | null;
  [k: string]: unknown;
} | null;
export type Konzessionsabgabe = {
  timestamp?: string | null;
  guid?: string | null;
  kosten?: number | null;
  kategorie?: string | null;
  satz: "KAS" | "SA" | "SAS" | "TA" | "TAS" | "TK" | "TKS" | "TS" | "TSS";
  [k: string]: unknown;
} & Konzessionsabgabe1;
export type Konzessionsabgabe1 = {
  timestamp?: string | null;
  guid?: string | null;
  kosten?: number | null;
  kategorie?: string | null;
  satz: "KAS" | "SA" | "SAS" | "TA" | "TAS" | "TK" | "TKS" | "TS" | "TSS";
  [k: string]: unknown;
} | null;
export type Zaehlzeitregister = {
  timestamp?: string | null;
  guid?: string | null;
  zaehlzeitDefinition?: string | null;
  register?: string | null;
  schwachlastfaehig?: null | "NICHT_SCHWACHLASTFAEHIG" | "SCHWACHLASTFAEHIG";
  [k: string]: unknown;
} & Zaehlzeitregister1;
export type Zaehlzeitregister1 = {
  timestamp?: string | null;
  guid?: string | null;
  zaehlzeitDefinition?: string | null;
  register?: string | null;
  schwachlastfaehig?: null | "NICHT_SCHWACHLASTFAEHIG" | "SCHWACHLASTFAEHIG";
  [k: string]: unknown;
} | null;
export type Zaehlwerk1 = {
  timestamp?: string | null;
  guid?: string | null;
  zaehlwerkId?: string | null;
  bezeichnung?: string | null;
  richtung?: null | "AUSSP" | "EINSP";
  obisKennzahl?: string | null;
  wandlerfaktor?: number | null;
  einheit?:
    | null
    | "ZERO"
    | "WH"
    | "KW"
    | "ANZAHL"
    | "KUBIKMETER"
    | "STUNDE"
    | "TAG"
    | "MONAT"
    | "VAR"
    | "VARH"
    | "KWHK"
    | "JAHR"
    | "KWH"
    | "MW"
    | "KVAR"
    | "KVARH"
    | "MWH";
  kennzahl?: string | null;
  schwachlastfaehig?: null | "NICHT_SCHWACHLASTFAEHIG" | "SCHWACHLASTFAEHIG";
  verwendungszwecke?: Verwendungszweck[] | null;
  verbrauchsart?: null | "KL" | "KLW" | "KLWS" | "W" | "WS";
  unterbrechbarkeit?: null | "UV" | "NUV";
  waermenutzung?: null | "SPEICHERHEIZUNG" | "WAERMEPUMPE" | "DIREKTHEIZUNG";
  konzessionsabgabe?: Konzessionsabgabe1;
  steuerbefreit?: boolean | null;
  vorkommastelle?: number | null;
  nachkommastelle?: number | null;
  abrechnungsrelevant?: boolean | null;
  anzahlAblesungen?: number | null;
  zaehlzeiten?: Zaehlzeitregister1;
  konfiguration?: string | null;
  [k: string]: unknown;
} | null;
export type Verbrauch = {
  startdatum?: string | null;
  enddatum?: string | null;
  type?: null | "ARBEITLEISTUNGTAGESPARAMETERABHMALO" | "VERANSCHLAGTEJAHRESMENGE" | "TUMKUNDENWERT";
  tarifstufe?:
    | null
    | "TARIFSTUFE_0"
    | "TARIFSTUFE_1"
    | "TARIFSTUFE_2"
    | "TARIFSTUFE_3"
    | "TARIFSTUFE_4"
    | "TARIFSTUFE_5"
    | "TARIFSTUFE_6"
    | "TARIFSTUFE_7"
    | "TARIFSTUFE_8"
    | "TARIFSTUFE_9";
  timestamp?: string | null;
  guid?: string | null;
  wertermittlungsverfahren?: null | "PROGNOSE" | "MESSUNG";
  messwertstatus?:
    | null
    | "ABGELESEN"
    | "ERSATZWERT"
    | "VOLAEUFIGERWERT"
    | "ANGABE_FUER_LIEFERSCHEIN"
    | "VORSCHLAGSWERT"
    | "NICHT_VERWENDBAR"
    | "PROGNOSEWERT"
    | "ENERGIEMENGESUMMIERT"
    | "FEHLT";
  statuszusatzinformationen?: StatusZusatzInformation[] | null;
  obiskennzahl: string;
  wert: number;
  einheit:
    | "ZERO"
    | "WH"
    | "KW"
    | "ANZAHL"
    | "KUBIKMETER"
    | "STUNDE"
    | "TAG"
    | "MONAT"
    | "VAR"
    | "VARH"
    | "KWHK"
    | "JAHR"
    | "KWH"
    | "MW"
    | "KVAR"
    | "KVARH"
    | "MWH";
  nutzungszeitpunkt?: string | null;
  ausfuehrungszeitpunkt?: string | null;
  [k: string]: unknown;
} & Verbrauch1;
export type StatusZusatzInformation = {
  timestamp?: string | null;
  art?:
    | null
    | "VERTRAG"
    | "MESSWERTQUALITAET"
    | "MESSKLASSIFIZIERUNG"
    | "PLAUSIBILISIERUNGSHINWEIS"
    | "ERSATZWERTBILDUNGSVERFAHREN"
    | "GRUND_ERSATZWERTBILDUNGSVERFAHREN"
    | "KORREKTURGRUND"
    | "GASQUALITAET";
  guid?: string | null;
  status?:
    | null
    | "TARIF_1"
    | "TARIF_2"
    | "TARIF_3"
    | "TARIF_4"
    | "TARIF_5"
    | "TARIF_6"
    | "TARIF_7"
    | "TARIF_8"
    | "TARIF_9"
    | "ZAEHLERSTAND_ZUM_BEGINN_DER_ANGEGEBENEN_ENERGIEMENGE_VORHANDEN_UND_KOMMUNIZIERT"
    | "ZAEHLERSTAND_ZUM_ENDE_DER_ANGEGEBENEN_ENERGIEMENGE_VORHANDEN_UND_KOMMUNIZIERT"
    | "ZAEHLERSTAND_ZUM_BEGINN_DER_ANGEGEBENEN_ENERGIEMENGE_NICHT_VORHANDEN_DA_MENGENABGRENZUNG"
    | "ZAEHLERSTAND_ZUM_ENDE_DER_ANGEGEBENEN_ENERGIEMENGE_NICHT_VORHANDEN_DA_MENGENABGRENZUNG"
    | "KEIN_ZUGANG"
    | "KOMMUNIKATIONSSTOERUNG"
    | "NETZAUSFALL"
    | "SPANNUNGSAUSFALL"
    | "STATUS_GERAETEWECHSEL"
    | "KALIBRIERUNG"
    | "GERAET_ARBEITET_AUSSERHALB_DER_BETRIEBSBEDINGUNGEN"
    | "MESSEINRICHTUNG_GESTOERT_DEFEKT"
    | "UNSICHERHEIT_MESSUNG"
    | "KUNDENSELBSTABLESUNG"
    | "LEERSTAND"
    | "REALER_ZAEHLERUEBERLAUF_GEPRUEFT"
    | "PLAUSIBEL_WG_KONTROLLABLESUNG"
    | "PLAUSIBEL_WG_KUNDENHINWEIS"
    | "VERGLEICHSMESSUNG_GEEICHT"
    | "VERGLEICHSMESSUNG_NICHT_GEEICHT"
    | "MESSWERTNACHBILDUNG_AUS_GEEICHTEN_WERTEN"
    | "MESSWERTNACHBILDUNG_AUS_NICHT_GEEICHTEN_WERTEN"
    | "INTERPOLATION"
    | "HALTEWERT"
    | "BILANZIERUNG_NETZABSCHNITT"
    | "HISTORISCHE_MESSWERTE"
    | "BERUECKSICHTIGUNG_STOERMENGENZAEHLWERK"
    | "MENGENUMWERTUNG_VOLLSTAENDIG"
    | "UHRZEIT_GESTELLT_SYNCHRONISATION"
    | "MESSWERT_UNPLAUSIBEL"
    | "FALSCHER_WANDLERFAKTOR"
    | "FEHLERHAFTE_ABLESUNG"
    | "AENDERUNG_DER_BERECHNUNG"
    | "UMBAU_DER_MESSLOKATION"
    | "DATENBEARBEITUNGSFEHLER"
    | "BRENNWERTKORREKTUR"
    | "Z_ZAHL_KORREKTUR"
    | "STOERUNG_DEFEKT_MESSEINRICHTUNG"
    | "AENDERUNG_TARIFSCHALTZEITEN"
    | "TARIFSCHALTGERAET_DEFEKT"
    | "AUSTAUSCH_DES_ERSATZWERTES"
    | "IMPULSWERTIGKEIT_NICHT_AUSREICHEND"
    | "UMSTELLUNG_GASQUALITAET"
    | "STATISTISCHE_METHODE"
    | "ENERGIEMENGE_IN_UNGEMESSENEM_ZEITINTERVALL"
    | "ENERGIEMENGE_AUS_DEM_UNGEPAIRTEN_ZEITINTERVALL"
    | "AUFTEILUNG"
    | "VERWENDUNG_VON_WERTEN_DES_STOERMENGENZAEHLWERKS"
    | "UMGANGS_UND_KORREKTURMENGEN"
    | "WARTUNGSARBEITEN_AN_GEEICHTEM_MESSGERAET"
    | "GESTOERTE_WERTE"
    | "WARTUNGSARBEITEN_AN_EICHRECHTSKONFORMEN_MESSGERAETEN"
    | "KONSISTENZ_UND_SYNCHRONPRUEFUNG"
    | "RECHENWERT"
    | "ANGABEN_MESSLOKATION"
    | "BASIS_MME"
    | "GRUND_ANGABEN_MESSLOKATION"
    | "ANFORDERUNG_IN_DIE_VERGANGENHEIT_ZUM_ANGEFORDERTEN_ZEITPUNKT_LIEGT_KEIN_WERT_VOR";
  [k: string]: unknown;
} & StatusZusatzInformation1;
export type StatusZusatzInformation1 = {
  timestamp?: string | null;
  art?:
    | null
    | "VERTRAG"
    | "MESSWERTQUALITAET"
    | "MESSKLASSIFIZIERUNG"
    | "PLAUSIBILISIERUNGSHINWEIS"
    | "ERSATZWERTBILDUNGSVERFAHREN"
    | "GRUND_ERSATZWERTBILDUNGSVERFAHREN"
    | "KORREKTURGRUND"
    | "GASQUALITAET";
  guid?: string | null;
  status?:
    | null
    | "TARIF_1"
    | "TARIF_2"
    | "TARIF_3"
    | "TARIF_4"
    | "TARIF_5"
    | "TARIF_6"
    | "TARIF_7"
    | "TARIF_8"
    | "TARIF_9"
    | "ZAEHLERSTAND_ZUM_BEGINN_DER_ANGEGEBENEN_ENERGIEMENGE_VORHANDEN_UND_KOMMUNIZIERT"
    | "ZAEHLERSTAND_ZUM_ENDE_DER_ANGEGEBENEN_ENERGIEMENGE_VORHANDEN_UND_KOMMUNIZIERT"
    | "ZAEHLERSTAND_ZUM_BEGINN_DER_ANGEGEBENEN_ENERGIEMENGE_NICHT_VORHANDEN_DA_MENGENABGRENZUNG"
    | "ZAEHLERSTAND_ZUM_ENDE_DER_ANGEGEBENEN_ENERGIEMENGE_NICHT_VORHANDEN_DA_MENGENABGRENZUNG"
    | "KEIN_ZUGANG"
    | "KOMMUNIKATIONSSTOERUNG"
    | "NETZAUSFALL"
    | "SPANNUNGSAUSFALL"
    | "STATUS_GERAETEWECHSEL"
    | "KALIBRIERUNG"
    | "GERAET_ARBEITET_AUSSERHALB_DER_BETRIEBSBEDINGUNGEN"
    | "MESSEINRICHTUNG_GESTOERT_DEFEKT"
    | "UNSICHERHEIT_MESSUNG"
    | "KUNDENSELBSTABLESUNG"
    | "LEERSTAND"
    | "REALER_ZAEHLERUEBERLAUF_GEPRUEFT"
    | "PLAUSIBEL_WG_KONTROLLABLESUNG"
    | "PLAUSIBEL_WG_KUNDENHINWEIS"
    | "VERGLEICHSMESSUNG_GEEICHT"
    | "VERGLEICHSMESSUNG_NICHT_GEEICHT"
    | "MESSWERTNACHBILDUNG_AUS_GEEICHTEN_WERTEN"
    | "MESSWERTNACHBILDUNG_AUS_NICHT_GEEICHTEN_WERTEN"
    | "INTERPOLATION"
    | "HALTEWERT"
    | "BILANZIERUNG_NETZABSCHNITT"
    | "HISTORISCHE_MESSWERTE"
    | "BERUECKSICHTIGUNG_STOERMENGENZAEHLWERK"
    | "MENGENUMWERTUNG_VOLLSTAENDIG"
    | "UHRZEIT_GESTELLT_SYNCHRONISATION"
    | "MESSWERT_UNPLAUSIBEL"
    | "FALSCHER_WANDLERFAKTOR"
    | "FEHLERHAFTE_ABLESUNG"
    | "AENDERUNG_DER_BERECHNUNG"
    | "UMBAU_DER_MESSLOKATION"
    | "DATENBEARBEITUNGSFEHLER"
    | "BRENNWERTKORREKTUR"
    | "Z_ZAHL_KORREKTUR"
    | "STOERUNG_DEFEKT_MESSEINRICHTUNG"
    | "AENDERUNG_TARIFSCHALTZEITEN"
    | "TARIFSCHALTGERAET_DEFEKT"
    | "AUSTAUSCH_DES_ERSATZWERTES"
    | "IMPULSWERTIGKEIT_NICHT_AUSREICHEND"
    | "UMSTELLUNG_GASQUALITAET"
    | "STATISTISCHE_METHODE"
    | "ENERGIEMENGE_IN_UNGEMESSENEM_ZEITINTERVALL"
    | "ENERGIEMENGE_AUS_DEM_UNGEPAIRTEN_ZEITINTERVALL"
    | "AUFTEILUNG"
    | "VERWENDUNG_VON_WERTEN_DES_STOERMENGENZAEHLWERKS"
    | "UMGANGS_UND_KORREKTURMENGEN"
    | "WARTUNGSARBEITEN_AN_GEEICHTEM_MESSGERAET"
    | "GESTOERTE_WERTE"
    | "WARTUNGSARBEITEN_AN_EICHRECHTSKONFORMEN_MESSGERAETEN"
    | "KONSISTENZ_UND_SYNCHRONPRUEFUNG"
    | "RECHENWERT"
    | "ANGABEN_MESSLOKATION"
    | "BASIS_MME"
    | "GRUND_ANGABEN_MESSLOKATION"
    | "ANFORDERUNG_IN_DIE_VERGANGENHEIT_ZUM_ANGEFORDERTEN_ZEITPUNKT_LIEGT_KEIN_WERT_VOR";
  [k: string]: unknown;
} | null;
export type Verbrauch1 = {
  startdatum?: string | null;
  enddatum?: string | null;
  type?: null | "ARBEITLEISTUNGTAGESPARAMETERABHMALO" | "VERANSCHLAGTEJAHRESMENGE" | "TUMKUNDENWERT";
  tarifstufe?:
    | null
    | "TARIFSTUFE_0"
    | "TARIFSTUFE_1"
    | "TARIFSTUFE_2"
    | "TARIFSTUFE_3"
    | "TARIFSTUFE_4"
    | "TARIFSTUFE_5"
    | "TARIFSTUFE_6"
    | "TARIFSTUFE_7"
    | "TARIFSTUFE_8"
    | "TARIFSTUFE_9";
  timestamp?: string | null;
  guid?: string | null;
  wertermittlungsverfahren?: null | "PROGNOSE" | "MESSUNG";
  messwertstatus?:
    | null
    | "ABGELESEN"
    | "ERSATZWERT"
    | "VOLAEUFIGERWERT"
    | "ANGABE_FUER_LIEFERSCHEIN"
    | "VORSCHLAGSWERT"
    | "NICHT_VERWENDBAR"
    | "PROGNOSEWERT"
    | "ENERGIEMENGESUMMIERT"
    | "FEHLT";
  statuszusatzinformationen?: StatusZusatzInformation[] | null;
  obiskennzahl: string;
  wert: number;
  einheit:
    | "ZERO"
    | "WH"
    | "KW"
    | "ANZAHL"
    | "KUBIKMETER"
    | "STUNDE"
    | "TAG"
    | "MONAT"
    | "VAR"
    | "VARH"
    | "KWHK"
    | "JAHR"
    | "KWH"
    | "MW"
    | "KVAR"
    | "KVARH"
    | "MWH";
  nutzungszeitpunkt?: string | null;
  ausfuehrungszeitpunkt?: string | null;
  [k: string]: unknown;
} | null;
export type Messlokation = {
  boTyp?: string | null;
  versionStruktur?: string | null;
  timestamp?: string | null;
  externeReferenzen?: ExterneReferenz1[] | null;
  guid?: string | null;
  messlokationsId: string;
  sparte: "STROM" | "GAS" | "FERNWAERME" | "NAHWAERME" | "WASSER" | "ABWASSER";
  netzebeneMessung?:
    | null
    | "NSP"
    | "MSP"
    | "HSP"
    | "HSS"
    | "MSP_NSP_UMSP"
    | "HSP_MSP_UMSP"
    | "HSS_HSP_UMSP"
    | "HD"
    | "MD"
    | "ND";
  messgebietNr?: string | null;
  grundzustaendigerMSBCodeNr?: string | null;
  grundzustaendigerMSBIMCodeNr?: string | null;
  grundzustaendigerMDLCodeNr?: string | null;
  messadresse?: Adresse1;
  geoadresse?: Geokoordinaten1;
  katasterinformation?: Katasteradresse1;
  geraete?: Hardware[] | null;
  messdienstleistung?: Dienstleistung[] | null;
  messlokationszaehler?: Zaehler[] | null;
  bilanzierungsmethode?: null | "RLM" | "SLP" | "TLP_GEMEINSAM" | "TLP_GETRENNT" | "PAUSCHAL" | "IMS";
  abrechnungmessstellenbetriebnna?: boolean | null;
  marktrollen?: MarktpartnerDetails1[] | null;
  gasqualitaet?: null | "ZERO" | "H_GAS" | "HGAS" | "L_GAS" | "LGAS";
  verlustfaktor?: number | null;
  zaehlwerke?: Zaehlwerk1[] | null;
  betriebszustand?: null | "GESPERRT_NICHT_ENTSPERREN" | "GESPERRT" | "REGELBETRIEB";
  messprodukte?: Messprodukt[] | null;
  [k: string]: unknown;
} & Messlokation1;
export type Hardware = {
  geraetetyp:
    | "WECHSELSTROMZAEHLER"
    | "DREHSTROMZAEHLER"
    | "ZWEIRICHTUNGSZAEHLER"
    | "RLM_ZAEHLER"
    | "IMS_ZAEHLER"
    | "BALGENGASZAEHLER"
    | "MAXIMUMZAEHLER"
    | "MULTIPLEXANLAGE"
    | "PAUSCHALANLAGE"
    | "VERSTAERKERANLAGE"
    | "SUMMATIONSGERAET"
    | "IMPULSGEBER"
    | "EDL_21_ZAEHLERAUFSATZ"
    | "VIER_QUADRANTEN_LASTGANGZAEHLER"
    | "MENGENUMWERTER"
    | "STROMWANDLER"
    | "SPANNUNGSWANDLER"
    | "DATENLOGGER"
    | "KOMMUNIKATIONSANSCHLUSS"
    | "MODEM"
    | "TELEKOMMUNIKATIONSEINRICHTUNG"
    | "DREHKOLBENGASZAEHLER"
    | "TURBINENRADGASZAEHLER"
    | "ULTRASCHALLZAEHLER"
    | "WIRBELGASZAEHLER"
    | "MODERNE_MESSEINRICHTUNG"
    | "ELEKTRONISCHER_HAUSHALTSZAEHLER"
    | "STEUEREINRICHTUNG"
    | "TECHNISCHESTEUEREINRICHTUNG"
    | "TARIFSCHALTGERAET"
    | "RUNDSTEUEREMPFAENGER"
    | "OPTIONALE_ZUS_ZAEHLEINRICHTUNG"
    | "MESSWANDLERSATZ_IMS_MME"
    | "KOMBIMESSWANDLER_IMS_MME"
    | "TARIFSCHALTGERAET_IMS_MME"
    | "RUNDSTEUEREMPFAENGER_IMS_MME"
    | "TEMPERATUR_KOMPENSATION"
    | "HOECHSTBELASTUNGS_ANZEIGER"
    | "SONSTIGES_GERAET"
    | "SMARTMETERGATEWAY"
    | "STEUERBOX"
    | "BLOCKSTROMWANDLER"
    | "KOMBIMESSWANDLER";
  bezeichnung: string;
  geraeteeigenschaften?: Geraeteeigenschaften;
  geraetenummer?: string | null;
  geraetereferenz?: string | null;
  timestamp?: string | null;
  guid?: string | null;
  [k: string]: unknown;
} & Hardware1;
export type Geraeteeigenschaften = {
  timestamp?: string | null;
  guid?: string | null;
  geraetetyp:
    | "WECHSELSTROMZAEHLER"
    | "DREHSTROMZAEHLER"
    | "ZWEIRICHTUNGSZAEHLER"
    | "RLM_ZAEHLER"
    | "IMS_ZAEHLER"
    | "BALGENGASZAEHLER"
    | "MAXIMUMZAEHLER"
    | "MULTIPLEXANLAGE"
    | "PAUSCHALANLAGE"
    | "VERSTAERKERANLAGE"
    | "SUMMATIONSGERAET"
    | "IMPULSGEBER"
    | "EDL_21_ZAEHLERAUFSATZ"
    | "VIER_QUADRANTEN_LASTGANGZAEHLER"
    | "MENGENUMWERTER"
    | "STROMWANDLER"
    | "SPANNUNGSWANDLER"
    | "DATENLOGGER"
    | "KOMMUNIKATIONSANSCHLUSS"
    | "MODEM"
    | "TELEKOMMUNIKATIONSEINRICHTUNG"
    | "DREHKOLBENGASZAEHLER"
    | "TURBINENRADGASZAEHLER"
    | "ULTRASCHALLZAEHLER"
    | "WIRBELGASZAEHLER"
    | "MODERNE_MESSEINRICHTUNG"
    | "ELEKTRONISCHER_HAUSHALTSZAEHLER"
    | "STEUEREINRICHTUNG"
    | "TECHNISCHESTEUEREINRICHTUNG"
    | "TARIFSCHALTGERAET"
    | "RUNDSTEUEREMPFAENGER"
    | "OPTIONALE_ZUS_ZAEHLEINRICHTUNG"
    | "MESSWANDLERSATZ_IMS_MME"
    | "KOMBIMESSWANDLER_IMS_MME"
    | "TARIFSCHALTGERAET_IMS_MME"
    | "RUNDSTEUEREMPFAENGER_IMS_MME"
    | "TEMPERATUR_KOMPENSATION"
    | "HOECHSTBELASTUNGS_ANZEIGER"
    | "SONSTIGES_GERAET"
    | "SMARTMETERGATEWAY"
    | "STEUERBOX"
    | "BLOCKSTROMWANDLER"
    | "KOMBIMESSWANDLER";
  geraetemerkmal?:
    | null
    | "EINTARIF"
    | "ZWEITARIF"
    | "MEHRTARIF"
    | "GAS_G2P5"
    | "GAS_G4"
    | "GAS_G6"
    | "GAS_G10"
    | "GAS_G16"
    | "GAS_G25"
    | "GAS_G40"
    | "GAS_G65"
    | "GAS_G100"
    | "GAS_G160"
    | "GAS_G250"
    | "GAS_G400"
    | "GAS_G650"
    | "GAS_G1000"
    | "GAS_G1600"
    | "GAS_G2500"
    | "IMPULSGEBER_G4_G100"
    | "IMPULSGEBER_G100"
    | "MODEM_GSM"
    | "MODEM_GPRS"
    | "MODEM_FUNK"
    | "MODEM_GSM_O_LG"
    | "MODEM_GSM_M_LG"
    | "MODEM_FESTNETZ"
    | "MODEM_GPRS_M_LG"
    | "PLC_COM"
    | "ETHERNET_KOM"
    | "DSL_KOM"
    | "LTE_KOM"
    | "RUNDSTEUEREMPFAENGER"
    | "TARIFSCHALTGERAET"
    | "ZUSTANDS_MU"
    | "TEMPERATUR_MU"
    | "KOMPAKT_MU"
    | "SYSTEM_MU"
    | "UNBESTIMMT"
    | "WASSER_MWZW"
    | "WASSER_WZWW"
    | "WASSER_WZ01"
    | "WASSER_WZ02"
    | "WASSER_WZ03"
    | "WASSER_WZ04"
    | "WASSER_WZ05"
    | "WASSER_WZ06"
    | "WASSER_WZ07"
    | "WASSER_WZ08"
    | "WASSER_WZ09"
    | "WASSER_WZ10"
    | "WASSER_VWZ04"
    | "WASSER_VWZ05"
    | "WASSER_VWZ06"
    | "WASSER_VWZ07"
    | "WASSER_VWZ10"
    | "GAS_G350"
    | "GAS_G4000"
    | "GAS_G6500"
    | "GAS_G10000"
    | "GAS_G12500"
    | "GAS_G16000";
  Parameter?: {
    [k: string]: string | null;
  } | null;
  [k: string]: unknown;
} & Geraeteeigenschaften1;
export type Geraeteeigenschaften1 = {
  timestamp?: string | null;
  guid?: string | null;
  geraetetyp:
    | "WECHSELSTROMZAEHLER"
    | "DREHSTROMZAEHLER"
    | "ZWEIRICHTUNGSZAEHLER"
    | "RLM_ZAEHLER"
    | "IMS_ZAEHLER"
    | "BALGENGASZAEHLER"
    | "MAXIMUMZAEHLER"
    | "MULTIPLEXANLAGE"
    | "PAUSCHALANLAGE"
    | "VERSTAERKERANLAGE"
    | "SUMMATIONSGERAET"
    | "IMPULSGEBER"
    | "EDL_21_ZAEHLERAUFSATZ"
    | "VIER_QUADRANTEN_LASTGANGZAEHLER"
    | "MENGENUMWERTER"
    | "STROMWANDLER"
    | "SPANNUNGSWANDLER"
    | "DATENLOGGER"
    | "KOMMUNIKATIONSANSCHLUSS"
    | "MODEM"
    | "TELEKOMMUNIKATIONSEINRICHTUNG"
    | "DREHKOLBENGASZAEHLER"
    | "TURBINENRADGASZAEHLER"
    | "ULTRASCHALLZAEHLER"
    | "WIRBELGASZAEHLER"
    | "MODERNE_MESSEINRICHTUNG"
    | "ELEKTRONISCHER_HAUSHALTSZAEHLER"
    | "STEUEREINRICHTUNG"
    | "TECHNISCHESTEUEREINRICHTUNG"
    | "TARIFSCHALTGERAET"
    | "RUNDSTEUEREMPFAENGER"
    | "OPTIONALE_ZUS_ZAEHLEINRICHTUNG"
    | "MESSWANDLERSATZ_IMS_MME"
    | "KOMBIMESSWANDLER_IMS_MME"
    | "TARIFSCHALTGERAET_IMS_MME"
    | "RUNDSTEUEREMPFAENGER_IMS_MME"
    | "TEMPERATUR_KOMPENSATION"
    | "HOECHSTBELASTUNGS_ANZEIGER"
    | "SONSTIGES_GERAET"
    | "SMARTMETERGATEWAY"
    | "STEUERBOX"
    | "BLOCKSTROMWANDLER"
    | "KOMBIMESSWANDLER";
  geraetemerkmal?:
    | null
    | "EINTARIF"
    | "ZWEITARIF"
    | "MEHRTARIF"
    | "GAS_G2P5"
    | "GAS_G4"
    | "GAS_G6"
    | "GAS_G10"
    | "GAS_G16"
    | "GAS_G25"
    | "GAS_G40"
    | "GAS_G65"
    | "GAS_G100"
    | "GAS_G160"
    | "GAS_G250"
    | "GAS_G400"
    | "GAS_G650"
    | "GAS_G1000"
    | "GAS_G1600"
    | "GAS_G2500"
    | "IMPULSGEBER_G4_G100"
    | "IMPULSGEBER_G100"
    | "MODEM_GSM"
    | "MODEM_GPRS"
    | "MODEM_FUNK"
    | "MODEM_GSM_O_LG"
    | "MODEM_GSM_M_LG"
    | "MODEM_FESTNETZ"
    | "MODEM_GPRS_M_LG"
    | "PLC_COM"
    | "ETHERNET_KOM"
    | "DSL_KOM"
    | "LTE_KOM"
    | "RUNDSTEUEREMPFAENGER"
    | "TARIFSCHALTGERAET"
    | "ZUSTANDS_MU"
    | "TEMPERATUR_MU"
    | "KOMPAKT_MU"
    | "SYSTEM_MU"
    | "UNBESTIMMT"
    | "WASSER_MWZW"
    | "WASSER_WZWW"
    | "WASSER_WZ01"
    | "WASSER_WZ02"
    | "WASSER_WZ03"
    | "WASSER_WZ04"
    | "WASSER_WZ05"
    | "WASSER_WZ06"
    | "WASSER_WZ07"
    | "WASSER_WZ08"
    | "WASSER_WZ09"
    | "WASSER_WZ10"
    | "WASSER_VWZ04"
    | "WASSER_VWZ05"
    | "WASSER_VWZ06"
    | "WASSER_VWZ07"
    | "WASSER_VWZ10"
    | "GAS_G350"
    | "GAS_G4000"
    | "GAS_G6500"
    | "GAS_G10000"
    | "GAS_G12500"
    | "GAS_G16000";
  Parameter?: {
    [k: string]: string | null;
  } | null;
  [k: string]: unknown;
} | null;
export type Hardware1 = {
  geraetetyp:
    | "WECHSELSTROMZAEHLER"
    | "DREHSTROMZAEHLER"
    | "ZWEIRICHTUNGSZAEHLER"
    | "RLM_ZAEHLER"
    | "IMS_ZAEHLER"
    | "BALGENGASZAEHLER"
    | "MAXIMUMZAEHLER"
    | "MULTIPLEXANLAGE"
    | "PAUSCHALANLAGE"
    | "VERSTAERKERANLAGE"
    | "SUMMATIONSGERAET"
    | "IMPULSGEBER"
    | "EDL_21_ZAEHLERAUFSATZ"
    | "VIER_QUADRANTEN_LASTGANGZAEHLER"
    | "MENGENUMWERTER"
    | "STROMWANDLER"
    | "SPANNUNGSWANDLER"
    | "DATENLOGGER"
    | "KOMMUNIKATIONSANSCHLUSS"
    | "MODEM"
    | "TELEKOMMUNIKATIONSEINRICHTUNG"
    | "DREHKOLBENGASZAEHLER"
    | "TURBINENRADGASZAEHLER"
    | "ULTRASCHALLZAEHLER"
    | "WIRBELGASZAEHLER"
    | "MODERNE_MESSEINRICHTUNG"
    | "ELEKTRONISCHER_HAUSHALTSZAEHLER"
    | "STEUEREINRICHTUNG"
    | "TECHNISCHESTEUEREINRICHTUNG"
    | "TARIFSCHALTGERAET"
    | "RUNDSTEUEREMPFAENGER"
    | "OPTIONALE_ZUS_ZAEHLEINRICHTUNG"
    | "MESSWANDLERSATZ_IMS_MME"
    | "KOMBIMESSWANDLER_IMS_MME"
    | "TARIFSCHALTGERAET_IMS_MME"
    | "RUNDSTEUEREMPFAENGER_IMS_MME"
    | "TEMPERATUR_KOMPENSATION"
    | "HOECHSTBELASTUNGS_ANZEIGER"
    | "SONSTIGES_GERAET"
    | "SMARTMETERGATEWAY"
    | "STEUERBOX"
    | "BLOCKSTROMWANDLER"
    | "KOMBIMESSWANDLER";
  bezeichnung: string;
  geraeteeigenschaften?: Geraeteeigenschaften1;
  geraetenummer?: string | null;
  geraetereferenz?: string | null;
  timestamp?: string | null;
  guid?: string | null;
  [k: string]: unknown;
} | null;
export type Dienstleistung = {
  dienstleistungstyp:
    | "DATENBEREITSTELLUNG_TAEGLICH"
    | "DATENBEREITSTELLUNG_WOECHENTLICH"
    | "DATENBEREITSTELLUNG_MONATLICH"
    | "DATENBEREITSTELLUNG_JAEHRLICH"
    | "DATENBEREITSTELLUNG_HISTORISCHE_LG"
    | "DATENBEREITSTELLUNG_STUENDLICH"
    | "DATENBEREITSTELLUNG_VIERTELJAEHRLICH"
    | "DATENBEREITSTELLUNG_HALBJAEHRLICH"
    | "DATENBEREITSTELLUNG_MONATLICH_ZUSAETZLICH"
    | "DATENBEREITSTELLUNG_EINMALIG"
    | "AUSLESUNG_2X_TAEGLICH_FERNAUSLESUNG"
    | "AUSLESUNG_TAEGLICH_FERNAUSLESUNG"
    | "AUSLESUNG_LGK_MANUELL_MSB"
    | "AUSLESUNG_MONATLICH_SLP_FERNAUSLESUNG"
    | "AUSLESUNG_JAEHRLICH_SLP_FERNAUSLESUNG"
    | "AUSLESUNG_MDE_SLP"
    | "ABLESUNG_MONATLICH_SLP"
    | "ABLESUNG_VIERTELJAEHRLICH_SLP"
    | "ABLESUNG_HALBJAEHRLICH_SLP"
    | "ABLESUNG_JAEHRLICH_SLP"
    | "AUSLESUNG_SLP_FERNAUSLESUNG"
    | "ABLESUNG_SLP_ZUSAETZLICH_MSB"
    | "ABLESUNG_SLP_ZUSAETZLICH_KUNDE"
    | "AUSLESUNG_LGK_FERNAUSLESUNG_ZUSAETZLICH_MSB"
    | "AUSLESUNG_MOATLICH_FERNAUSLESUNG"
    | "AUSLESUNG_STUENDLICH_FERNAUSLESUNG"
    | "ABLESUNG_MONATLICH_LGK"
    | "AUSLESUNG_TEMERATURMENGENUMWERTER"
    | "AUSLESUNG_ZUSTANDSMENGENUMWERTER"
    | "AUSLESUNG_SYSTEMMENGENUMWERTER"
    | "AUSLESUNG_VORGANG_SLP"
    | "AUSLESUUNG_KOMPAKTMENGENUMWERTER"
    | "AUSLESUNG_MDE_LGK"
    | "SPERRUNG_SLP"
    | "ENTSPERRUNG_SLP"
    | "SPERRUNG_RLM"
    | "ENTSPERRUNG_RLM"
    | "MAHNKOSTEN"
    | "INKASSOKOSTEN";
  bezeichnung: string;
  timestamp?: string | null;
  guid?: string | null;
  [k: string]: unknown;
} & Dienstleistung1;
export type Dienstleistung1 = {
  dienstleistungstyp:
    | "DATENBEREITSTELLUNG_TAEGLICH"
    | "DATENBEREITSTELLUNG_WOECHENTLICH"
    | "DATENBEREITSTELLUNG_MONATLICH"
    | "DATENBEREITSTELLUNG_JAEHRLICH"
    | "DATENBEREITSTELLUNG_HISTORISCHE_LG"
    | "DATENBEREITSTELLUNG_STUENDLICH"
    | "DATENBEREITSTELLUNG_VIERTELJAEHRLICH"
    | "DATENBEREITSTELLUNG_HALBJAEHRLICH"
    | "DATENBEREITSTELLUNG_MONATLICH_ZUSAETZLICH"
    | "DATENBEREITSTELLUNG_EINMALIG"
    | "AUSLESUNG_2X_TAEGLICH_FERNAUSLESUNG"
    | "AUSLESUNG_TAEGLICH_FERNAUSLESUNG"
    | "AUSLESUNG_LGK_MANUELL_MSB"
    | "AUSLESUNG_MONATLICH_SLP_FERNAUSLESUNG"
    | "AUSLESUNG_JAEHRLICH_SLP_FERNAUSLESUNG"
    | "AUSLESUNG_MDE_SLP"
    | "ABLESUNG_MONATLICH_SLP"
    | "ABLESUNG_VIERTELJAEHRLICH_SLP"
    | "ABLESUNG_HALBJAEHRLICH_SLP"
    | "ABLESUNG_JAEHRLICH_SLP"
    | "AUSLESUNG_SLP_FERNAUSLESUNG"
    | "ABLESUNG_SLP_ZUSAETZLICH_MSB"
    | "ABLESUNG_SLP_ZUSAETZLICH_KUNDE"
    | "AUSLESUNG_LGK_FERNAUSLESUNG_ZUSAETZLICH_MSB"
    | "AUSLESUNG_MOATLICH_FERNAUSLESUNG"
    | "AUSLESUNG_STUENDLICH_FERNAUSLESUNG"
    | "ABLESUNG_MONATLICH_LGK"
    | "AUSLESUNG_TEMERATURMENGENUMWERTER"
    | "AUSLESUNG_ZUSTANDSMENGENUMWERTER"
    | "AUSLESUNG_SYSTEMMENGENUMWERTER"
    | "AUSLESUNG_VORGANG_SLP"
    | "AUSLESUUNG_KOMPAKTMENGENUMWERTER"
    | "AUSLESUNG_MDE_LGK"
    | "SPERRUNG_SLP"
    | "ENTSPERRUNG_SLP"
    | "SPERRUNG_RLM"
    | "ENTSPERRUNG_RLM"
    | "MAHNKOSTEN"
    | "INKASSOKOSTEN";
  bezeichnung: string;
  timestamp?: string | null;
  guid?: string | null;
  [k: string]: unknown;
} | null;
export type Zaehler = {
  boTyp?: string | null;
  versionStruktur?: string | null;
  timestamp?: string | null;
  externeReferenzen?: ExterneReferenz1[] | null;
  guid?: string | null;
  zaehlernummer: string;
  sparte: "STROM" | "GAS" | "FERNWAERME" | "NAHWAERME" | "WASSER" | "ABWASSER";
  zaehlerauspraegung?: null | "EINRICHTUNGSZAEHLER" | "ZWEIRICHTUNGSZAEHLER";
  zaehlertyp?:
    | null
    | "DREHSTROMZAEHLER"
    | "BALGENGASZAEHLER"
    | "DREHKOLBENZAEHLER"
    | "SMARTMETER"
    | "LEISTUNGSZAEHLER"
    | "MAXIMUMZAEHLER"
    | "TURBINENRADGASZAEHLER"
    | "ULTRASCHALLGASZAEHLER"
    | "WECHSELSTROMZAEHLER"
    | "WIRBELGASZAEHLER"
    | "MESSDATENREGISTRIERGERAET"
    | "ELEKTRONISCHERHAUSHALTSZAEHLER"
    | "SONDERAUSSTATTUNG"
    | "WASSERZAEHLER"
    | "MODERNEMESSEINRICHTUNG"
    | "NEUEMESSEINRICHTUNGGAS";
  tarifart?: null | "EINTARIF" | "ZWEITARIF" | "MEHRTARIF" | "SMART_METER" | "LEISTUNGSGEMESSEN";
  zaehlerkonstante?: number | null;
  eichungBis?: string | null;
  letzteEichung?: string | null;
  /**
   * @minItems 1
   */
  zaehlwerke?: [Zaehlwerk1, ...Zaehlwerk1[]] | null;
  zaehlerhersteller?: Geschaeftspartner1;
  gateway?: string | null;
  fernschaltung?: null | "VORHANDEN" | "NICHT_VORHANDEN";
  messwerterfassung?: null | "FERNAUSLESBAR" | "MANUELL_AUSGELESENE";
  zaehlertypspezifikation?: null | "EDL40" | "EDL21" | "SONSTIGER_EHZ" | "MME_STANDARD" | "MME_MEDA";
  befestigungsart?: null | "STECKTECHNIK" | "DREIPUNKT" | "HUTSCHIENE" | "EINSTUTZEN" | "ZWEISTUTZEN";
  zaehlergroesse?:
    | null
    | "EINTARIF"
    | "ZWEITARIF"
    | "MEHRTARIF"
    | "GAS_G2P5"
    | "GAS_G4"
    | "GAS_G6"
    | "GAS_G10"
    | "GAS_G16"
    | "GAS_G25"
    | "GAS_G40"
    | "GAS_G65"
    | "GAS_G100"
    | "GAS_G160"
    | "GAS_G250"
    | "GAS_G400"
    | "GAS_G650"
    | "GAS_G1000"
    | "GAS_G1600"
    | "GAS_G2500"
    | "IMPULSGEBER_G4_G100"
    | "IMPULSGEBER_G100"
    | "MODEM_GSM"
    | "MODEM_GPRS"
    | "MODEM_FUNK"
    | "MODEM_GSM_O_LG"
    | "MODEM_GSM_M_LG"
    | "MODEM_FESTNETZ"
    | "MODEM_GPRS_M_LG"
    | "PLC_COM"
    | "ETHERNET_KOM"
    | "DSL_KOM"
    | "LTE_KOM"
    | "RUNDSTEUEREMPFAENGER"
    | "TARIFSCHALTGERAET"
    | "ZUSTANDS_MU"
    | "TEMPERATUR_MU"
    | "KOMPAKT_MU"
    | "SYSTEM_MU"
    | "UNBESTIMMT"
    | "WASSER_MWZW"
    | "WASSER_WZWW"
    | "WASSER_WZ01"
    | "WASSER_WZ02"
    | "WASSER_WZ03"
    | "WASSER_WZ04"
    | "WASSER_WZ05"
    | "WASSER_WZ06"
    | "WASSER_WZ07"
    | "WASSER_WZ08"
    | "WASSER_WZ09"
    | "WASSER_WZ10"
    | "WASSER_VWZ04"
    | "WASSER_VWZ05"
    | "WASSER_VWZ06"
    | "WASSER_VWZ07"
    | "WASSER_VWZ10"
    | "GAS_G350"
    | "GAS_G4000"
    | "GAS_G6500"
    | "GAS_G10000"
    | "GAS_G12500"
    | "GAS_G16000";
  geraete?: Geraet[] | null;
  [k: string]: unknown;
} & Zaehler1;
export type Geraet = {
  timestamp?: string | null;
  guid?: string | null;
  geraetenummer?: string | null;
  geraeteeigenschaften?: Geraeteeigenschaften1;
  geraeteart?:
    | null
    | "WANDLER"
    | "KOMMUNIKATIONSEINRICHTUNG"
    | "TECHNISCHE_STEUEREINRICHTUNG"
    | "MENGENUMWERTER"
    | "SMARTMETER_GATEWAY"
    | "STEUERBOX"
    | "ZAEHLEINRICHTUNG";
  [k: string]: unknown;
} & Geraet1;
export type Geraet1 = {
  timestamp?: string | null;
  guid?: string | null;
  geraetenummer?: string | null;
  geraeteeigenschaften?: Geraeteeigenschaften1;
  geraeteart?:
    | null
    | "WANDLER"
    | "KOMMUNIKATIONSEINRICHTUNG"
    | "TECHNISCHE_STEUEREINRICHTUNG"
    | "MENGENUMWERTER"
    | "SMARTMETER_GATEWAY"
    | "STEUERBOX"
    | "ZAEHLEINRICHTUNG";
  [k: string]: unknown;
} | null;
export type Zaehler1 = {
  boTyp?: string | null;
  versionStruktur?: string | null;
  timestamp?: string | null;
  externeReferenzen?: ExterneReferenz1[] | null;
  guid?: string | null;
  zaehlernummer: string;
  sparte: "STROM" | "GAS" | "FERNWAERME" | "NAHWAERME" | "WASSER" | "ABWASSER";
  zaehlerauspraegung?: null | "EINRICHTUNGSZAEHLER" | "ZWEIRICHTUNGSZAEHLER";
  zaehlertyp?:
    | null
    | "DREHSTROMZAEHLER"
    | "BALGENGASZAEHLER"
    | "DREHKOLBENZAEHLER"
    | "SMARTMETER"
    | "LEISTUNGSZAEHLER"
    | "MAXIMUMZAEHLER"
    | "TURBINENRADGASZAEHLER"
    | "ULTRASCHALLGASZAEHLER"
    | "WECHSELSTROMZAEHLER"
    | "WIRBELGASZAEHLER"
    | "MESSDATENREGISTRIERGERAET"
    | "ELEKTRONISCHERHAUSHALTSZAEHLER"
    | "SONDERAUSSTATTUNG"
    | "WASSERZAEHLER"
    | "MODERNEMESSEINRICHTUNG"
    | "NEUEMESSEINRICHTUNGGAS";
  tarifart?: null | "EINTARIF" | "ZWEITARIF" | "MEHRTARIF" | "SMART_METER" | "LEISTUNGSGEMESSEN";
  zaehlerkonstante?: number | null;
  eichungBis?: string | null;
  letzteEichung?: string | null;
  /**
   * @minItems 1
   */
  zaehlwerke?: [Zaehlwerk1, ...Zaehlwerk1[]] | null;
  zaehlerhersteller?: Geschaeftspartner1;
  gateway?: string | null;
  fernschaltung?: null | "VORHANDEN" | "NICHT_VORHANDEN";
  messwerterfassung?: null | "FERNAUSLESBAR" | "MANUELL_AUSGELESENE";
  zaehlertypspezifikation?: null | "EDL40" | "EDL21" | "SONSTIGER_EHZ" | "MME_STANDARD" | "MME_MEDA";
  befestigungsart?: null | "STECKTECHNIK" | "DREIPUNKT" | "HUTSCHIENE" | "EINSTUTZEN" | "ZWEISTUTZEN";
  zaehlergroesse?:
    | null
    | "EINTARIF"
    | "ZWEITARIF"
    | "MEHRTARIF"
    | "GAS_G2P5"
    | "GAS_G4"
    | "GAS_G6"
    | "GAS_G10"
    | "GAS_G16"
    | "GAS_G25"
    | "GAS_G40"
    | "GAS_G65"
    | "GAS_G100"
    | "GAS_G160"
    | "GAS_G250"
    | "GAS_G400"
    | "GAS_G650"
    | "GAS_G1000"
    | "GAS_G1600"
    | "GAS_G2500"
    | "IMPULSGEBER_G4_G100"
    | "IMPULSGEBER_G100"
    | "MODEM_GSM"
    | "MODEM_GPRS"
    | "MODEM_FUNK"
    | "MODEM_GSM_O_LG"
    | "MODEM_GSM_M_LG"
    | "MODEM_FESTNETZ"
    | "MODEM_GPRS_M_LG"
    | "PLC_COM"
    | "ETHERNET_KOM"
    | "DSL_KOM"
    | "LTE_KOM"
    | "RUNDSTEUEREMPFAENGER"
    | "TARIFSCHALTGERAET"
    | "ZUSTANDS_MU"
    | "TEMPERATUR_MU"
    | "KOMPAKT_MU"
    | "SYSTEM_MU"
    | "UNBESTIMMT"
    | "WASSER_MWZW"
    | "WASSER_WZWW"
    | "WASSER_WZ01"
    | "WASSER_WZ02"
    | "WASSER_WZ03"
    | "WASSER_WZ04"
    | "WASSER_WZ05"
    | "WASSER_WZ06"
    | "WASSER_WZ07"
    | "WASSER_WZ08"
    | "WASSER_WZ09"
    | "WASSER_WZ10"
    | "WASSER_VWZ04"
    | "WASSER_VWZ05"
    | "WASSER_VWZ06"
    | "WASSER_VWZ07"
    | "WASSER_VWZ10"
    | "GAS_G350"
    | "GAS_G4000"
    | "GAS_G6500"
    | "GAS_G10000"
    | "GAS_G12500"
    | "GAS_G16000";
  geraete?: Geraet[] | null;
  [k: string]: unknown;
} | null;
export type Messprodukt = {
  timestamp?: string | null;
  guid?: string | null;
  messproduktId?: string | null;
  verwendungszwecke?: Verwendungszweck1[] | null;
  verbrauchsart?: null | "KL" | "KLW" | "KLWS" | "W" | "WS";
  unterbrechbarkeit?: null | "UV" | "NUV";
  waermenutzung?: null | "SPEICHERHEIZUNG" | "WAERMEPUMPE" | "DIREKTHEIZUNG";
  zaehlzeiten?: Zaehlzeitregister1;
  zweiteMessung?: boolean | null;
  werteuebermittlungAnNB?: boolean | null;
  [k: string]: unknown;
} & Messprodukt1;
export type Messprodukt1 = {
  timestamp?: string | null;
  guid?: string | null;
  messproduktId?: string | null;
  verwendungszwecke?: Verwendungszweck1[] | null;
  verbrauchsart?: null | "KL" | "KLW" | "KLWS" | "W" | "WS";
  unterbrechbarkeit?: null | "UV" | "NUV";
  waermenutzung?: null | "SPEICHERHEIZUNG" | "WAERMEPUMPE" | "DIREKTHEIZUNG";
  zaehlzeiten?: Zaehlzeitregister1;
  zweiteMessung?: boolean | null;
  werteuebermittlungAnNB?: boolean | null;
  [k: string]: unknown;
} | null;
export type Messlokation1 = {
  boTyp?: string | null;
  versionStruktur?: string | null;
  timestamp?: string | null;
  externeReferenzen?: ExterneReferenz1[] | null;
  guid?: string | null;
  messlokationsId: string;
  sparte: "STROM" | "GAS" | "FERNWAERME" | "NAHWAERME" | "WASSER" | "ABWASSER";
  netzebeneMessung?:
    | null
    | "NSP"
    | "MSP"
    | "HSP"
    | "HSS"
    | "MSP_NSP_UMSP"
    | "HSP_MSP_UMSP"
    | "HSS_HSP_UMSP"
    | "HD"
    | "MD"
    | "ND";
  messgebietNr?: string | null;
  grundzustaendigerMSBCodeNr?: string | null;
  grundzustaendigerMSBIMCodeNr?: string | null;
  grundzustaendigerMDLCodeNr?: string | null;
  messadresse?: Adresse1;
  geoadresse?: Geokoordinaten1;
  katasterinformation?: Katasteradresse1;
  geraete?: Hardware[] | null;
  messdienstleistung?: Dienstleistung[] | null;
  messlokationszaehler?: Zaehler[] | null;
  bilanzierungsmethode?: null | "RLM" | "SLP" | "TLP_GEMEINSAM" | "TLP_GETRENNT" | "PAUSCHAL" | "IMS";
  abrechnungmessstellenbetriebnna?: boolean | null;
  marktrollen?: MarktpartnerDetails1[] | null;
  gasqualitaet?: null | "ZERO" | "H_GAS" | "HGAS" | "L_GAS" | "LGAS";
  verlustfaktor?: number | null;
  zaehlwerke?: Zaehlwerk1[] | null;
  betriebszustand?: null | "GESPERRT_NICHT_ENTSPERREN" | "GESPERRT" | "REGELBETRIEB";
  messprodukte?: Messprodukt[] | null;
  [k: string]: unknown;
} | null;
export type Messlokationszuordnung = {
  messlokationsId: string;
  arithmetik?: null | "ADDITION" | "SUBTRAKTION" | "MULTIPLIKATION" | "DIVISION" | "DIVIDEND" | "POSITIVWERT";
  gueltigSeit?: string | null;
  gueltigBis?: string | null;
  timestamp?: string | null;
  guid?: string | null;
  [k: string]: unknown;
} & Messlokationszuordnung1;
export type Messlokationszuordnung1 = {
  messlokationsId: string;
  arithmetik?: null | "ADDITION" | "SUBTRAKTION" | "MULTIPLIKATION" | "DIVISION" | "DIVIDEND" | "POSITIVWERT";
  gueltigSeit?: string | null;
  gueltigBis?: string | null;
  timestamp?: string | null;
  guid?: string | null;
  [k: string]: unknown;
} | null;
export type Netznutzungsabrechnungsdaten = {
  timestamp?: string | null;
  guid?: string | null;
  artikelId?: string | null;
  artikelIdTyp?: null | "ARTIKELID" | "GRUPPENARTIKELID";
  anzahl?: number | null;
  gemeinderabatt?: number | null;
  zuschlag?: number | null;
  abschlag?: number | null;
  singulaereBetriebsmittel?: Menge;
  preisSingulaereBetriebsmittel?: Preis;
  [k: string]: unknown;
} & Netznutzungsabrechnungsdaten1;
export type Menge = {
  timestamp?: string | null;
  guid?: string | null;
  wert: number;
  einheit?:
    | null
    | "ZERO"
    | "WH"
    | "KW"
    | "ANZAHL"
    | "KUBIKMETER"
    | "STUNDE"
    | "TAG"
    | "MONAT"
    | "VAR"
    | "VARH"
    | "KWHK"
    | "JAHR"
    | "KWH"
    | "MW"
    | "KVAR"
    | "KVARH"
    | "MWH";
  [k: string]: unknown;
} & Menge1;
export type Menge1 = {
  timestamp?: string | null;
  guid?: string | null;
  wert: number;
  einheit?:
    | null
    | "ZERO"
    | "WH"
    | "KW"
    | "ANZAHL"
    | "KUBIKMETER"
    | "STUNDE"
    | "TAG"
    | "MONAT"
    | "VAR"
    | "VARH"
    | "KWHK"
    | "JAHR"
    | "KWH"
    | "MW"
    | "KVAR"
    | "KVARH"
    | "MWH";
  [k: string]: unknown;
} | null;
export type Preis = {
  wert: number;
  einheit?: null | "EUR" | "CT";
  bezugswert?:
    | null
    | "ZERO"
    | "WH"
    | "KW"
    | "ANZAHL"
    | "KUBIKMETER"
    | "STUNDE"
    | "TAG"
    | "MONAT"
    | "VAR"
    | "VARH"
    | "KWHK"
    | "JAHR"
    | "KWH"
    | "MW"
    | "KVAR"
    | "KVARH"
    | "MWH";
  status?: null | "VORLAEUFIG" | "ENDGUELTIG";
  timestamp?: string | null;
  guid?: string | null;
  [k: string]: unknown;
} & Preis1;
export type Preis1 = {
  wert: number;
  einheit?: null | "EUR" | "CT";
  bezugswert?:
    | null
    | "ZERO"
    | "WH"
    | "KW"
    | "ANZAHL"
    | "KUBIKMETER"
    | "STUNDE"
    | "TAG"
    | "MONAT"
    | "VAR"
    | "VARH"
    | "KWHK"
    | "JAHR"
    | "KWH"
    | "MW"
    | "KVAR"
    | "KVARH"
    | "MWH";
  status?: null | "VORLAEUFIG" | "ENDGUELTIG";
  timestamp?: string | null;
  guid?: string | null;
  [k: string]: unknown;
} | null;
export type Netznutzungsabrechnungsdaten1 = {
  timestamp?: string | null;
  guid?: string | null;
  artikelId?: string | null;
  artikelIdTyp?: null | "ARTIKELID" | "GRUPPENARTIKELID";
  anzahl?: number | null;
  gemeinderabatt?: number | null;
  zuschlag?: number | null;
  abschlag?: number | null;
  singulaereBetriebsmittel?: Menge1;
  preisSingulaereBetriebsmittel?: Preis1;
  [k: string]: unknown;
} | null;
export type Konfigurationsprodukt = {
  timestamp?: string | null;
  produktcode?: string | null;
  guid?: string | null;
  leistungskurvendefinition?: string | null;
  schaltzeitdefinition?: string | null;
  marktpartner?: Marktteilnehmer;
  [k: string]: unknown;
} & Konfigurationsprodukt1;
export type Marktteilnehmer = {
  boTyp?: string | null;
  versionStruktur?: string | null;
  timestamp?: string | null;
  externeReferenzen?: ExterneReferenz1[] | null;
  guid?: string | null;
  anrede?:
    | null
    | "HERR"
    | "FRAU"
    | "EHELEUTE"
    | "FIRMA"
    | "INDIVIDUELL"
    | "FAMILIE"
    | "ERBENGEMEINSCHAFT"
    | "WOHNGEMEINSCHAFT"
    | "GRUNDSTUECKGEMEINSCHAFT"
    | "DR";
  title?: string | null;
  name1?: string | null;
  name2?: string | null;
  name3?: string | null;
  gewerbekennzeichnung: boolean;
  hrnummer?: string | null;
  amtsgericht?: string | null;
  kontaktweg?: ("ANSCHREIBEN" | "TELEFONAT" | "FAX" | "E_MAIL" | "SMS")[] | null;
  umsatzsteuerId?: string | null;
  glaeubigerId?: string | null;
  eMailAdresse?: string | null;
  website?: string | null;
  geschaeftspartnerrolle?: ("LIEFERANT" | "DIENSTLEISTER" | "KUNDE" | "INTERESSENT" | "MARKTPARTNER")[] | null;
  partneradresse?: Adresse1;
  grundlageZurVerringerungDerUmlagenNachEnfg?:
    | null
    | "KUNDE_ERFUELLT_VORAUSSETZUNG"
    | "KUNDE_ERFUELLT_VORAUSSETZUNG_NICHT"
    | "KEINE_ANGABE";
  marktrolle?:
    | null
    | "NB"
    | "LF"
    | "MSB"
    | "MDL"
    | "DL"
    | "BKV"
    | "BIKO"
    | "UENB"
    | "KUNDE_SELBST_NN"
    | "MGV"
    | "EIV"
    | "RB"
    | "KUNDE"
    | "INTERESSENT"
    | "GMSB";
  rollencodenummer: string;
  rollencodetyp: "ZERO" | "GLN" | "BDEW" | "DVGW";
  makoadresse?: string | null;
  ansprechpartner?: Ansprechpartner;
  [k: string]: unknown;
} & Marktteilnehmer1;
export type Ansprechpartner = {
  boTyp?: string | null;
  versionStruktur?: string | null;
  timestamp?: string | null;
  externeReferenzen?: ExterneReferenz1[] | null;
  guid?: string | null;
  anrede?:
    | null
    | "HERR"
    | "FRAU"
    | "EHELEUTE"
    | "FIRMA"
    | "INDIVIDUELL"
    | "FAMILIE"
    | "ERBENGEMEINSCHAFT"
    | "WOHNGEMEINSCHAFT"
    | "GRUNDSTUECKGEMEINSCHAFT"
    | "DR";
  inviduelleAnrede?: string | null;
  titel?: null | "DR" | "PROF" | "PROF_DR";
  vorname?: string | null;
  nachname?: string | null;
  eMailAdresse?: string | null;
  kommentar?: string | null;
  geschaeftspartner?: Geschaeftspartner1;
  adresse?: Adresse1;
  rufnummern?: Rufnummer[] | null;
  zustaendigkeit?: Zustaendigkeit[] | null;
  [k: string]: unknown;
} & Ansprechpartner1;
export type Rufnummer = {
  nummerntyp:
    | "RUF_ZENTRALE"
    | "FAX_ZENTRALE"
    | "SAMMELRUF"
    | "SAMMELFAX"
    | "ABTEILUNGRUF"
    | "ABTEILUNGFAX"
    | "RUF_DURCHWAHL"
    | "FAX_DURCHWAHL"
    | "MOBIL_NUMMER";
  rufnummer: string;
  timestamp?: string | null;
  guid?: string | null;
  [k: string]: unknown;
} & Rufnummer1;
export type Rufnummer1 = {
  nummerntyp:
    | "RUF_ZENTRALE"
    | "FAX_ZENTRALE"
    | "SAMMELRUF"
    | "SAMMELFAX"
    | "ABTEILUNGRUF"
    | "ABTEILUNGFAX"
    | "RUF_DURCHWAHL"
    | "FAX_DURCHWAHL"
    | "MOBIL_NUMMER";
  rufnummer: string;
  timestamp?: string | null;
  guid?: string | null;
  [k: string]: unknown;
} | null;
export type Zustaendigkeit = {
  jobtitel?: string | null;
  abteilung?: string | null;
  themengebiet?: string | null;
  timestamp?: string | null;
  guid?: string | null;
  [k: string]: unknown;
} & Zustaendigkeit1;
export type Zustaendigkeit1 = {
  jobtitel?: string | null;
  abteilung?: string | null;
  themengebiet?: string | null;
  timestamp?: string | null;
  guid?: string | null;
  [k: string]: unknown;
} | null;
export type Ansprechpartner1 = {
  boTyp?: string | null;
  versionStruktur?: string | null;
  timestamp?: string | null;
  externeReferenzen?: ExterneReferenz1[] | null;
  guid?: string | null;
  anrede?:
    | null
    | "HERR"
    | "FRAU"
    | "EHELEUTE"
    | "FIRMA"
    | "INDIVIDUELL"
    | "FAMILIE"
    | "ERBENGEMEINSCHAFT"
    | "WOHNGEMEINSCHAFT"
    | "GRUNDSTUECKGEMEINSCHAFT"
    | "DR";
  inviduelleAnrede?: string | null;
  titel?: null | "DR" | "PROF" | "PROF_DR";
  vorname?: string | null;
  nachname?: string | null;
  eMailAdresse?: string | null;
  kommentar?: string | null;
  geschaeftspartner?: Geschaeftspartner1;
  adresse?: Adresse1;
  rufnummern?: Rufnummer[] | null;
  zustaendigkeit?: Zustaendigkeit[] | null;
  [k: string]: unknown;
} | null;
export type Marktteilnehmer1 = {
  boTyp?: string | null;
  versionStruktur?: string | null;
  timestamp?: string | null;
  externeReferenzen?: ExterneReferenz1[] | null;
  guid?: string | null;
  anrede?:
    | null
    | "HERR"
    | "FRAU"
    | "EHELEUTE"
    | "FIRMA"
    | "INDIVIDUELL"
    | "FAMILIE"
    | "ERBENGEMEINSCHAFT"
    | "WOHNGEMEINSCHAFT"
    | "GRUNDSTUECKGEMEINSCHAFT"
    | "DR";
  title?: string | null;
  name1?: string | null;
  name2?: string | null;
  name3?: string | null;
  gewerbekennzeichnung: boolean;
  hrnummer?: string | null;
  amtsgericht?: string | null;
  kontaktweg?: ("ANSCHREIBEN" | "TELEFONAT" | "FAX" | "E_MAIL" | "SMS")[] | null;
  umsatzsteuerId?: string | null;
  glaeubigerId?: string | null;
  eMailAdresse?: string | null;
  website?: string | null;
  geschaeftspartnerrolle?: ("LIEFERANT" | "DIENSTLEISTER" | "KUNDE" | "INTERESSENT" | "MARKTPARTNER")[] | null;
  partneradresse?: Adresse1;
  grundlageZurVerringerungDerUmlagenNachEnfg?:
    | null
    | "KUNDE_ERFUELLT_VORAUSSETZUNG"
    | "KUNDE_ERFUELLT_VORAUSSETZUNG_NICHT"
    | "KEINE_ANGABE";
  marktrolle?:
    | null
    | "NB"
    | "LF"
    | "MSB"
    | "MDL"
    | "DL"
    | "BKV"
    | "BIKO"
    | "UENB"
    | "KUNDE_SELBST_NN"
    | "MGV"
    | "EIV"
    | "RB"
    | "KUNDE"
    | "INTERESSENT"
    | "GMSB";
  rollencodenummer: string;
  rollencodetyp: "ZERO" | "GLN" | "BDEW" | "DVGW";
  makoadresse?: string | null;
  ansprechpartner?: Ansprechpartner1;
  [k: string]: unknown;
} | null;
export type Konfigurationsprodukt1 = {
  timestamp?: string | null;
  produktcode?: string | null;
  guid?: string | null;
  leistungskurvendefinition?: string | null;
  schaltzeitdefinition?: string | null;
  marktpartner?: Marktteilnehmer1;
  [k: string]: unknown;
} | null;

export interface BO4EBOMarktlokation {
  boTyp?: string | null;
  versionStruktur?: string | null;
  timestamp?: string | null;
  externeReferenzen?: ExterneReferenz[] | null;
  guid?: string | null;
  marktlokationsId: string;
  sparte: "STROM" | "GAS" | "FERNWAERME" | "NAHWAERME" | "WASSER" | "ABWASSER";
  energierichtung?: null | "AUSSP" | "EINSP";
  bilanzierungsmethode?: null | "RLM" | "SLP" | "TLP_GEMEINSAM" | "TLP_GETRENNT" | "PAUSCHAL" | "IMS";
  verbrauchsart?: null | "KL" | "KLW" | "KLWS" | "W" | "WS";
  unterbrechbar?: boolean | null;
  netzebene?:
    | null
    | "NSP"
    | "MSP"
    | "HSP"
    | "HSS"
    | "MSP_NSP_UMSP"
    | "HSP_MSP_UMSP"
    | "HSS_HSP_UMSP"
    | "HD"
    | "MD"
    | "ND";
  netzbetreiberCodeNr?: string | null;
  gebietTyp?:
    | null
    | "REGELZONE"
    | "MARKTGEBIET"
    | "BILANZIERUNGSGEBIET"
    | "VERTEILNETZ"
    | "TRANSPORTNETZ"
    | "REGIONALNETZ"
    | "AREALNETZ"
    | "GRUNDVERSORGUNGSGEBIET"
    | "VERSORGUNGSGEBIET";
  netzgebietNr?: string | null;
  bilanzierungsgebiet?: string | null;
  grundversorgerCodeNr?: string | null;
  gasqualitaet?: null | "ZERO" | "H_GAS" | "HGAS" | "L_GAS" | "LGAS";
  endkunde?: Geschaeftspartner;
  lokationsadresse?: Adresse1;
  geoadresse?: Geokoordinaten;
  katasterinformation?: Katasteradresse;
  marktrollen?: MarktpartnerDetails[] | null;
  regelzone?: string | null;
  marktgebiet?: string | null;
  zeitreihentyp?: null | "EGS" | "LGS" | "NZR" | "SES" | "SLS" | "TES" | "TLS" | "SLS_TLS" | "SES_TES";
  zaehlwerke?: Zaehlwerk[] | null;
  zaehlwerkeBeteiligteMarktrolle?: Zaehlwerk1[] | null;
  verbrauchsmenge?: Verbrauch[] | null;
  messlokationen?: Messlokation[] | null;
  zugehoerigeMesslokationen?: Messlokationszuordnung[] | null;
  messtechnischeEinordnung?: null | "IMS" | "KME_MME" | "KEINE_MESSUNG";
  netznutzungsabrechnungsdaten?: Netznutzungsabrechnungsdaten[] | null;
  sperrstatus?: null | "ENTSPERRT" | "GESPERRT";
  messprodukte?: Messprodukt1[] | null;
  konfigurationsprodukte?: Konfigurationsprodukt[] | null;
  [k: string]: unknown;
}
