/* tslint:disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

export type ExterneReferenz = {
  exRefName?: string | null;
  exRefWert?: string | null;
  timestamp?: string | null;
  guid?: string | null;
  [k: string]: unknown;
} & ExterneReferenz1;
export type ExterneReferenz1 = {
  exRefName?: string | null;
  exRefWert?: string | null;
  timestamp?: string | null;
  guid?: string | null;
  [k: string]: unknown;
} | null;
export type Fehler = {
  typ: "SYNTAX" | "VERARBEITUNG";
  fehlerDetails?: FehlerDetail[] | null;
  timestamp?: string | null;
  guid?: string | null;
  [k: string]: unknown;
} & Fehler1;
export type FehlerDetail = {
  timestamp?: string | null;
  guid?: string | null;
  code:
    | "ID_UNBEKANNT"
    | "ABSENDER_NICHT_ZUGEORDNET"
    | "EMPFAENGER_NICHT_ZUGEORDNET"
    | "GERAET_UNBEKANNT"
    | "OBIS_UNBEKANNT"
    | "REFERENZIERUNG_FEHLERHAFT"
    | "TUPEL_UNBEKANNT"
    | "ABSENDER_TUPEL_NICHT_ZUGEORDNET"
    | "EMPFAENGER_TUPEL_NICHT_ZUGEORDNET"
    | "VORKOMMA_ZU_VIELE_STELLEN"
    | "ZEITREIHE_UNVOLLSTAENDIG"
    | "REFERENZIERTES_TUPEL_UNBEKANNT"
    | "MARKTLOKATION_UNBEKANNT"
    | "MESSLOKATION_UNBEKANNT"
    | "MELDEPUNKT_NICHT_MEHR_IM_NETZ"
    | "ERFORDERLICHE_ANGABE_FEHLT"
    | "GESCHAEFTSVORFALL_ZURUECKGEWIESEN"
    | "ZEITINTERVALL_NEGATIV"
    | "FORMAT_NICHT_EINGEHALTEN"
    | "GESCHAEFTSVORFALL_ABSENDER"
    | "KONFIGURATIONSID_UNBEKANNT"
    | "SEGMENTWIEDERHOLUNG_UEBERSCHRITTEN"
    | "ANZAHLCODES_UEBERSCHRITTEN"
    | "ZEITANGABE_UNPLAUSIBEL";
  beschreibung?: string | null;
  ursache?: FehlerUrsache;
  [k: string]: unknown;
} & FehlerDetail1;
export type FehlerUrsache = {
  dokument?: string | null;
  nachricht?: string | null;
  transaktion?: string | null;
  gruppe?: string | null;
  segment?: string | null;
  beschreibung?: string | null;
  timestamp?: string | null;
  guid?: string | null;
  [k: string]: unknown;
} & FehlerUrsache1;
export type FehlerUrsache1 = {
  dokument?: string | null;
  nachricht?: string | null;
  transaktion?: string | null;
  gruppe?: string | null;
  segment?: string | null;
  beschreibung?: string | null;
  timestamp?: string | null;
  guid?: string | null;
  [k: string]: unknown;
} | null;
export type FehlerDetail1 = {
  timestamp?: string | null;
  guid?: string | null;
  code:
    | "ID_UNBEKANNT"
    | "ABSENDER_NICHT_ZUGEORDNET"
    | "EMPFAENGER_NICHT_ZUGEORDNET"
    | "GERAET_UNBEKANNT"
    | "OBIS_UNBEKANNT"
    | "REFERENZIERUNG_FEHLERHAFT"
    | "TUPEL_UNBEKANNT"
    | "ABSENDER_TUPEL_NICHT_ZUGEORDNET"
    | "EMPFAENGER_TUPEL_NICHT_ZUGEORDNET"
    | "VORKOMMA_ZU_VIELE_STELLEN"
    | "ZEITREIHE_UNVOLLSTAENDIG"
    | "REFERENZIERTES_TUPEL_UNBEKANNT"
    | "MARKTLOKATION_UNBEKANNT"
    | "MESSLOKATION_UNBEKANNT"
    | "MELDEPUNKT_NICHT_MEHR_IM_NETZ"
    | "ERFORDERLICHE_ANGABE_FEHLT"
    | "GESCHAEFTSVORFALL_ZURUECKGEWIESEN"
    | "ZEITINTERVALL_NEGATIV"
    | "FORMAT_NICHT_EINGEHALTEN"
    | "GESCHAEFTSVORFALL_ABSENDER"
    | "KONFIGURATIONSID_UNBEKANNT"
    | "SEGMENTWIEDERHOLUNG_UEBERSCHRITTEN"
    | "ANZAHLCODES_UEBERSCHRITTEN"
    | "ZEITANGABE_UNPLAUSIBEL";
  beschreibung?: string | null;
  ursache?: FehlerUrsache1;
  [k: string]: unknown;
} | null;
export type Fehler1 = {
  typ: "SYNTAX" | "VERARBEITUNG";
  fehlerDetails?: FehlerDetail[] | null;
  timestamp?: string | null;
  guid?: string | null;
  [k: string]: unknown;
} | null;

export interface BO4EBOStatusbericht {
  boTyp?: string | null;
  versionStruktur?: string | null;
  timestamp?: string | null;
  externeReferenzen?: ExterneReferenz[] | null;
  guid?: string | null;
  status: "ERFOLGREICH" | "FEHLER";
  pruefgegenstand?: string | null;
  datumPruefung: string;
  fehler?: Fehler;
  [k: string]: unknown;
}
