/* eslint-disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

export type ExterneReferenz = {
  exRefName: string | null;
  exRefWert: string | null;
  timestamp?: string | null;
  guid?: string | null;
  [k: string]: unknown;
} & ExterneReferenz1;
export type ExterneReferenz1 = {
  exRefName: string | null;
  exRefWert: string | null;
  timestamp?: string | null;
  guid?: string | null;
  [k: string]: unknown;
} | null;
export type Menge = {
  timestamp?: string | null;
  guid?: string | null;
  wert: number;
  einheit:
    | null
    | "ZERO"
    | "WH"
    | "KW"
    | "ANZAHL"
    | "KUBIKMETER"
    | "STUNDE"
    | "TAG"
    | "MONAT"
    | "VAR"
    | "VARH"
    | "KWHK"
    | "W_M2"
    | "M_S"
    | "STUECK"
    | "JAHR"
    | "KWH"
    | "MW"
    | "KVAR"
    | "KVARH"
    | "MWH";
  [k: string]: unknown;
} & Menge1;
export type Menge1 = {
  timestamp?: string | null;
  guid?: string | null;
  wert: number;
  einheit:
    | null
    | "ZERO"
    | "WH"
    | "KW"
    | "ANZAHL"
    | "KUBIKMETER"
    | "STUNDE"
    | "TAG"
    | "MONAT"
    | "VAR"
    | "VARH"
    | "KWHK"
    | "W_M2"
    | "M_S"
    | "STUECK"
    | "JAHR"
    | "KWH"
    | "MW"
    | "KVAR"
    | "KVARH"
    | "MWH";
  [k: string]: unknown;
} | null;
export type Verwendungszweck = {
  marktrolle:
    | "NB"
    | "LF"
    | "MSB"
    | "MDL"
    | "DL"
    | "BKV"
    | "BIKO"
    | "UENB"
    | "KUNDE_SELBST_NN"
    | "MGV"
    | "EIV"
    | "RB"
    | "KUNDE"
    | "INTERESSENT"
    | "GMSB"
    | "AMSB";
  zweck:
    | (
        | "NETZNUTZUNGSABRECHNUNG"
        | "BILANZKREISABRECHNUNG"
        | "MEHRMINDERMENGENABRECHNUNG"
        | "ENDKUNDENABRECHNUNG"
        | "BLINDARBEITABRECHNUNG_BETRIEBSFUEHRUNG"
        | "UEBERMITTLUNG_AN_DAS_HKNR"
        | "ERMITTLUNG_AUSGEGLICHENHEIT_BILANZKREIS"
        | "SELBSTVERBRAUCH"
        | "ES_LIEGT_KEIN_VERWENDUNGSZWECK_VOR"
        | "KEINE_DATENLIEFERUNG_AN_MARKTROLLE"
      )[]
    | null;
  timestamp?: string | null;
  guid?: string | null;
  [k: string]: unknown;
} & Verwendungszweck1;
export type Verwendungszweck1 = {
  marktrolle:
    | "NB"
    | "LF"
    | "MSB"
    | "MDL"
    | "DL"
    | "BKV"
    | "BIKO"
    | "UENB"
    | "KUNDE_SELBST_NN"
    | "MGV"
    | "EIV"
    | "RB"
    | "KUNDE"
    | "INTERESSENT"
    | "GMSB"
    | "AMSB";
  zweck:
    | (
        | "NETZNUTZUNGSABRECHNUNG"
        | "BILANZKREISABRECHNUNG"
        | "MEHRMINDERMENGENABRECHNUNG"
        | "ENDKUNDENABRECHNUNG"
        | "BLINDARBEITABRECHNUNG_BETRIEBSFUEHRUNG"
        | "UEBERMITTLUNG_AN_DAS_HKNR"
        | "ERMITTLUNG_AUSGEGLICHENHEIT_BILANZKREIS"
        | "SELBSTVERBRAUCH"
        | "ES_LIEGT_KEIN_VERWENDUNGSZWECK_VOR"
        | "KEINE_DATENLIEFERUNG_AN_MARKTROLLE"
      )[]
    | null;
  timestamp?: string | null;
  guid?: string | null;
  [k: string]: unknown;
} | null;
export type Konfigurationsprodukt = {
  timestamp?: string | null;
  produktcode: string | null;
  guid?: string | null;
  leistungskurvendefinition: string | null;
  schaltzeitdefinition: string | null;
  auftraggebenderMarktpartner: Marktteilnehmer;
  empfangendeMarktrolle:
    | null
    | "NB"
    | "LF"
    | "MSB"
    | "MDL"
    | "DL"
    | "BKV"
    | "BIKO"
    | "UENB"
    | "KUNDE_SELBST_NN"
    | "MGV"
    | "EIV"
    | "RB"
    | "KUNDE"
    | "INTERESSENT"
    | "GMSB"
    | "AMSB";
  [k: string]: unknown;
} & Konfigurationsprodukt1;
export type Marktteilnehmer = {
  boTyp: string | null;
  versionStruktur: string | null;
  timestamp?: string | null;
  externeReferenzen: ExterneReferenz[] | null;
  guid?: string | null;
  anrede:
    | null
    | "HERR"
    | "FRAU"
    | "EHELEUTE"
    | "FIRMA"
    | "INDIVIDUELL"
    | "FAMILIE"
    | "ERBENGEMEINSCHAFT"
    | "WOHNGEMEINSCHAFT"
    | "GRUNDSTUECKGEMEINSCHAFT"
    | "DR";
  title: string | null;
  name1: string | null;
  name2: string | null;
  name3: string | null;
  gewerbekennzeichnung: boolean;
  hrnummer: string | null;
  amtsgericht: string | null;
  kontaktweg: ("ANSCHREIBEN" | "TELEFONAT" | "FAX" | "E_MAIL" | "SMS")[] | null;
  umsatzsteuerId: string | null;
  glaeubigerId: string | null;
  eMailAdresse: string | null;
  website: string | null;
  geschaeftspartnerrolle: ("LIEFERANT" | "DIENSTLEISTER" | "KUNDE" | "INTERESSENT" | "MARKTPARTNER")[] | null;
  partneradresse: Adresse;
  grundlageZurVerringerungDerUmlagenNachEnfg:
    null | "KUNDE_ERFUELLT_VORAUSSETZUNG" | "KUNDE_ERFUELLT_VORAUSSETZUNG_NICHT" | "KEINE_ANGABE";
  gruendeDerPrivilegierungNachEnFG:
    | (
        | "STROMSPEICHER_UND_VERLUSTENERGIE"
        | "ELEKTRISCH_ANGETRIEBENE_WAERMEPUMPEN"
        | "UMLAGEERHEBUNG_BEI_ANLAGEN_ZUR_VERSTROMUNG_VON_KUPPELGASEN"
        | "HERSTELLUNG_VON_GRUENEN_WASSERSTOFF"
        | "STROMKOSTENINTENSIVE_UNTERNEHMEN"
        | "HERSTELLUNG_VON_WASSERSTOFF_IN_STROMKOSTENINTENSIVEN_UNTERNEHMEN"
        | "SCHIENENBAHNEN"
        | "ELEKTRISCHE_BETRIEBENE_BUSSEN_IM_LINIENVERKEHR"
        | "LANDSTROMANLAGEN"
      )[]
    | null;
  bankverbindung: Bankverbindung;
  steuernummer: string | null;
  erreichbarkeit: Erreichbarkeit;
  marktrolle:
    | null
    | "NB"
    | "LF"
    | "MSB"
    | "MDL"
    | "DL"
    | "BKV"
    | "BIKO"
    | "UENB"
    | "KUNDE_SELBST_NN"
    | "MGV"
    | "EIV"
    | "RB"
    | "KUNDE"
    | "INTERESSENT"
    | "GMSB"
    | "AMSB";
  rollencodenummer: string | null;
  rollencodetyp: null | "ZERO" | "GLN" | "BDEW" | "DVGW";
  makoadresse: string | null;
  ansprechpartner: Ansprechpartner;
  rolle: null | "ANDERE_PARTEI" | "EMPFAENGER";
  gueltigkeitszeitraum?: Zeitraum;
  qualitaet?:
    null | "VOLLSTAENDIG" | "INFORMATIV" | "IM_SYSTEM_VORHANDEN" | "ERWARTET" | "VORLAEUFIG" | "UNVOLLSTAENDIG";
  [k: string]: unknown;
} & Marktteilnehmer1;
export type Adresse = {
  timestamp?: string | null;
  guid?: string | null;
  postleitzahl: string | null;
  ort: string | null;
  strasse: string | null;
  hausnummer: string | null;
  postfach: string | null;
  adresszusatz: string | null;
  coErgaenzung: string | null;
  landescode:
    | null
    | "AC"
    | "AD"
    | "AE"
    | "AF"
    | "AG"
    | "AI"
    | "AL"
    | "AM"
    | "AN"
    | "AO"
    | "AQ"
    | "AR"
    | "AS"
    | "AT"
    | "AU"
    | "AW"
    | "AX"
    | "AZ"
    | "BA"
    | "BB"
    | "BD"
    | "BE"
    | "BF"
    | "BG"
    | "BH"
    | "BI"
    | "BJ"
    | "BL"
    | "BM"
    | "BN"
    | "BO"
    | "BQ"
    | "BR"
    | "BS"
    | "BT"
    | "BU"
    | "BV"
    | "BW"
    | "BY"
    | "BZ"
    | "CA"
    | "CC"
    | "CD"
    | "CF"
    | "CG"
    | "CH"
    | "CI"
    | "CK"
    | "CL"
    | "CM"
    | "CN"
    | "CO"
    | "CP"
    | "CR"
    | "CS"
    | "CU"
    | "CV"
    | "CW"
    | "CX"
    | "CY"
    | "CZ"
    | "DE"
    | "DG"
    | "DJ"
    | "DK"
    | "DM"
    | "DO"
    | "DZ"
    | "EA"
    | "EC"
    | "EE"
    | "EG"
    | "EH"
    | "ER"
    | "ES"
    | "ET"
    | "EU"
    | "FI"
    | "FJ"
    | "FK"
    | "FM"
    | "FO"
    | "FR"
    | "FX"
    | "GA"
    | "GB"
    | "GD"
    | "GE"
    | "GF"
    | "GG"
    | "GH"
    | "GI"
    | "GL"
    | "GM"
    | "GN"
    | "GP"
    | "GQ"
    | "GR"
    | "GS"
    | "GT"
    | "GU"
    | "GW"
    | "GY"
    | "HK"
    | "HM"
    | "HN"
    | "HR"
    | "HT"
    | "HU"
    | "IC"
    | "ID"
    | "IE"
    | "IL"
    | "IM"
    | "IN"
    | "IO"
    | "IQ"
    | "IR"
    | "IS"
    | "IT"
    | "JE"
    | "JM"
    | "JO"
    | "JP"
    | "KE"
    | "KG"
    | "KH"
    | "KI"
    | "KM"
    | "KN"
    | "KP"
    | "KR"
    | "KW"
    | "KY"
    | "KZ"
    | "LA"
    | "LB"
    | "LC"
    | "LI"
    | "LK"
    | "LR"
    | "LS"
    | "LT"
    | "LU"
    | "LV"
    | "LY"
    | "MA"
    | "MC"
    | "MD"
    | "ME"
    | "MF"
    | "MG"
    | "MH"
    | "MK"
    | "ML"
    | "MM"
    | "MN"
    | "MO"
    | "MP"
    | "MQ"
    | "MR"
    | "MS"
    | "MT"
    | "MU"
    | "MV"
    | "MW"
    | "MX"
    | "MY"
    | "MZ"
    | "NA"
    | "NC"
    | "NE"
    | "NF"
    | "NG"
    | "NI"
    | "NL"
    | "NO"
    | "NP"
    | "NR"
    | "NT"
    | "NU"
    | "NZ"
    | "OM"
    | "PA"
    | "PE"
    | "PF"
    | "PG"
    | "PH"
    | "PK"
    | "PL"
    | "PM"
    | "PN"
    | "PR"
    | "PS"
    | "PT"
    | "PW"
    | "PY"
    | "QA"
    | "RE"
    | "RO"
    | "RS"
    | "RU"
    | "RW"
    | "SA"
    | "SB"
    | "SC"
    | "SD"
    | "SE"
    | "SF"
    | "SG"
    | "SH"
    | "SI"
    | "SJ"
    | "SK"
    | "SL"
    | "SM"
    | "SN"
    | "SO"
    | "SR"
    | "SS"
    | "ST"
    | "SU"
    | "SV"
    | "SX"
    | "SY"
    | "SZ"
    | "TA"
    | "TC"
    | "TD"
    | "TF"
    | "TG"
    | "TJ"
    | "TK"
    | "TL"
    | "TM"
    | "TN"
    | "TO"
    | "TP"
    | "TR"
    | "TT"
    | "TV"
    | "TW"
    | "TZ"
    | "UA"
    | "UG"
    | "UK"
    | "UM"
    | "US"
    | "UY"
    | "UZ"
    | "VA"
    | "VC"
    | "VE"
    | "VG"
    | "VI"
    | "VN"
    | "VU"
    | "WF"
    | "WS"
    | "XK"
    | "YE"
    | "YT"
    | "YU"
    | "ZA"
    | "ZM"
    | "ZR"
    | "ZW";
  ortsteil?: string | null;
  [k: string]: unknown;
} & Adresse1;
export type Adresse1 = {
  timestamp?: string | null;
  guid?: string | null;
  postleitzahl: string | null;
  ort: string | null;
  strasse: string | null;
  hausnummer: string | null;
  postfach: string | null;
  adresszusatz: string | null;
  coErgaenzung: string | null;
  landescode:
    | null
    | "AC"
    | "AD"
    | "AE"
    | "AF"
    | "AG"
    | "AI"
    | "AL"
    | "AM"
    | "AN"
    | "AO"
    | "AQ"
    | "AR"
    | "AS"
    | "AT"
    | "AU"
    | "AW"
    | "AX"
    | "AZ"
    | "BA"
    | "BB"
    | "BD"
    | "BE"
    | "BF"
    | "BG"
    | "BH"
    | "BI"
    | "BJ"
    | "BL"
    | "BM"
    | "BN"
    | "BO"
    | "BQ"
    | "BR"
    | "BS"
    | "BT"
    | "BU"
    | "BV"
    | "BW"
    | "BY"
    | "BZ"
    | "CA"
    | "CC"
    | "CD"
    | "CF"
    | "CG"
    | "CH"
    | "CI"
    | "CK"
    | "CL"
    | "CM"
    | "CN"
    | "CO"
    | "CP"
    | "CR"
    | "CS"
    | "CU"
    | "CV"
    | "CW"
    | "CX"
    | "CY"
    | "CZ"
    | "DE"
    | "DG"
    | "DJ"
    | "DK"
    | "DM"
    | "DO"
    | "DZ"
    | "EA"
    | "EC"
    | "EE"
    | "EG"
    | "EH"
    | "ER"
    | "ES"
    | "ET"
    | "EU"
    | "FI"
    | "FJ"
    | "FK"
    | "FM"
    | "FO"
    | "FR"
    | "FX"
    | "GA"
    | "GB"
    | "GD"
    | "GE"
    | "GF"
    | "GG"
    | "GH"
    | "GI"
    | "GL"
    | "GM"
    | "GN"
    | "GP"
    | "GQ"
    | "GR"
    | "GS"
    | "GT"
    | "GU"
    | "GW"
    | "GY"
    | "HK"
    | "HM"
    | "HN"
    | "HR"
    | "HT"
    | "HU"
    | "IC"
    | "ID"
    | "IE"
    | "IL"
    | "IM"
    | "IN"
    | "IO"
    | "IQ"
    | "IR"
    | "IS"
    | "IT"
    | "JE"
    | "JM"
    | "JO"
    | "JP"
    | "KE"
    | "KG"
    | "KH"
    | "KI"
    | "KM"
    | "KN"
    | "KP"
    | "KR"
    | "KW"
    | "KY"
    | "KZ"
    | "LA"
    | "LB"
    | "LC"
    | "LI"
    | "LK"
    | "LR"
    | "LS"
    | "LT"
    | "LU"
    | "LV"
    | "LY"
    | "MA"
    | "MC"
    | "MD"
    | "ME"
    | "MF"
    | "MG"
    | "MH"
    | "MK"
    | "ML"
    | "MM"
    | "MN"
    | "MO"
    | "MP"
    | "MQ"
    | "MR"
    | "MS"
    | "MT"
    | "MU"
    | "MV"
    | "MW"
    | "MX"
    | "MY"
    | "MZ"
    | "NA"
    | "NC"
    | "NE"
    | "NF"
    | "NG"
    | "NI"
    | "NL"
    | "NO"
    | "NP"
    | "NR"
    | "NT"
    | "NU"
    | "NZ"
    | "OM"
    | "PA"
    | "PE"
    | "PF"
    | "PG"
    | "PH"
    | "PK"
    | "PL"
    | "PM"
    | "PN"
    | "PR"
    | "PS"
    | "PT"
    | "PW"
    | "PY"
    | "QA"
    | "RE"
    | "RO"
    | "RS"
    | "RU"
    | "RW"
    | "SA"
    | "SB"
    | "SC"
    | "SD"
    | "SE"
    | "SF"
    | "SG"
    | "SH"
    | "SI"
    | "SJ"
    | "SK"
    | "SL"
    | "SM"
    | "SN"
    | "SO"
    | "SR"
    | "SS"
    | "ST"
    | "SU"
    | "SV"
    | "SX"
    | "SY"
    | "SZ"
    | "TA"
    | "TC"
    | "TD"
    | "TF"
    | "TG"
    | "TJ"
    | "TK"
    | "TL"
    | "TM"
    | "TN"
    | "TO"
    | "TP"
    | "TR"
    | "TT"
    | "TV"
    | "TW"
    | "TZ"
    | "UA"
    | "UG"
    | "UK"
    | "UM"
    | "US"
    | "UY"
    | "UZ"
    | "VA"
    | "VC"
    | "VE"
    | "VG"
    | "VI"
    | "VN"
    | "VU"
    | "WF"
    | "WS"
    | "XK"
    | "YE"
    | "YT"
    | "YU"
    | "ZA"
    | "ZM"
    | "ZR"
    | "ZW";
  ortsteil?: string | null;
  [k: string]: unknown;
} | null;
export type Bankverbindung = {
  timestamp?: string | null;
  guid?: string | null;
  iban: string | null;
  kontoinhaber: string | null;
  bankkennung: string | null;
  bankname: string | null;
  [k: string]: unknown;
} & Bankverbindung1;
export type Bankverbindung1 = {
  timestamp?: string | null;
  guid?: string | null;
  iban: string | null;
  kontoinhaber: string | null;
  bankkennung: string | null;
  bankname: string | null;
  [k: string]: unknown;
} | null;
export type Erreichbarkeit = {
  timestamp?: string | null;
  guid?: string | null;
  montagErreichbarkeit: Zeitfenster;
  dienstagErreichbarkeit: Zeitfenster;
  mittwochErreichbarkeit: Zeitfenster;
  donnerstagErreichbarkeit: Zeitfenster;
  freitagErreichbarkeit: Zeitfenster;
  mittagspause: Zeitfenster;
  [k: string]: unknown;
} & Erreichbarkeit1;
export type Zeitfenster = {
  timestamp?: string | null;
  guid?: string | null;
  startzeit: string | null;
  endzeit: string | null;
  [k: string]: unknown;
} & Zeitfenster1;
export type Zeitfenster1 = {
  timestamp?: string | null;
  guid?: string | null;
  startzeit: string | null;
  endzeit: string | null;
  [k: string]: unknown;
} | null;
export type Erreichbarkeit1 = {
  timestamp?: string | null;
  guid?: string | null;
  montagErreichbarkeit: Zeitfenster;
  dienstagErreichbarkeit: Zeitfenster;
  mittwochErreichbarkeit: Zeitfenster;
  donnerstagErreichbarkeit: Zeitfenster;
  freitagErreichbarkeit: Zeitfenster;
  mittagspause: Zeitfenster;
  [k: string]: unknown;
} | null;
export type Ansprechpartner = {
  boTyp: string | null;
  versionStruktur: string | null;
  timestamp?: string | null;
  externeReferenzen: ExterneReferenz[] | null;
  guid?: string | null;
  anrede:
    | null
    | "HERR"
    | "FRAU"
    | "EHELEUTE"
    | "FIRMA"
    | "INDIVIDUELL"
    | "FAMILIE"
    | "ERBENGEMEINSCHAFT"
    | "WOHNGEMEINSCHAFT"
    | "GRUNDSTUECKGEMEINSCHAFT"
    | "DR";
  inviduelleAnrede: string | null;
  titel: null | "DR" | "PROF" | "PROF_DR" | "DIPLOM_INF";
  vorname: string | null;
  nachname: string | null;
  eMailAdresse: string | null;
  kommentar: string | null;
  geschaeftspartner: Geschaeftspartner;
  adresse: Adresse;
  rufnummern: Rufnummer[] | null;
  zustaendigkeit: Zustaendigkeit[] | null;
  gewerbekennzeichnung: boolean | null;
  unternehmensart:
    | null
    | "LIEFERANT"
    | "NETZBETREIBER"
    | "MESSSTELLENBETREIBER"
    | "ÜBERTRAGUNGSNETZBETREIBER"
    | "BILANZKOORDINATOR"
    | "BILANZKREISVERANTWORTLICHER"
    | "ENERGIESERVICEANBIETER";
  gueltigkeitszeitraum?: Zeitraum;
  qualitaet?:
    null | "VOLLSTAENDIG" | "INFORMATIV" | "IM_SYSTEM_VORHANDEN" | "ERWARTET" | "VORLAEUFIG" | "UNVOLLSTAENDIG";
  [k: string]: unknown;
} & Ansprechpartner1;
export type Geschaeftspartner = {
  boTyp: string | null;
  versionStruktur: string | null;
  timestamp?: string | null;
  externeReferenzen: ExterneReferenz[] | null;
  guid?: string | null;
  anrede:
    | null
    | "HERR"
    | "FRAU"
    | "EHELEUTE"
    | "FIRMA"
    | "INDIVIDUELL"
    | "FAMILIE"
    | "ERBENGEMEINSCHAFT"
    | "WOHNGEMEINSCHAFT"
    | "GRUNDSTUECKGEMEINSCHAFT"
    | "DR";
  title: string | null;
  name1: string | null;
  name2: string | null;
  name3: string | null;
  gewerbekennzeichnung: boolean;
  hrnummer: string | null;
  amtsgericht: string | null;
  kontaktweg: ("ANSCHREIBEN" | "TELEFONAT" | "FAX" | "E_MAIL" | "SMS")[] | null;
  umsatzsteuerId: string | null;
  glaeubigerId: string | null;
  eMailAdresse: string | null;
  website: string | null;
  geschaeftspartnerrolle: ("LIEFERANT" | "DIENSTLEISTER" | "KUNDE" | "INTERESSENT" | "MARKTPARTNER")[] | null;
  partneradresse: Adresse;
  grundlageZurVerringerungDerUmlagenNachEnfg:
    null | "KUNDE_ERFUELLT_VORAUSSETZUNG" | "KUNDE_ERFUELLT_VORAUSSETZUNG_NICHT" | "KEINE_ANGABE";
  gruendeDerPrivilegierungNachEnFG:
    | (
        | "STROMSPEICHER_UND_VERLUSTENERGIE"
        | "ELEKTRISCH_ANGETRIEBENE_WAERMEPUMPEN"
        | "UMLAGEERHEBUNG_BEI_ANLAGEN_ZUR_VERSTROMUNG_VON_KUPPELGASEN"
        | "HERSTELLUNG_VON_GRUENEN_WASSERSTOFF"
        | "STROMKOSTENINTENSIVE_UNTERNEHMEN"
        | "HERSTELLUNG_VON_WASSERSTOFF_IN_STROMKOSTENINTENSIVEN_UNTERNEHMEN"
        | "SCHIENENBAHNEN"
        | "ELEKTRISCHE_BETRIEBENE_BUSSEN_IM_LINIENVERKEHR"
        | "LANDSTROMANLAGEN"
      )[]
    | null;
  bankverbindung: Bankverbindung;
  steuernummer: string | null;
  erreichbarkeit: Erreichbarkeit;
  gueltigkeitszeitraum?: Zeitraum;
  qualitaet?:
    null | "VOLLSTAENDIG" | "INFORMATIV" | "IM_SYSTEM_VORHANDEN" | "ERWARTET" | "VORLAEUFIG" | "UNVOLLSTAENDIG";
  [k: string]: unknown;
} & Geschaeftspartner1;
export type Zeitraum = {
  einheit:
    | null
    | "SEKUNDE"
    | "MINUTE"
    | "STUNDE"
    | "VIERTEL_STUNDE"
    | "TAG"
    | "WOCHE"
    | "MONAT"
    | "QUARTAL"
    | "HALBJAHR"
    | "JAHR";
  dauer: number | null;
  startdatum: string | null;
  enddatum: string | null;
  startzeitpunkt: string | null;
  endzeitpunkt: string | null;
  timestamp?: string | null;
  guid?: string | null;
  [k: string]: unknown;
} & Zeitraum1;
export type Zeitraum1 = {
  einheit:
    | null
    | "SEKUNDE"
    | "MINUTE"
    | "STUNDE"
    | "VIERTEL_STUNDE"
    | "TAG"
    | "WOCHE"
    | "MONAT"
    | "QUARTAL"
    | "HALBJAHR"
    | "JAHR";
  dauer: number | null;
  startdatum: string | null;
  enddatum: string | null;
  startzeitpunkt: string | null;
  endzeitpunkt: string | null;
  timestamp?: string | null;
  guid?: string | null;
  [k: string]: unknown;
} | null;
export type Geschaeftspartner1 = {
  boTyp: string | null;
  versionStruktur: string | null;
  timestamp?: string | null;
  externeReferenzen: ExterneReferenz[] | null;
  guid?: string | null;
  anrede:
    | null
    | "HERR"
    | "FRAU"
    | "EHELEUTE"
    | "FIRMA"
    | "INDIVIDUELL"
    | "FAMILIE"
    | "ERBENGEMEINSCHAFT"
    | "WOHNGEMEINSCHAFT"
    | "GRUNDSTUECKGEMEINSCHAFT"
    | "DR";
  title: string | null;
  name1: string | null;
  name2: string | null;
  name3: string | null;
  gewerbekennzeichnung: boolean;
  hrnummer: string | null;
  amtsgericht: string | null;
  kontaktweg: ("ANSCHREIBEN" | "TELEFONAT" | "FAX" | "E_MAIL" | "SMS")[] | null;
  umsatzsteuerId: string | null;
  glaeubigerId: string | null;
  eMailAdresse: string | null;
  website: string | null;
  geschaeftspartnerrolle: ("LIEFERANT" | "DIENSTLEISTER" | "KUNDE" | "INTERESSENT" | "MARKTPARTNER")[] | null;
  partneradresse: Adresse;
  grundlageZurVerringerungDerUmlagenNachEnfg:
    null | "KUNDE_ERFUELLT_VORAUSSETZUNG" | "KUNDE_ERFUELLT_VORAUSSETZUNG_NICHT" | "KEINE_ANGABE";
  gruendeDerPrivilegierungNachEnFG:
    | (
        | "STROMSPEICHER_UND_VERLUSTENERGIE"
        | "ELEKTRISCH_ANGETRIEBENE_WAERMEPUMPEN"
        | "UMLAGEERHEBUNG_BEI_ANLAGEN_ZUR_VERSTROMUNG_VON_KUPPELGASEN"
        | "HERSTELLUNG_VON_GRUENEN_WASSERSTOFF"
        | "STROMKOSTENINTENSIVE_UNTERNEHMEN"
        | "HERSTELLUNG_VON_WASSERSTOFF_IN_STROMKOSTENINTENSIVEN_UNTERNEHMEN"
        | "SCHIENENBAHNEN"
        | "ELEKTRISCHE_BETRIEBENE_BUSSEN_IM_LINIENVERKEHR"
        | "LANDSTROMANLAGEN"
      )[]
    | null;
  bankverbindung: Bankverbindung;
  steuernummer: string | null;
  erreichbarkeit: Erreichbarkeit;
  gueltigkeitszeitraum?: Zeitraum;
  qualitaet?:
    null | "VOLLSTAENDIG" | "INFORMATIV" | "IM_SYSTEM_VORHANDEN" | "ERWARTET" | "VORLAEUFIG" | "UNVOLLSTAENDIG";
  [k: string]: unknown;
} | null;
export type Rufnummer = {
  nummerntyp:
    | null
    | "RUF_ZENTRALE"
    | "FAX_ZENTRALE"
    | "SAMMELRUF"
    | "SAMMELFAX"
    | "ABTEILUNGRUF"
    | "ABTEILUNGFAX"
    | "RUF_DURCHWAHL"
    | "FAX_DURCHWAHL"
    | "MOBIL_NUMMER";
  rufnummer: string | null;
  timestamp?: string | null;
  guid?: string | null;
  [k: string]: unknown;
} & Rufnummer1;
export type Rufnummer1 = {
  nummerntyp:
    | null
    | "RUF_ZENTRALE"
    | "FAX_ZENTRALE"
    | "SAMMELRUF"
    | "SAMMELFAX"
    | "ABTEILUNGRUF"
    | "ABTEILUNGFAX"
    | "RUF_DURCHWAHL"
    | "FAX_DURCHWAHL"
    | "MOBIL_NUMMER";
  rufnummer: string | null;
  timestamp?: string | null;
  guid?: string | null;
  [k: string]: unknown;
} | null;
export type Zustaendigkeit = {
  jobtitel: string | null;
  abteilung: string | null;
  themengebiet: string | null;
  timestamp?: string | null;
  guid?: string | null;
  [k: string]: unknown;
} & Zustaendigkeit1;
export type Zustaendigkeit1 = {
  jobtitel: string | null;
  abteilung: string | null;
  themengebiet: string | null;
  timestamp?: string | null;
  guid?: string | null;
  [k: string]: unknown;
} | null;
export type Ansprechpartner1 = {
  boTyp: string | null;
  versionStruktur: string | null;
  timestamp?: string | null;
  externeReferenzen: ExterneReferenz[] | null;
  guid?: string | null;
  anrede:
    | null
    | "HERR"
    | "FRAU"
    | "EHELEUTE"
    | "FIRMA"
    | "INDIVIDUELL"
    | "FAMILIE"
    | "ERBENGEMEINSCHAFT"
    | "WOHNGEMEINSCHAFT"
    | "GRUNDSTUECKGEMEINSCHAFT"
    | "DR";
  inviduelleAnrede: string | null;
  titel: null | "DR" | "PROF" | "PROF_DR" | "DIPLOM_INF";
  vorname: string | null;
  nachname: string | null;
  eMailAdresse: string | null;
  kommentar: string | null;
  geschaeftspartner: Geschaeftspartner;
  adresse: Adresse;
  rufnummern: Rufnummer[] | null;
  zustaendigkeit: Zustaendigkeit[] | null;
  gewerbekennzeichnung: boolean | null;
  unternehmensart:
    | null
    | "LIEFERANT"
    | "NETZBETREIBER"
    | "MESSSTELLENBETREIBER"
    | "ÜBERTRAGUNGSNETZBETREIBER"
    | "BILANZKOORDINATOR"
    | "BILANZKREISVERANTWORTLICHER"
    | "ENERGIESERVICEANBIETER";
  gueltigkeitszeitraum?: Zeitraum;
  qualitaet?:
    null | "VOLLSTAENDIG" | "INFORMATIV" | "IM_SYSTEM_VORHANDEN" | "ERWARTET" | "VORLAEUFIG" | "UNVOLLSTAENDIG";
  [k: string]: unknown;
} | null;
export type Marktteilnehmer1 = {
  boTyp: string | null;
  versionStruktur: string | null;
  timestamp?: string | null;
  externeReferenzen: ExterneReferenz[] | null;
  guid?: string | null;
  anrede:
    | null
    | "HERR"
    | "FRAU"
    | "EHELEUTE"
    | "FIRMA"
    | "INDIVIDUELL"
    | "FAMILIE"
    | "ERBENGEMEINSCHAFT"
    | "WOHNGEMEINSCHAFT"
    | "GRUNDSTUECKGEMEINSCHAFT"
    | "DR";
  title: string | null;
  name1: string | null;
  name2: string | null;
  name3: string | null;
  gewerbekennzeichnung: boolean;
  hrnummer: string | null;
  amtsgericht: string | null;
  kontaktweg: ("ANSCHREIBEN" | "TELEFONAT" | "FAX" | "E_MAIL" | "SMS")[] | null;
  umsatzsteuerId: string | null;
  glaeubigerId: string | null;
  eMailAdresse: string | null;
  website: string | null;
  geschaeftspartnerrolle: ("LIEFERANT" | "DIENSTLEISTER" | "KUNDE" | "INTERESSENT" | "MARKTPARTNER")[] | null;
  partneradresse: Adresse;
  grundlageZurVerringerungDerUmlagenNachEnfg:
    null | "KUNDE_ERFUELLT_VORAUSSETZUNG" | "KUNDE_ERFUELLT_VORAUSSETZUNG_NICHT" | "KEINE_ANGABE";
  gruendeDerPrivilegierungNachEnFG:
    | (
        | "STROMSPEICHER_UND_VERLUSTENERGIE"
        | "ELEKTRISCH_ANGETRIEBENE_WAERMEPUMPEN"
        | "UMLAGEERHEBUNG_BEI_ANLAGEN_ZUR_VERSTROMUNG_VON_KUPPELGASEN"
        | "HERSTELLUNG_VON_GRUENEN_WASSERSTOFF"
        | "STROMKOSTENINTENSIVE_UNTERNEHMEN"
        | "HERSTELLUNG_VON_WASSERSTOFF_IN_STROMKOSTENINTENSIVEN_UNTERNEHMEN"
        | "SCHIENENBAHNEN"
        | "ELEKTRISCHE_BETRIEBENE_BUSSEN_IM_LINIENVERKEHR"
        | "LANDSTROMANLAGEN"
      )[]
    | null;
  bankverbindung: Bankverbindung;
  steuernummer: string | null;
  erreichbarkeit: Erreichbarkeit;
  marktrolle:
    | null
    | "NB"
    | "LF"
    | "MSB"
    | "MDL"
    | "DL"
    | "BKV"
    | "BIKO"
    | "UENB"
    | "KUNDE_SELBST_NN"
    | "MGV"
    | "EIV"
    | "RB"
    | "KUNDE"
    | "INTERESSENT"
    | "GMSB"
    | "AMSB";
  rollencodenummer: string | null;
  rollencodetyp: null | "ZERO" | "GLN" | "BDEW" | "DVGW";
  makoadresse: string | null;
  ansprechpartner: Ansprechpartner;
  rolle: null | "ANDERE_PARTEI" | "EMPFAENGER";
  gueltigkeitszeitraum?: Zeitraum;
  qualitaet?:
    null | "VOLLSTAENDIG" | "INFORMATIV" | "IM_SYSTEM_VORHANDEN" | "ERWARTET" | "VORLAEUFIG" | "UNVOLLSTAENDIG";
  [k: string]: unknown;
} | null;
export type Konfigurationsprodukt1 = {
  timestamp?: string | null;
  produktcode: string | null;
  guid?: string | null;
  leistungskurvendefinition: string | null;
  schaltzeitdefinition: string | null;
  auftraggebenderMarktpartner: Marktteilnehmer;
  empfangendeMarktrolle:
    | null
    | "NB"
    | "LF"
    | "MSB"
    | "MDL"
    | "DL"
    | "BKV"
    | "BIKO"
    | "UENB"
    | "KUNDE_SELBST_NN"
    | "MGV"
    | "EIV"
    | "RB"
    | "KUNDE"
    | "INTERESSENT"
    | "GMSB"
    | "AMSB";
  [k: string]: unknown;
} | null;
export type Netzlokationsabrechnungsdaten = {
  timestamp?: string | null;
  guid?: string | null;
  artikelId: string | null;
  artikelIdTyp: null | "ARTIKELID" | "GRUPPENARTIKELID";
  blindarbeitszahler: null | "ANSCHLUSSNEHMER" | "LIEFERANT";
  findetBlindarbeitsAbrechnungStatt: boolean | null;
  lieferantBereitZurZahlungBlindarbeit: boolean | null;
  [k: string]: unknown;
} & Netzlokationsabrechnungsdaten1;
export type Netzlokationsabrechnungsdaten1 = {
  timestamp?: string | null;
  guid?: string | null;
  artikelId: string | null;
  artikelIdTyp: null | "ARTIKELID" | "GRUPPENARTIKELID";
  blindarbeitszahler: null | "ANSCHLUSSNEHMER" | "LIEFERANT";
  findetBlindarbeitsAbrechnungStatt: boolean | null;
  lieferantBereitZurZahlungBlindarbeit: boolean | null;
  [k: string]: unknown;
} | null;
export type MarktpartnerDetails = {
  rollencodenummer: string | null;
  code: string | null;
  marktrolle:
    | null
    | "NB"
    | "LF"
    | "MSB"
    | "MDL"
    | "DL"
    | "BKV"
    | "BIKO"
    | "UENB"
    | "KUNDE_SELBST_NN"
    | "MGV"
    | "EIV"
    | "RB"
    | "KUNDE"
    | "INTERESSENT"
    | "GMSB"
    | "AMSB";
  timestamp?: string | null;
  guid?: string | null;
  weiterverpflichtet: boolean | null;
  [k: string]: unknown;
} & MarktpartnerDetails1;
export type MarktpartnerDetails1 = {
  rollencodenummer: string | null;
  code: string | null;
  marktrolle:
    | null
    | "NB"
    | "LF"
    | "MSB"
    | "MDL"
    | "DL"
    | "BKV"
    | "BIKO"
    | "UENB"
    | "KUNDE_SELBST_NN"
    | "MGV"
    | "EIV"
    | "RB"
    | "KUNDE"
    | "INTERESSENT"
    | "GMSB"
    | "AMSB";
  timestamp?: string | null;
  guid?: string | null;
  weiterverpflichtet: boolean | null;
  [k: string]: unknown;
} | null;
export type LokationsTypZuordnung = {
  timestamp?: string | null;
  guid?: string | null;
  lokationstyp: null | "MALO" | "MELO" | "NELO" | "SR" | "TR";
  lokationsId: string | null;
  [k: string]: unknown;
} & LokationsTypZuordnung1;
export type LokationsTypZuordnung1 = {
  timestamp?: string | null;
  guid?: string | null;
  lokationstyp: null | "MALO" | "MELO" | "NELO" | "SR" | "TR";
  lokationsId: string | null;
  [k: string]: unknown;
} | null;
export type Messprodukt = {
  timestamp?: string | null;
  guid?: string | null;
  messproduktId: string | null;
  verwendungszwecke: Verwendungszweck[] | null;
  verbrauchsart: null | "KL" | "KLW" | "KLWS" | "W" | "WS" | "WK" | "EM" | "STRB" | "STW";
  unterbrechbarkeit: null | "UV" | "NUV";
  waermenutzung:
    | null
    | "SPEICHERHEIZUNG"
    | "WAERMEPUMPE"
    | "DIREKTHEIZUNG"
    | "WAERMEPUMPE_WAERME_KAELTE"
    | "WAERMEPUMPE_KAELTE"
    | "WAERMEPUMPE_WAERME";
  zaehlzeiten: Zaehlzeitregister;
  zweiteMessung: boolean | null;
  werteuebermittlungAnNB?: boolean | null;
  emobilitaetsart: null | "WALLBOX" | "E_MOBILITAETSLADESAEULE" | "LADEPARK";
  [k: string]: unknown;
} & Messprodukt1;
export type Zaehlzeitregister = {
  timestamp?: string | null;
  guid?: string | null;
  zaehlzeitDefinition: string | null;
  register: string | null;
  schwachlastfaehig: null | "NICHT_SCHWACHLASTFAEHIG" | "SCHWACHLASTFAEHIG";
  [k: string]: unknown;
} & Zaehlzeitregister1;
export type Zaehlzeitregister1 = {
  timestamp?: string | null;
  guid?: string | null;
  zaehlzeitDefinition: string | null;
  register: string | null;
  schwachlastfaehig: null | "NICHT_SCHWACHLASTFAEHIG" | "SCHWACHLASTFAEHIG";
  [k: string]: unknown;
} | null;
export type Messprodukt1 = {
  timestamp?: string | null;
  guid?: string | null;
  messproduktId: string | null;
  verwendungszwecke: Verwendungszweck[] | null;
  verbrauchsart: null | "KL" | "KLW" | "KLWS" | "W" | "WS" | "WK" | "EM" | "STRB" | "STW";
  unterbrechbarkeit: null | "UV" | "NUV";
  waermenutzung:
    | null
    | "SPEICHERHEIZUNG"
    | "WAERMEPUMPE"
    | "DIREKTHEIZUNG"
    | "WAERMEPUMPE_WAERME_KAELTE"
    | "WAERMEPUMPE_KAELTE"
    | "WAERMEPUMPE_WAERME";
  zaehlzeiten: Zaehlzeitregister;
  zweiteMessung: boolean | null;
  werteuebermittlungAnNB?: boolean | null;
  emobilitaetsart: null | "WALLBOX" | "E_MOBILITAETSLADESAEULE" | "LADEPARK";
  [k: string]: unknown;
} | null;

export interface Netzlokation {
  boTyp: string | null;
  versionStruktur: string | null;
  timestamp?: string | null;
  externeReferenzen: ExterneReferenz[] | null;
  guid?: string | null;
  netzlokationsId: string | null;
  sparte: null | "STROM" | "GAS" | "FERNWAERME" | "NAHWAERME" | "WASSER" | "ABWASSER";
  netzanschlussleistung: Menge;
  grundzustaendigerMSBCodeNr: string | null;
  steuerkanal: boolean | null;
  obisKennzahl: string | null;
  verwendungszweck: Verwendungszweck;
  konfigurationsprodukte: Konfigurationsprodukt[] | null;
  eigenschaftMSBLokation:
    | null
    | "NB"
    | "LF"
    | "MSB"
    | "MDL"
    | "DL"
    | "BKV"
    | "BIKO"
    | "UENB"
    | "KUNDE_SELBST_NN"
    | "MGV"
    | "EIV"
    | "RB"
    | "KUNDE"
    | "INTERESSENT"
    | "GMSB"
    | "AMSB";
  lokationsbuendelObjektcode: string | null;
  vorgelagerteLokationsId: string | null;
  abrechnungsdaten: Netzlokationsabrechnungsdaten[] | null;
  marktrollen: MarktpartnerDetails[] | null;
  vorgelagerteLokationsIds: LokationsTypZuordnung[] | null;
  messprodukte: Messprodukt[] | null;
  verwendungszwecke: Verwendungszweck[] | null;
  gueltigkeitszeitraum?: Zeitraum;
  qualitaet?:
    null | "VOLLSTAENDIG" | "INFORMATIV" | "IM_SYSTEM_VORHANDEN" | "ERWARTET" | "VORLAEUFIG" | "UNVOLLSTAENDIG";
  [k: string]: unknown;
}
