/* eslint-disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

export type ExterneReferenz = {
  exRefName?: string | null;
  exRefWert?: string | null;
  timestamp?: string | null;
  guid?: string | null;
  [k: string]: unknown;
} & ExterneReferenz1;
export type ExterneReferenz1 = {
  exRefName?: string | null;
  exRefWert?: string | null;
  timestamp?: string | null;
  guid?: string | null;
  [k: string]: unknown;
} | null;
export type Geraet = {
  timestamp?: string | null;
  guid?: string | null;
  geraetenummer?: string | null;
  geraeteeigenschaften?: Geraeteeigenschaften;
  geraeteart?:
    | null
    | "WANDLER"
    | "KOMMUNIKATIONSEINRICHTUNG"
    | "TECHNISCHE_STEUEREINRICHTUNG"
    | "MENGENUMWERTER"
    | "SMARTMETER_GATEWAY"
    | "STEUERBOX"
    | "ZAEHLEINRICHTUNG";
  [k: string]: unknown;
} & Geraet1;
export type Geraeteeigenschaften = {
  timestamp?: string | null;
  guid?: string | null;
  geraetetyp:
    | "WECHSELSTROMZAEHLER"
    | "DREHSTROMZAEHLER"
    | "ZWEIRICHTUNGSZAEHLER"
    | "RLM_ZAEHLER"
    | "IMS_ZAEHLER"
    | "BALGENGASZAEHLER"
    | "MAXIMUMZAEHLER"
    | "MULTIPLEXANLAGE"
    | "PAUSCHALANLAGE"
    | "VERSTAERKERANLAGE"
    | "SUMMATIONSGERAET"
    | "IMPULSGEBER"
    | "EDL_21_ZAEHLERAUFSATZ"
    | "VIER_QUADRANTEN_LASTGANGZAEHLER"
    | "MENGENUMWERTER"
    | "STROMWANDLER"
    | "SPANNUNGSWANDLER"
    | "DATENLOGGER"
    | "KOMMUNIKATIONSANSCHLUSS"
    | "MODEM"
    | "TELEKOMMUNIKATIONSEINRICHTUNG"
    | "DREHKOLBENGASZAEHLER"
    | "TURBINENRADGASZAEHLER"
    | "ULTRASCHALLZAEHLER"
    | "WIRBELGASZAEHLER"
    | "MODERNE_MESSEINRICHTUNG"
    | "ELEKTRONISCHER_HAUSHALTSZAEHLER"
    | "STEUEREINRICHTUNG"
    | "TECHNISCHESTEUEREINRICHTUNG"
    | "TARIFSCHALTGERAET"
    | "RUNDSTEUEREMPFAENGER"
    | "OPTIONALE_ZUS_ZAEHLEINRICHTUNG"
    | "MESSWANDLERSATZ_IMS_MME"
    | "KOMBIMESSWANDLER_IMS_MME"
    | "TARIFSCHALTGERAET_IMS_MME"
    | "RUNDSTEUEREMPFAENGER_IMS_MME"
    | "TEMPERATUR_KOMPENSATION"
    | "HOECHSTBELASTUNGS_ANZEIGER"
    | "SONSTIGES_GERAET"
    | "SMARTMETERGATEWAY"
    | "STEUERBOX"
    | "BLOCKSTROMWANDLER"
    | "KOMBIMESSWANDLER";
  geraetemerkmal?:
    | null
    | "EINTARIF"
    | "ZWEITARIF"
    | "MEHRTARIF"
    | "GAS_G2P5"
    | "GAS_G4"
    | "GAS_G6"
    | "GAS_G10"
    | "GAS_G16"
    | "GAS_G25"
    | "GAS_G40"
    | "GAS_G65"
    | "GAS_G100"
    | "GAS_G160"
    | "GAS_G250"
    | "GAS_G400"
    | "GAS_G650"
    | "GAS_G1000"
    | "GAS_G1600"
    | "GAS_G2500"
    | "IMPULSGEBER_G4_G100"
    | "IMPULSGEBER_G100"
    | "MODEM_GSM"
    | "MODEM_GPRS"
    | "MODEM_FUNK"
    | "MODEM_GSM_O_LG"
    | "MODEM_GSM_M_LG"
    | "MODEM_FESTNETZ"
    | "MODEM_GPRS_M_LG"
    | "PLC_COM"
    | "ETHERNET_KOM"
    | "DSL_KOM"
    | "LTE_KOM"
    | "RUNDSTEUEREMPFAENGER"
    | "TARIFSCHALTGERAET"
    | "ZUSTANDS_MU"
    | "TEMPERATUR_MU"
    | "KOMPAKT_MU"
    | "SYSTEM_MU"
    | "UNBESTIMMT"
    | "WASSER_MWZW"
    | "WASSER_WZWW"
    | "WASSER_WZ01"
    | "WASSER_WZ02"
    | "WASSER_WZ03"
    | "WASSER_WZ04"
    | "WASSER_WZ05"
    | "WASSER_WZ06"
    | "WASSER_WZ07"
    | "WASSER_WZ08"
    | "WASSER_WZ09"
    | "WASSER_WZ10"
    | "WASSER_VWZ04"
    | "WASSER_VWZ05"
    | "WASSER_VWZ06"
    | "WASSER_VWZ07"
    | "WASSER_VWZ10"
    | "GAS_G350"
    | "GAS_G4000"
    | "GAS_G6500"
    | "GAS_G10000"
    | "GAS_G12500"
    | "GAS_G16000";
  Parameter?: {
    [k: string]: string | null;
  } | null;
  [k: string]: unknown;
} & Geraeteeigenschaften1;
export type Geraeteeigenschaften1 = {
  timestamp?: string | null;
  guid?: string | null;
  geraetetyp:
    | "WECHSELSTROMZAEHLER"
    | "DREHSTROMZAEHLER"
    | "ZWEIRICHTUNGSZAEHLER"
    | "RLM_ZAEHLER"
    | "IMS_ZAEHLER"
    | "BALGENGASZAEHLER"
    | "MAXIMUMZAEHLER"
    | "MULTIPLEXANLAGE"
    | "PAUSCHALANLAGE"
    | "VERSTAERKERANLAGE"
    | "SUMMATIONSGERAET"
    | "IMPULSGEBER"
    | "EDL_21_ZAEHLERAUFSATZ"
    | "VIER_QUADRANTEN_LASTGANGZAEHLER"
    | "MENGENUMWERTER"
    | "STROMWANDLER"
    | "SPANNUNGSWANDLER"
    | "DATENLOGGER"
    | "KOMMUNIKATIONSANSCHLUSS"
    | "MODEM"
    | "TELEKOMMUNIKATIONSEINRICHTUNG"
    | "DREHKOLBENGASZAEHLER"
    | "TURBINENRADGASZAEHLER"
    | "ULTRASCHALLZAEHLER"
    | "WIRBELGASZAEHLER"
    | "MODERNE_MESSEINRICHTUNG"
    | "ELEKTRONISCHER_HAUSHALTSZAEHLER"
    | "STEUEREINRICHTUNG"
    | "TECHNISCHESTEUEREINRICHTUNG"
    | "TARIFSCHALTGERAET"
    | "RUNDSTEUEREMPFAENGER"
    | "OPTIONALE_ZUS_ZAEHLEINRICHTUNG"
    | "MESSWANDLERSATZ_IMS_MME"
    | "KOMBIMESSWANDLER_IMS_MME"
    | "TARIFSCHALTGERAET_IMS_MME"
    | "RUNDSTEUEREMPFAENGER_IMS_MME"
    | "TEMPERATUR_KOMPENSATION"
    | "HOECHSTBELASTUNGS_ANZEIGER"
    | "SONSTIGES_GERAET"
    | "SMARTMETERGATEWAY"
    | "STEUERBOX"
    | "BLOCKSTROMWANDLER"
    | "KOMBIMESSWANDLER";
  geraetemerkmal?:
    | null
    | "EINTARIF"
    | "ZWEITARIF"
    | "MEHRTARIF"
    | "GAS_G2P5"
    | "GAS_G4"
    | "GAS_G6"
    | "GAS_G10"
    | "GAS_G16"
    | "GAS_G25"
    | "GAS_G40"
    | "GAS_G65"
    | "GAS_G100"
    | "GAS_G160"
    | "GAS_G250"
    | "GAS_G400"
    | "GAS_G650"
    | "GAS_G1000"
    | "GAS_G1600"
    | "GAS_G2500"
    | "IMPULSGEBER_G4_G100"
    | "IMPULSGEBER_G100"
    | "MODEM_GSM"
    | "MODEM_GPRS"
    | "MODEM_FUNK"
    | "MODEM_GSM_O_LG"
    | "MODEM_GSM_M_LG"
    | "MODEM_FESTNETZ"
    | "MODEM_GPRS_M_LG"
    | "PLC_COM"
    | "ETHERNET_KOM"
    | "DSL_KOM"
    | "LTE_KOM"
    | "RUNDSTEUEREMPFAENGER"
    | "TARIFSCHALTGERAET"
    | "ZUSTANDS_MU"
    | "TEMPERATUR_MU"
    | "KOMPAKT_MU"
    | "SYSTEM_MU"
    | "UNBESTIMMT"
    | "WASSER_MWZW"
    | "WASSER_WZWW"
    | "WASSER_WZ01"
    | "WASSER_WZ02"
    | "WASSER_WZ03"
    | "WASSER_WZ04"
    | "WASSER_WZ05"
    | "WASSER_WZ06"
    | "WASSER_WZ07"
    | "WASSER_WZ08"
    | "WASSER_WZ09"
    | "WASSER_WZ10"
    | "WASSER_VWZ04"
    | "WASSER_VWZ05"
    | "WASSER_VWZ06"
    | "WASSER_VWZ07"
    | "WASSER_VWZ10"
    | "GAS_G350"
    | "GAS_G4000"
    | "GAS_G6500"
    | "GAS_G10000"
    | "GAS_G12500"
    | "GAS_G16000";
  Parameter?: {
    [k: string]: string | null;
  } | null;
  [k: string]: unknown;
} | null;
export type Geraet1 = {
  timestamp?: string | null;
  guid?: string | null;
  geraetenummer?: string | null;
  geraeteeigenschaften?: Geraeteeigenschaften;
  geraeteart?:
    | null
    | "WANDLER"
    | "KOMMUNIKATIONSEINRICHTUNG"
    | "TECHNISCHE_STEUEREINRICHTUNG"
    | "MENGENUMWERTER"
    | "SMARTMETER_GATEWAY"
    | "STEUERBOX"
    | "ZAEHLEINRICHTUNG";
  [k: string]: unknown;
} | null;

export interface Wechsel {
  boTyp?: string | null;
  versionStruktur?: string | null;
  timestamp?: string | null;
  externeReferenzen?: ExterneReferenz[] | null;
  guid?: string | null;
  sparte: "STROM" | "GAS" | "FERNWAERME" | "NAHWAERME" | "WASSER" | "ABWASSER";
  geraete: Geraet[];
  wechseldatum?: string | null;
  vollstaendig?: boolean | null;
  [k: string]: unknown;
}
