on:
  release:
    types:
      - created
    tags:
      - "v[0-9]+.[0-9]+.[0-9]+"
      - "**/v[0-9]+.[0-9]+.[0-9]+"

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - uses: actions/setup-node@master
        with:
          node-version: 14
      - uses: JS-DevTools/npm-publish@master
        with:
          token: ${{ secrets.NPM_PUBLISH_TOKEN }}
          # expires never!
          # https://github.com/Hochfrequenz/bo4e-dotnet-ts-models/settings/secrets/actions/NPM_PUBLISH_TOKEN
          # https://www.npmjs.com/settings/hf-kklein/tokens/
